package com.hwtechservicesllc.staging2022.datatypes;

/*
    Copyright (c) 2022  HW Tech Services, Inc., LLC

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

// from FixProtocol.org website www.fixprotocol.org

public enum FIXTag {

    // 1-100

    ACCOUNT(1, "Account"),
    ADV_ID(2, "AdvId"),
    ADV_REF_ID(3, "AdvRefId"),
    ADV_SIDE(4, "AdvSide"),
    ADV_TRANS_TYPE(5, "AdvTransType"),
    AVG_PX(6, "AvgPx"),
    BEGIN_SEQ_NO(7,"BeginSeqNo"),
    BEGIN_STRING(8, "BeginString"),
    BODY_LENGTH(9, "BodyLength"),
    CHECK_SUM(10, "CheckSum"),

    CL_ORD_ID(11, "ClOrdID"),
    COMMISSION(12, "Commission"),
    COMM_TYPE(13, "CommType"),
    CUM_QTY(14, "CumQty"),
    CURRENCY(15, "Currency"),
    END_SEQ_NO(16, "EndSeqNo"),
    EXEC_ID(17, "ExecID"),
    EXEC_INST(18, "ExecInst"),
    EXEC_REF_ID(19, "ExecRefID"),
    EXEC_TRANS_TYPE(20, "ExecTransType (replaced)"),

    HANDL_INST(21, "HandlInst"),
    ID_SOURCE(22, "IDSource"),
    IOI_ID(23, "IOIid"),
    IOI_OTH_SVC(24, "IOIOthSvc (no longer used)"),
    IOI_QLTY_IND(25, "IOIQltyInd"),
    IOI_REF_ID(26, "IOIRefID"),
    IOI_SHARES(27, "IOIShares"),
    IOI_TRANS_TYPE(28, "IOITransType"),
    LAST_CAPACITY(29, "LastCapacity"),
    LAST_MKT(30, "LastMkt"),

    LAST_PX(31, "LastPx"),
    LAST_SHARES(32, "LastShares"),
    LINES_OF_TEXT(33, "LinesOfText"),
    MSG_SEQ_NUM(34, "MsgSeqNum"),
    MSG_TYPE(35, "MsgType"),
    NEW_SEQ_NO(36, "NewSeqNo"),
    ORDER_ID(37, "OrderID"),
    ORDER_QTY(38, "OrderQty"),
    ORD_STATUS(39, "OrdStatus"),
    ORD_TYPE(40, "OrdType"),

    ORIG_CL_ORD_ID(41, "OrigClOrdID"),
    ORIG_TIME(42, "OrigTime"),
    POSS_DUP_FLAG(43, "PossDupFlag"),
    PRICE(44, "Price"),
    REF_SEQ_NUM(45, "RefSeqNum"),
    RELATD_SYM(46, "RelatdSym (No longer used)"),
    RULE_80_A(47, "Rule80A (no longer used)"),
    SECURITY_ID(48, "SecurityID"),
    SENDER_COMP_ID(49, "SenderCompID"),
    SENDER_SUB_ID(50, "SenderSubID"),

    SENDING_DATE(51, "SendingDate (no longer used)"),
    SENDING_TIME(52, "SendingTime"),
    QUANTITY(53, "Quantity (formerly Shares)"),
    SIDE(54, "Side"),
    SYMBOL(55, "Symbol"),
    TARGET_COMP_ID(56, "TargetCompID"),
    TARGET_SUB_ID(57, "TargetSubID"),
    TEXT(58, "Text"),
    TIME_IN_FORCE(59, "TimeInForce"),
    TRANSACT_TIME(60, "TransactTime"),

    URGENCY(61, "Urgency"),
    VALID_UNTIL_TIME(62, "ValidUntilTime"),
    SETTLMNT_TYP(63, "SettlmntTyp"),
    FUT_SETT_DATE(64, "FutSettDate"),
    SYMBOL_SFX(65, "SymbolSfx"),
    LIST_ID(66, "ListID"),
    LIST_SEQ_NO(67, "ListSeqNo"),
    TOT_NO_ORDERS(68, "TotNoOrders (formerly named: ListNoOrds)"),
    LIST_EXEC_INST(69, "ListExecInst"),
    ALLOC_ID(70, "AllocID"),
    
    ALLOC_TRANS_TYPE(71, "AllocTransType"),
    REF_ALLOC_ID(72, "RefAllocID"),
    NO_ORDERS(73, "NoOrders"),
    AVG_PRX_PRECISION(74, "AvgPrxPrecision"),
    TRADE_DATE(75, "TradeDate"),
    EXEC_BROKER(76, "ExecBroker (replaced)"),
    OPEN_CLOSE(77, "OpenClose"),
    NO_ALLOCS(78, "NoAllocs"),
    ALLOC_ACCOUNT(79, "AllocAccount"),
    ALLOC_SHARES(80, "AllocShares"),
    
    PROCESS_CODE(81, "ProcessCode"),
    NO_RPTS(82, "NoRpts"),
    RPT_SEQ(83, "RptSeq"),
    CXL_QTY(84, "CxlQty"),
    NO_DLVY_INST(85, "NoDlvyInst (no longer used)"),
    DLVY_INST(86, "DlvyInst (no longer used)"),
    ALLOC_STATUS(87, "AllocStatus"),
    ALLOC_REJ_CODE(88, "AllocRejCode"),
    SIGNATURE(89, "Signature"),
    SECURE_DATA_LEN(90, "SecureDataLen"),
    
    SECURE_DATA(91, "SecureData"),
    BROKER_OF_CREDIT(92, "BrokerOfCredit (replaced)"),
    SIGNATURE_LENGTH(93, "SignatureLength"),
    EMAIL_TYPE(94, "EmailType"),
    RAW_DATA_LENGTH(95, "RawDataLength"),
    RAW_DATA(96, "RawData"),
    POSS_RESEND(97, "PossResend"),
    ENCRYPT_METHOD(98, "EncryptMethod"),
    STOP_PX(99, "StopPx"),
    EX_DESTINATION(100, "ExDestination"),

    
    // 101-200
    
    NOT_DEFINED(101, "(Not Defined)"),
    CXL_REJ_REASON(102, "CxlRejReason"),
    ORD_REJ_REASON(103, "OrdRejReason"),
    IOI_QUALIFIER(104, "IOIQualifier"),
    WAVE_NO(105, "WaveNo"),
    ISSUER(106, "Issuer"),
    SECURITY_DESC(107, "SecurityDesc"),
    HEART_BT_INT(108, "HeartBtInt"),
    CLIENT_ID(109, "ClientID (replaced)"),
    MIN_QTY(110, "MinQty"),

    MAX_FLOOR(111, "MaxFloor"),
    TEST_REQ_ID(112, "TestReqID"),
    REPORT_TO_EXCH(113, "ReportToExch"),
    LOCATE_REQD(114, "LocateReqd"),
    ON_BEHALF_OF_COMP_ID(115, "OnBehalfOfCompID"),
    ON_BEHALF_OF_SUB_ID(116, "OnBehalfOfSubID"),
    QUOTE_ID(117, "QuoteID"),
    NET_MONEY(118, "NetMoney"),
    SETTL_CURR_AMT(119, "SettlCurrAmt"),
    SETTL_CURRENCY(120, "SettlCurrency"),

    FOREX_REQ(121, "ForexReq"),
    ORIG_SENDING_TIME(122, "OrigSendingTime"),
    GAP_FILL_FLAG(123, "GapFillFlag"),
    NO_EXECS(124, "NoExecs"),
    CXL_TYPE(125, "CxlType (no longer used)"),
    EXPIRE_TIME(126, "ExpireTime"),
    DK_REASON(127, "DKReason"),
    DELIVER_TO_COMP_ID(128, "DeliverToCompID"),
    DELIVER_TO_SUB_ID(129, "DeliverToSubID"),
    IOI_NATURAL_FLAG(130, "IOINaturalFlag"),

    QUOTE_REQ_ID(131, "QuoteReqID"),
    BID_PX(132, "BidPx"),
    OFFER_PX(133, "OfferPx"),
    BID_SIZE(134, "BidSize"),
    OFFER_SIZE(135, "OfferSize"),
    NO_MISC_FEES(136, "NoMiscFees"),
    MISC_FEE_AMT(137, "MiscFeeAmt"),
    MISC_FEE_CURR(138, "MiscFeeCurr"),
    MISC_FEE_TYPE(139, "MiscFeeType"),
    PREV_CLOSE_PX(140, "PrevClosePx"),

    RESET_SEQ_NUM_FLAG(141, "ResetSeqNumFlag"),
    SENDER_LOCATION_ID(142, "SenderLocationID"),
    TARGET_LOCATION_ID(143, "TargetLocationID"),
    ON_BEHALF_OF_LOCATION_ID(144, "OnBehalfOfLocationID"),
    DELIVER_TO_LOCATION_ID(145, "DeliverToLocationID"),
    NO_RELATED_SYM(146, "NoRelatedSym"),
    SUBJECT(147, "Subject"),
    HEADLINE(148, "Headline"),
    URL_LINK(149, "URLLink"),
    EXEC_TYPE(150, "ExecType"),

    LEAVES_QTY(151, "LeavesQty"),
    CASH_ORDER_QTY(152, "CashOrderQty"),
    ALLOC_AVG_PX(153, "AllocAvgPx"),
    ALLOC_NET_MONEY(154, "AllocNetMoney"),
    SETTL_CURR_FX_RATE(155, "SettlCurrFxRate"),
    SETTL_CURR_FX_RATE_CALC(156, "SettlCurrFxRateCalc"),
    NUM_DAYS_INTEREST(157, "NumDaysInterest"),
    ACCRUED_INTEREST_RATE(158, "AccruedInterestRate"),
    ACCRUED_INTEREST_AMT(159, "AccruedInterestAmt"),
    SETTL_INST_MODE(160, "SettlInstMode"),

    ALLOC_TEXT(161, "AllocText"),
    SETTL_INST_ID(162, "SettlInstID"),
    SETTL_INST_TRANS_TYPE(163, "SettlInstTransType"),
    EMAIL_THREAD_ID(164, "EmailThreadID"),
    SETTL_INST_SOURCE(165, "SettlInstSource"),
    SETTL_LOCATION(166, "SettlLocation (replaced)"),
    SECURITY_TYPE(167, "SecurityType"),
    EFFECTIVE_TIME(168, "EffectiveTime"),
    STAND_INST_DB_TYPE(169, "StandInstDbType"),
    STAND_INST_DB_NAME(170, "StandInstDbName"),

    STAND_INST_DB_ID(171, "StandInstDbID"),
    SETTL_DELIVERY_TYPE(172, "SettlDeliveryType"),
    SETTL_DEPOSITORY_CODE(173, "SettlDepositoryCode (replaced)"),
    SETTL_BRKR_CODE(174, "SettlBrkrCode (replaced)"),
    SETTL_INST_CODE(175, "SettlInstCode (replaced)"),
    SECURITY_SETTL_AGENT_NAME(176, "SecuritySettlAgentName (replaced)"),
    SECURITY_SETTL_AGENT_CODE(177, "SecuritySettlAgentCode (replaced)"),
    SECURITY_SETTL_AGENT_ACCT_NUM(178, "SecuritySettlAgentAcctNum (replaced)"),
    SECURITY_SETTL_AGENT_ACCT_NAME(179, "SecuritySettlAgentAcctName (replaced)"),
    SECURITY_SETTL_AGENT_CONTACT_NAME(180, "SecuritySettlAgentContactName (replaced)"),

    SECURITY_SETTL_AGENT_CONTACT_PHONE(181, "SecuritySettlAgentContactPhone (replaced)"),
    CASH_SETTL_AGENT_NAME(182, "CashSettlAgentName (replaced)"),
    CASH_SETTL_AGENT_CODE(183, "CashSettlAgentCode (replaced)"),
    CASH_SETTL_AGENT_ACCT_NUM(184, "CashSettlAgentAcctNum (replaced)"),
    CASH_SETTL_AGENT_ACCT_NAME(185, "CashSettlAgentAcctName (replaced)"),
    CASH_SETTL_AGENT_CONTACT_NAME(186, "CashSettlAgentContactName (replaced)"),
    CASH_SETTL_AGENT_CONTACT_PHONE(187, "CashSettlAgentContactPhone (replaced)"),
    BID_SPOT_RATE(188, "BidSpotRate"),
    BID_FORWARD_POINTS(189, "BidForwardPoints"),
    OFFER_SPOT_RATE(190, "OfferSpotRate"),

    OFFER_FORWARD_POINTS(191, "OfferForwardPoints"),
    ORDER_QTY_2(192, "OrderQty2"),
    FUT_SETT_DATE_2(193, "FutSettDate2"),
    LAST_SPOT_RATE(194, "LastSpotRate"),
    LAST_FORWARD_POINTS(195, "LastForwardPoints"),
    ALLOC_LINK_ID(196, "AllocLinkID"),
    ALLOC_LINK_TYPE(197, "AllocLinkType"),
    SECONDARY_ORDER_ID(198, "SecondaryOrderID"),
    NO_IOI_QUALIFIERS(199, "NoIOIQualifiers"),
    MATURITY_MONTH_YEAR(200, "MaturityMonthYear"),


    // 201-300
    
    PUT_OR_CALL(201, "PutOrCall (replaced)"),
    STRIKE_PRICE(202, "StrikePrice"),
    COVERED_OR_UNCOVERED(203, "CoveredOrUncovered"),
    CUSTOMER_OR_FIRM(204, "CustomerOrFirm (replaced)"),
    MATURITY_DAY(205, "MaturityDay (replaced)"),
    OPT_ATTRIBUTE(206, "OptAttribute"),
    SECURITY_EXCHANGE(207, "SecurityExchange"),
    NOTIFY_BROKER_OF_CREDIT(208, "NotifyBrokerOfCredit"),
    ALLOC_HANDL_INST(209, "AllocHandlInst"),
    MAX_SHOW(210, "MaxShow"),

    PEG_DIFFERENCE(211, "PegDifference"),
    XML_DATA_LEN(212, "XmlDataLen"),
    XML_DATA(213, "XmlData"),
    SETTL_INST_REF_ID(214, "SettlInstRefID"),
    NO_ROUTING_IDS(215, "NoRoutingIDs"),
    ROUTING_TYPE(216, "RoutingType"),
    ROUTING_ID(217, "RoutingID"),
    SPREAD_TO_BENCHMARK(218, "SpreadToBenchmark"),
    BENCHMARK(219, "Benchmark (no longer used)"),

	// 220-222,    Reserved/Allocated to the Fixed Income proposal	
	BENCHMARK_CURVE_CURRENCY(220, "BenchmarkCurveCurrency"),
	BENCHMARK_CURVE_NAME(221, "BenchmarkCurveName"),
	BENCHMARK_CURVE_POINT(222, "BenchmarkCurvePoint"),
	// 220-222,    Reserved/Allocated to the Fixed Income proposal	
    COUPON_RATE(223, "CouponRate"),
	// 224-230,    Reserved/Allocated to the Fixed Income proposal
	COUPON_PAYMENT_DATE(224, "CouponPaymentDate"),
	ISSUE_DATE(225, "IssueDate"),
	REPURCHASE_TERM(226, "RepurchaseTerm (Deprecated)"),
	REPURCHASE_RATE(227, "RepurchaseRate (Deprecated)"),
	FACTOR(228, "Factor"),
	TRADE_ORIGINATION_DATE(229, "TradeOriginationDate"),
	EX_DATE(230, "ExDate"),
	// 224-230,    Reserved/Allocated to the Fixed Income proposal

    CONTRACT_MULTIPLIER(231, "ContractMultiplier"),
	// 232-261,    Reserved/Allocated to the Fixed Income proposal
	NO_STIPULATIONS(232, "NoStipulations"),
	STIPULATION_TYPE(233, "StipulationType"),
	STIPULATION_VALUE(234, "StipulationValue"),
	YIELD_TYPE(235, "YieldType"),
	YIELD(236, "Yield"),
	TOTAL_TAKEDOWN(237, "TotalTakedown"),
	CONCESSION(238, "Concession"),
	REPO_COLLATERAL_SECURITY_TYPE(239, "RepoCollateralSecurityType (Deprecated)"),
	REDEMPTION_DATE(240, "RedemptionDate (Deprecated)"),

	UNDERLYING_COUPON_PAYMENT_DATE(241, "UnderlyingCouponPaymentDate"),
	UNDERLYING_ISSUE_DATE(242, "UnderlyingIssueDate"),
	UNDERLYING_REPO_COLLATERAL_SECURITY_TYPE(243, "UnderlyingRepoCollateralSecurityType (Deprecated"),
	UNDERLYING_REPURCHASE_TERM(244, "UnderlyingRepurchaseTerm (Deprecated)"),
	UNDERLYING_REPURCHASE_RATE(245, "UnderlyingRepurchaseRate (Deprecated)"),
	UNDERLYING_FACTOR(246, "UnderlyingFactor"),
	UNDERLYING_REDEMPTION_DATE(247, "UnderlyingRedemptionDate (Deprecated)"),
	LEG_COUPON_PAYMENT_DATE(248, "LegCouponPaymentDate"),
	LEG_ISSUE_DATE(249, "LegIssueDate"),
	LEG_REPO_COLLATERAL_SECURITY_TYPE(250, "LegRepoCollateralSecurityType (Deprecated)"),

	LEG_REPURCHASE_TERM(251, "LegRepurchaseTerm (Deprecated)"),
	LEG_REPURCHASE_RATE(252, "LegRepurchaseRate (Deprecated)"),
	LEG_FACTOR(253, "LegFactor"),
	LEG_REDEMPTION_DATE(254, "LegRedemptionDate (Deprecated)"),
	CREDIT_RATING(255, "CreditRating"),
	UNDERLYING_CREDIT_RATING(256, "UnderlyingCreditRating"),
	LEG_CREDIT_RATING(257, "LegCreditRating"),
	TRADED_FLAT_SWITCH(258, "TradedFlatSwitch"),
	BASIS_FEATURE_DATE(259, "BasisFeatureDate"),
	BASIS_FEATURE_PRICE(260, "BasisFeaturePrice"),

	// xx(261, ""),
	// 232-261,    Reserved/Allocated to the Fixed Income proposal

    MD_REQ_ID(262, "MDReqID"),
    SUBSCRIPTION_REQUEST_TYPE(263, "SubscriptionRequestType"),
    MARKET_DEPTH(264, "MarketDepth"),
    MD_UPDATE_TYPE(265, "MDUpdateType"),
    AGGREGATED_BOOK(266, "AggregatedBook"),
    NO_MD_ENTRY_TYPES(267, "NoMDEntryTypes"),
    NO_MD_ENTRIES(268, "NoMDEntries"),
    MD_ENTRY_TYPE(269, "MDEntryType"),
    MD_ENTRY_PX(270, "MDEntryPx"),

    MD_ENTRY_SIZE(271, "MDEntrySize"),
    MD_ENTRY_DATE(272, "MDEntryDate"),
    MD_ENTRY_TIME(273, "MDEntryTime"),
    TICK_DIRECTION(274, "TickDirection"),
    MD_MKT(275, "MDMkt"),
    QUOTE_CONDITION(276, "QuoteCondition"),
    TRADE_CONDITION(277, "TradeCondition"),
    MD_ENTRY_ID(278, "MDEntryID"),
    MD_UPDATE_ACTION(279, "MDUpdateAction"),
    MD_ENTRY_REF_ID(280, "MDEntryRefID"),

    MD_REQ_REJ_REASON(281, "MDReqRejReason"),
    MD_ENTRY_ORIGINATOR(282, "MDEntryOriginator"),
    LOCATION_ID(283, "LocationID"),
    DESK_ID(284, "DeskID"),
    DELETE_REASON(285, "DeleteReason"),
    OPEN_CLOSE_SETTLE_FLAG(286, "OpenCloseSettleFlag"),
    SELLER_DAYS(287, "SellerDays"),
    MD_ENTRY_BUYER(288, "MDEntryBuyer"),
    MD_ENTRY_SELLER(289, "MDEntrySeller"),
    MD_ENTRY_POSITION_NO(290, "MDEntryPositionNo"),

    FINANCIAL_STATUS(291, "FinancialStatus"),
    CORPORATE_ACTION(292, "CorporateAction"),
    DEF_BID_SIZE(293, "DefBidSize"),
    DEF_OFFER_SIZE(294, "DefOfferSize"),
    NO_QUOTE_ENTRIES(295, "NoQuoteEntries"),
    NO_QUOTE_SETS(296, "NoQuoteSets"),
    QUOTE_ACK_STATUS(297, "QuoteAckStatus"),
    QUOTE_CANCEL_TYPE(298, "QuoteCancelType"),
    QUOTE_ENTRY_ID(299, "QuoteEntryID"),
    QUOTE_REJECT_REASON(300, "QuoteRejectReason"),


    // 301-400
    
    QUOTE_RESPONSE_LEVEL(301, "QuoteResponseLevel"),
    QUOTE_SET_ID(302, "QuoteSetID"),
    QUOTE_REQUEST_TYPE(303, "QuoteRequestType"),
    TOT_QUOTE_ENTRIES(304, "TotQuoteEntries"),
    UNDERLYING_ID_SOURCE(305, "UnderlyingIDSource"),
    UNDERLYING_ISSUER(306, "UnderlyingIssuer"),
    UNDERLYING_SECURITY_DESC(307, "UnderlyingSecurityDesc"),
    UNDERLYING_SECURITY_EXCHANGE(308, "UnderlyingSecurityExchange"),
    UNDERLYING_SECURITY_ID(309, "UnderlyingSecurityID"),
    UNDERLYING_SECURITY_TYPE(310, "UnderlyingSecurityType"),

    UNDERLYING_SYMBOL(311, "UnderlyingSymbol"),
    UNDERLYING_SYMBOL_SFX(312, "UnderlyingSymbolSfx"),
    UNDERLYING_MATURITY_MONTH_YEAR(313, "UnderlyingMaturityMonthYear"),
    UNDERLYING_MATURITY_DAY(314, "UnderlyingMaturityDay"),
    UNDERLYING_PUT_OR_CALL(315, "UnderlyingPutOrCall"),
    UNDERLYING_STRIKE_PRICE(316, "UnderlyingStrikePrice"),
    UNDERLYING_OPT_ATTRIBUTE(317, "UnderlyingOptAttribute"),
    UNDERLYING_CURRENCY(318, "UnderlyingCurrency"),
    RATIO_QTY(319, "RatioQty (unused)"),
    SECURITY_REQ_ID(320, "SecurityReqID"),

    SECURITY_REQUEST_TYPE(321, "SecurityRequestType"),
    SECURITY_RESPONSE_ID(322, "SecurityResponseID"),
    SECURITY_RESPONSE_TYPE(323, "SecurityResponseType"),
    SECURITY_STATUS_REQ_ID(324, "SecurityStatusReqID"),
    UNSOLICITED_INDICATOR(325, "UnsolicitedIndicator"),
    SECURITY_TRADING_STATUS(326, "SecurityTradingStatus"),
    HALT_REASON(327, "HaltReason"),
    IN_VIEW_OF_COMMON(328, "InViewOfCommon"),
    DUE_TO_RELATED(329, "DueToRelated"),
    BUY_VOLUME(330, "BuyVolume"),

    SELL_VOLUME(331, "SellVolume"),
    HIGH_PX(332, "HighPx"),
    LOW_PX(333, "LowPx"),
    ADJUSTMENT(334, "Adjustment"),
    TRAD_SES_REQ_ID(335, "TradSesReqID"),
    TRADING_SESSION_ID(336, "TradingSessionID"),
    CONTRA_TRADER(337, "ContraTrader"),
    TRAD_SES_METHOD(338, "TradSesMethod"),
    TRAD_SES_MODE(339, "TradSesMode"),
    TRAD_SES_STATUS(340, "TradSesStatus"),

    TRAD_SES_START_TIME(341, "TradSesStartTime"),
    TRAD_SES_OPEN_TIME(342, "TradSesOpenTime"),
    TRAD_SES_PRE_CLOSE_TIME(343, "TradSesPreCloseTime"),
    TRAD_SES_CLOSE_TIME(344, "TradSesCloseTime"),
    TRAD_SES_END_TIME(345, "TradSesEndTime"),
    NUMBER_OF_ORDERS(346, "NumberOfOrders"),
    MESSAGE_ENCODING(347, "MessageEncoding"),
    ENCODED_ISSUER_LEN(348, "EncodedIssuerLen"),
    ENCODED_ISSUER(349, "EncodedIssuer"),
    ENCODED_SECURITY_DESC_LEN(350, "EncodedSecurityDescLen"),

    ENCODED_SECURITY_DESC(351, "EncodedSecurityDesc"),
    ENCODED_LIST_EXEC_INST_LEN(352, "EncodedListExecInstLen"),
    ENCODED_LIST_EXEC_INST(353, "EncodedListExecInst"),
    ENCODED_TEXT_LEN(354, "EncodedTextLen"),
    ENCODED_TEXT(355, "EncodedText"),
    ENCODED_SUBJECT_LEN(356, "EncodedSubjectLen"),
    ENCODED_SUBJECT(357, "EncodedSubject"),
    ENCODED_HEADLINE_LEN(358, "EncodedHeadlineLen"),
    ENCODED_HEADLINE(359, "EncodedHeadline"),
    ENCODED_ALLOC_TEXT_LEN(360, "EncodedAllocTextLen"),

    ENCODED_ALLOC_TEXT(361, "EncodedAllocText"),
    ENCODED_UNDERLYING_ISSUER_LEN(362, "EncodedUnderlyingIssuerLen"),
    ENCODED_UNDERLYING_ISSUER(363, "EncodedUnderlyingIssuer"),
    ENCODED_UNDERLYING_SECURITY_DESC_LEN(364, "EncodedUnderlyingSecurityDescLen"),
    ENCODED_UNDERLYING_SECURITY_DESC(365, "EncodedUnderlyingSecurityDesc"),
    ALLOC_PRICE(366, "AllocPrice"),
    QUOTE_SET_VALID_UNTIL_TIME(367, "QuoteSetValidUntilTime"),
    QUOTE_ENTRY_REJECT_REASON(368, "QuoteEntryRejectReason"),
    LAST_MSG_SEQ_NUM_PROCESSED(369, "LastMsgSeqNumProcessed"),
    ON_BEHALF_OF_SENDING_TIME(370, "OnBehalfOfSendingTime"),

    REF_TAG_ID(371, "RefTagID"),
    REF_MSG_TYPE(372, "RefMsgType"),
    SESSION_REJECT_REASON(373, "SessionRejectReason"),
    BID_REQUEST_TRANS_TYPE(374, "BidRequestTransType"),
    CONTRA_BROKER(375, "ContraBroker"),
    COMPLIANCE_ID(376, "ComplianceID"),
    SOLICITED_FLAG(377, "SolicitedFlag"),
    EXEC_RESTATEMENT_REASON(378, "ExecRestatementReason"),
    BUSINESS_REJECT_REF_ID(379, "BusinessRejectRefID"),
    BUSINESS_REJECT_REASON(380, "BusinessRejectReason"),

    GROSS_TRADE_AMT(381, "GrossTradeAmt"),
    NO_CONTRA_BROKERS(382, "NoContraBrokers"),
    MAX_MESSAGE_SIZE(383, "MaxMessageSize"),
    NO_MSG_TYPES(384, "NoMsgTypes"),
    MSG_DIRECTION(385, "MsgDirection"),
    NO_TRADING_SESSIONS(386, "NoTradingSessions"),
    TOTAL_VOLUME_TRADED(387, "TotalVolumeTraded"),
    DISCRETION_INST(388, "DiscretionInst"),
    DISCRETION_OFFSET(389, "DiscretionOffset"),
    BID_ID(390, "BidID"),

    CLIENT_BID_ID(391, "ClientBidID"),
    LIST_NAME(392, "ListName"),
    TOTAL_NUM_SECURITIES(393, "TotalNumSecurities"),
    BID_TYPE(394, "BidType"),
    NUM_TICKETS(395, "NumTickets"),
    SIDE_VALUE1(396, "SideValue1"), 
    SIDE_VALUE2(397, "SideValue2"),
    NO_BID_DESCRIPTORS(398, "NoBidDescriptors"),
    BID_DESCRIPTOR_TYPE(399, "BidDescriptorType"),
    BID_DESCRIPTOR(400, "BidDescriptor"),


    // 401-500
    
    SIDE_VALUE_IND(401, "SideValueInd"),
    LIQUIDITY_PCT_LOW(402, "LiquidityPctLow"),
    LIQUIDITY_PCT_HIGH(403, "LiquidityPctHigh"),
    LIQUIDITY_VALUE(404, "LiquidityValue"),
    EFP_TRACKING_ERROR(405, "EFPTrackingError"),
    FAIR_VALUE(406, "FairValue"),
    OUTSIDE_INDEX_PCT(407, "OutsideIndexPct"),
    VALUE_OF_FUTURES(408, "ValueOfFutures"),
    LIQUIDITY_IND_TYPE(409, "LiquidityIndType"),
    WT_AVERAGE_LIQUIDITY(410, "WtAverageLiquidity"),

    EXCHANGE_FOR_PHYSICAL(411, "ExchangeForPhysical"),
    OUT_MAIN_CNTRY_U_INDEX(412, "OutMainCntryUIndex"),
    CROSS_PERCENT(413, "CrossPercent"),
    PROG_RPT_REQS(414, "ProgRptReqs"),
    PROG_PERIOD_INTERVAL(415, "ProgPeriodInterval"),
    INC_TAX_IND(416, "IncTaxInd"),
    NUM_BIDDERS(417, "NumBidders"),
    TRADE_TYPE(418, "TradeType"),
    BASIS_PX_TYPE(419, "BasisPxType"),
    NO_BID_COMPONENTS(420, "NoBidComponents"),

    COUNTRY(421, "Country"),
    TOT_NO_STRIKES(422, "TotNoStrikes"),
    PRICE_TYPE(423, "PriceType"),
    DAY_ORDER_QTY(424, "DayOrderQty"),
    DAY_CUM_QTY(425, "DayCumQty"),
    DAY_AVG_PX(426, "DayAvgPx"),
    GT_BOOKING_INST(427, "GTBookingInst"),
    NO_STRIKES(428, "NoStrikes"),
    LIST_STATUS_TYPE(429, "ListStatusType"),
    NET_GROSS_IND(430, "NetGrossInd"),

    LIST_ORDER_STATUS(431, "ListOrderStatus"),
    EXPIRE_DATE(432, "ExpireDate"),
    LIST_EXEC_INST_TYPE(433, "ListExecInstType"),
    CXL_REJ_RESPONSE_TO(434, "CxlRejResponseTo"),
    UNDERLYING_COUPON_RATE(435, "UnderlyingCouponRate"),
    UNDERLYING_CONTRACT_MULTIPLIER(436, "UnderlyingContractMultiplier"),
    CONTRA_TRADE_QTY(437, "ContraTradeQty"),
    CONTRA_TRADE_TIME(438, "ContraTradeTime"),
    CLEARING_FIRM(439, "ClearingFirm"),
    CLEARING_ACCOUNT(440, "ClearingAccount"),
    
    LIQUIDITY_NUM_SECURITIES(441, "LiquidityNumSecurities"),
    MULTI_LEG_REPORTING_TYPE(442, "MultiLegReportingType"),
    STRIKE_TIME(443, "StrikeTime"),
    LIST_STATUS_TEXT(444, "ListStatusText"),
    LIST_STATUS_ENCODED_TEXT_LEN(445, "ListStatusEncodedTextLen"),
    LIST_STATUS_ENCODED_TEXT(446, "ListStatusEncodedText"),
	PARTY_ID_SOURCE(447, "PartyIDSource"),
	PARTY_ID(448, "PartyID"),
    TOTAL_VOLUME_TRADED_DATE(449, "TotalVolumeTradedDate (replaced)"),
    TOTAL_VOLUME_TRADED_TIME(450, "TotalVolumeTradedTime (replaced)"),

	NET_CHG_PREV_DAY(451, "NetChgPrevDay"),
	PARTY_ROLE(452, "PartyRole"),
	NO_PARTY_IDS(453, "NoPartyIDs"),
	NO_SECURITY_ALT_ID(454, "NoSecurityAltID"),
	SECURITY_ALT_ID(455, "SecurityAltID"),
	SECURITY_ALT_ID_SOURCE(456, "SecurityAltIDSource"),
	NO_UNDERLYING_SECURITY_ALT_ID(457, "NoUnderlyingSecurityAltID"),
	UNDERLYING_SECURITY_ALT_ID(458, "UnderlyingSecurityAltID"),
	UNDERLYING_SECURITY_ALT_ID_SOURCE(459, "UnderlyingSecurityAltIDSource"),
	PRODUCT(460, "Product"),

	CFI_CODE(461, "CFICode"),
	UNDERLYING_PRODUCT(462, "UnderlyingProduct"),
	UNDERLYING_CFI_CODE(463, "UnderlyingCFICode"),
	TEST_MESSAGE_INDICATOR(464, "TestMessageIndicator"),
	QUANTITY_TYPE(465, "QuantityType (Deprecated)"),
	BOOKING_REF_ID(466, "BookingRefID"),
	INDIVIDUAL_ALLOC_ID(467, "IndividualAllocID"),
	ROUNDING_DIRECTION(468, "RoundingDirection"),
	ROUNDING_MODULUS(469, "RoundingModulus"),
	COUNTRY_OF_ISSUE(470, "CountryOfIssue"),

	STATE_OR_PROVINCE_OF_ISSUE(471, "StateOrProvinceOfIssue"),
	LOCALE_OF_ISSUE(472, "LocaleOfIssue"),
	NO_REGIST_DTLS(473, "NoRegistDtls"),
	MAILING_DTLS(474, "MailingDtls"),
	INVESTOR_COUNTRY_OF_RESIDENCE(475, "InvestorCountryOfResidence"),
	PAYMENT_REF(476, "PaymentRef"),
	DISTRIB_PAYMENT_METHOD(477, "DistribPaymentMethod"),
	CASH_DISTRIB_CURR(478, "CashDistribCurr"),
	COMM_CURRENCY(479, "CommCurrency"),
	CANCELLATION_RIGHTS(480, "CancellationRights"),

	MONEY_LAUNDERING_STATUS(481, "MoneyLaunderingStatus"),
	MAILING_INST(482, "MailingInst"),
	TRANS_BKD_TIME(483, "TransBkdTime"),
	EXEC_PRICE_TYPE(484, "ExecPriceType"),
	EXEC_PRICE_ADJUSTMENT(485, "ExecPriceAdjustment"),
	DATE_OF_BIRTH(486, "DateOfBirth"),
	TRADE_REPORT_TRANS_TYPE(487, "TradeReportTransType"),
	CARD_HOLDER_NAME(488, "CardHolderName"),
	CARD_NUMBER(489, "CardNumber"),
	CARD_EXP_DATE(490, "CardExpDate"),

	CARD_ISS_NUM(491, "CardIssNum"),
	PAYMENT_METHOD(492, "PaymentMethod"),
	REGIST_ACCT_TYPE(493, "RegistAcctType"),
	DESIGNATION(494, "Designation"),
	TAX_ADVANTAGE_TYPE(495, "TaxAdvantageType"),
	REGIST_REJ_REASON_TEXT(496, "RegistRejReasonText"),
	FUND_RENEW_WAIV(497, "FundRenewWaiv"),
	CASH_DISTRIB_AGENT_NAME(498, "CashDistribAgentName"),
	CASH_DISTRIB_AGENT_CODE(499, "CashDistribAgentCode"),
	CASH_DISTRIB_AGENT_ACCT_NUMBER(500, "CashDistribAgentAcctNumber"),

	
    // 501-600
    
	CASH_DISTRIB_PAY_REF(501, "CashDistribPayRef"),
	CASH_DISTRIB_AGENT_ACCT_NAME(502, "CashDistribAgentAcctName"),
	CARD_START_DATE(503, "CardStartDate"),
	PAYMENT_DATE(504, "PaymentDate"),
	PAYMENT_REMITTER_ID(505, "PaymentRemitterID"),
	REGIST_STATUS(506, "RegistStatus"),
	REGIST_REJ_REASON_CODE(507, "RegistRejReasonCode"),
	REGIST_REF_ID(508, "RegistRefID"),
	REGIST_DTLS(509, "RegistDtls"),
	NO_DISTRIB_INSTS(510, "NoDistribInsts"),

	REGIST_EMAIL(511, "RegistEmail"),
	DISTRIB_PERCENTAGE(512, "DistribPercentage"),
	REGIST_ID(513, "RegistID"),
	REGIST_TRANS_TYPE(514, "RegistTransType"),
	EXEC_VALUATION_POINT(515, "ExecValuationPoint"),
	ORDER_PERCENT(516, "OrderPercent"),
	OWNERSHIP_TYPE(517, "OwnershipType"),
	NO_CONT_AMTS(518, "NoContAmts"),
	CONT_AMT_TYPE(519, "ContAmtType"),
	CONT_AMT_VALUE(520, "ContAmtValue"),

	CONT_AMT_CURR(521, "ContAmtCurr"),
	OWNER_TYPE(522, "OwnerType"),
	PARTY_SUB_ID(523, "PartySubID"),
	NESTED_PARTY_ID(524, "NestedPartyID"),
	NESTED_PARTY_ID_SOURCE(525, "NestedPartyIDSource"),
	SECONDARY_CL_ORD_ID(526, "SecondaryClOrdID"),
	SECONDARY_EXEC_ID(527, "SecondaryExecID"),
	ORDER_CAPACITY(528, "OrderCapacity"),
	ORDER_RESTRICTIONS(529, "OrderRestrictions"),
	MASS_CANCEL_REQUEST_TYPE(530, "MassCancelRequestType"),

	MASS_CANCEL_RESPONSE(531, "MassCancelResponse"),
	MASS_CANCEL_REJECT_REASON(532, "MassCancelRejectReason"),
	TOTAL_AFFECTED_ORDERS(533, "TotalAffectedOrders"),
	NO_AFFECTED_ORDERS(534, "NoAffectedOrders"),
	AFFECTED_ORDER_ID(535, "AffectedOrderID"),
	AFFECTED_SECONDARY_ORDER_ID(536, "AffectedSecondaryOrderID"),
	QUOTE_TYPE(537, "QuoteType"),
	NESTED_PARTY_ROLE(538, "NestedPartyRole"),
	NO_NESTED_PARTY_IDS(539, "NoNestedPartyIDs"),
	TOTAL_ACCRUED_INTEREST_AMT(540, "TotalAccruedInterestAmt (Deprecated)"),

	MATURITY_DATE(541, "MaturityDate"),
	UNDERLYING_MATURITY_DATE(542, "UnderlyingMaturityDate"),
	INSTR_REGISTRY(543, "InstrRegistry"),
	CASH_MARGIN(544, "CashMargin"),
	NESTED_PARTY_SUB_ID(545, "NestedPartySubID"),
	SCOPE(546, "Scope"),
	MD_IMPLICIT_DELETE(547, "MDImplicitDelete"),
	CROSS_ID(548, "CrossID"),
	CROSS_TYPE(549, "CrossType"),
	CROSS_PRIORITIZATION(550, "CrossPrioritization"),

	ORIG_CROSS_ID(551, "OrigCrossID"),
	NO_SIDES(552, "NoSides"),
	USERNAME(553, "Username"),
	PASSWORD(554, "Password"),
	NO_LEGS(555, "NoLegs"),
	LEG_CURRENCY(556, "LegCurrency"),
	TOT_NO_SECURITY_TYPES(557, "TotNoSecurityTypes"),
	NO_SECURITY_TYPES(558, "NoSecurityTypes"),
	SECURITY_LIST_REQUEST_TYPE(559, "SecurityListRequestType"),
	SECURITY_REQUEST_RESULT(560, "SecurityRequestResult"),

	ROUND_LOT(561, "RoundLot"),
	MIN_TRADE_VOL(562, "MinTradeVol"),
	MULTI_LEG_RPT_TYPE_REQ(563, "MultiLegRptTypeReq"),
	LEG_POSITION_EFFECT(564, "LegPositionEffect"),
	LEG_COVERED_OR_UNCOVERED(565, "LegCoveredOrUncovered"),
	LEG_PRICE(566, "LegPrice"),
	TRAD_SES_STATUS_REJ_REASON(567, "TradSesStatusRejReason"),
	TRADE_REQUEST_ID(568, "TradeRequestID"),
	TRADE_REQUEST_TYPE(569, "TradeRequestType"),
	PREVIOUSLY_REPORTED(570, "PreviouslyReported"),

	TRADE_REPORT_ID(571, "TradeReportID"),
	TRADE_REPORT_REF_ID(572, "TradeReportRefID"),
	MATCH_STATUS(573, "MatchStatus"),
	MATCH_TYPE(574, "MatchType"),
	ODD_LOT(575, "OddLot"),
	NO_CLEARING_INSTRUCTIONS(576, "NoClearingInstructions"),
	CLEARING_INSTRUCTION(577, "ClearingInstruction"),
	TRADE_INPUT_SOURCE(578, "TradeInputSource"),
	TRADE_INPUT_DEVICE(579, "TradeInputDevice"),
	NO_DATES(580, "NoDates"),

	ACCOUNT_TYPE(581, "AccountType"),
	CUST_ORDER_CAPACITY(582, "CustOrderCapacity"),
	CL_ORD_LINK_ID(583, "ClOrdLinkID"),
	MASS_STATUS_REQ_ID(584, "MassStatusReqID"),
	MASS_STATUS_REQ_TYPE(585, "MassStatusReqType"),
	ORIG_ORD_MOD_TIME(586, "OrigOrdModTime"),
	LEG_SETTL_TYPE(587, "LegSettlType formerly named LegSettlmntTyp prior to FIX 4.4)"),
	LEG_SETTL_DATE(588, "LegSettlDate (formerly named LegFutSettlDate prior to FIX 4.4)"),
	DAY_BOOKING_INST(589, "DayBookingInst"),
	BOOKING_UNIT(590, "BookingUnit"),

	PREALLOC_METHOD(591, "PreallocMethod"),
	UNDERLYING_COUNTRY_OF_ISSUE(592, "UnderlyingCountryOfIssue"),
	UNDERLYING_STATE_OR_PROVINCE_OF_ISSUE(593, "UnderlyingStateOrProvinceOfIssue"),
	UNDERLYING_LOCALE_OF_ISSUE(594, "UnderlyingLocaleOfIssue"),
	UNDERLYING_INSTR_REGISTRY(595, "UnderlyingInstrRegistry"),
	LEG_COUNTRY_OF_ISSUE(596, "LegCountryOfIssue"),
	LEG_STATE_OR_PROVINCE_OF_ISSUE(597, "LegStateOrProvinceOfIssue"),
	LEG_LOCALE_OF_ISSUE(598, "LegLocaleOfIssue"),
	LEG_INSTR_REGISTRY(599, "LegInstrRegistry"),
	LEG_SYMBOL(600, "LegSymbol"),

	
    // 601-700
    
	LEG_SYMBOL_SFX(601, "LegSymbolSfx"),
	LEG_SECURITY_ID(602, "LegSecurityID"),
	LEG_SECURITY_ID_SOURCE(603, "LegSecurityIDSource"),
	NO_LEG_SECURITY_ALT_ID(604, "NoLegSecurityAltID"),
	LEG_SECURITY_ALT_ID(605, "LegSecurityAltID"),
	LEG_SECURITY_ALT_ID_SOURCE(606, "LegSecurityAltIDSource"),
	LEG_PRODUCT(607, "LegProduct"),
	LEG_CFI_CODE(608, "LegCFICode"),
	LEG_SECURITY_TYPE(609, "LegSecurityType"),
	LEG_MATURITY_MONTH_YEAR(610, "LegMaturityMonthYear"),

	LEG_MATURITY_DATE(611, "LegMaturityDate"),
	LEG_STRIKE_PRICE(612, "LegStrikePrice"),
	LEG_OPT_ATTRIBUTE(613, "LegOptAttribute"),
	LEG_CONTRACT_MULTIPLIER(614, "LegContractMultiplier"),
	LEG_COUPON_RATE(615, "LegCouponRate"),
	LEG_SECURITY_EXCHANGE(616, "LegSecurityExchange"),
	LEG_ISSUER(617, "LegIssuer"),
	ENCODED_LEG_ISSUER_LEN(618, "EncodedLegIssuerLen"),
	ENCODED_LEG_ISSUER(619, "EncodedLegIssuer"),
	LEG_SECURITY_DESC(620, "LegSecurityDesc"),

	ENCODED_LEG_SECURITY_DESC_LEN(621, "EncodedLegSecurityDescLen"),
	ENCODED_LEG_SECURITY_DESC(622, "EncodedLegSecurityDesc"),
	LEG_RATIO_QTY(623, "LegRatioQty"),
	LEG_SIDE(624, "LegSide"),
	TRADING_SESSION_SUB_ID(625, "TradingSessionSubID"),
	ALLOC_TYPE(626, "AllocType"),
	NO_HOPS(627, "NoHops"),
	HOP_COMP_ID(628, "HopCompID"),
	HOP_SENDING_TIME(629, "HopSendingTime"),
	HOP_REF_ID(630, "HopRefID"),

	MID_PX(631, "MidPx"),
	BID_YIELD(632, "BidYield"),
	MID_YIELD(633, "MidYield"),
	OFFER_YIELD(634, "OfferYield"),
	CLEARING_FEE_INDICATOR(635, "ClearingFeeIndicator"),
	WORKING_INDICATOR(636, "WorkingIndicator"),
	LEG_LAST_PX(637, "LegLastPx"),
	PRIORITY_INDICATOR(638, "PriorityIndicator"),
	PRICE_IMPROVEMENT(639, "PriceImprovement"),
	PRICE_2(640, "Price2"),

	LAST_FORWARD_POINTS_2(641, "LastForwardPoints2"),
	BID_FORWARD_POINTS_2(642, "BidForwardPoints2"),
	OFFER_FORWARD_POINTS_2(643, "OfferForwardPoints2"),
	RFQ_REQ_ID(644, "RFQReqID"),
	MKT_BID_PX(645, "MktBidPx"),
	MKT_OFFER_PX(646, "MktOfferPx"),
	MIN_BID_SIZE(647, "MinBidSize"),
	MIN_OFFER_SIZE(648, "MinOfferSize"),
	QUOTE_STATUS_REQ_ID(649, "QuoteStatusReqID"),
	LEGAL_CONFIRM(650, "LegalConfirm"),

	UNDERLYING_LAST_PX(651, "UnderlyingLastPx"),
	UNDERLYING_LAST_QTY(652, "UnderlyingLastQty"),
    SEC_DEF_STATUS(653, "SecDefStatus (replaced)"),
	LEG_REF_ID(654, "LegRefID"),
	CONTRA_LEG_REF_ID(655, "ContraLegRefID"),
	SETTL_CURR_BID_FX_RATE(656, "SettlCurrBidFxRate"),
	SETTL_CURR_OFFER_FX_RATE(657, "SettlCurrOfferFxRate"),
	QUOTE_REQUEST_REJECT_REASON(658, "QuoteRequestRejectReason"),
	SIDE_COMPLIANCE_ID(659, "SideComplianceID"),
	ACCT_ID_SOURCE(660, "AcctIDSource"),

	ALLOC_ACCT_ID_SOURCE(661, "AllocAcctIDSource"),
	BENCHMARK_PRICE(662, "BenchmarkPrice"),
	BENCHMARK_PRICE_TYPE(663, "BenchmarkPriceType"),
	CONFIRM_ID(664, "ConfirmID"),
	CONFIRM_STATUS(665, "ConfirmStatus"),
	CONFIRM_TRANS_TYPE(666, "ConfirmTransType"),
	CONTRACT_SETTL_MONTH(667, "ContractSettlMonth"),
	DELIVERY_FORM(668, "DeliveryForm"),
	LAST_PAR_PX(669, "LastParPx"),
	NO_LEG_ALLOCS(670, "NoLegAllocs"),

	LEG_ALLOC_ACCOUNT(671, "LegAllocAccount"),
	LEG_INDIVIDUAL_ALLOC_ID(672, "LegIndividualAllocID"),
	LEG_ALLOC_QTY(673, "LegAllocQty"),
	LEG_ALLOC_ACCT_ID_SOURCE(674, "LegAllocAcctIDSource"),
	LEG_SETTL_CURRENCY(675, "LegSettlCurrency"),
	LEG_BENCHMARK_CURVE_CURRENCY(676, "LegBenchmarkCurveCurrency"),
	LEG_BENCHMARK_CURVE_NAME(677, "LegBenchmarkCurveName"),
	LEG_BENCHMARK_CURVE_POINT(678, "LegBenchmarkCurvePoint"),
	LEG_BENCHMARK_PRICE(679, "LegBenchmarkPrice"),
	LEG_BENCHMARK_PRICE_TYPE(680, "LegBenchmarkPriceType"),

	LEG_BID_PX(681, "LegBidPx"),
	LEG_IOI_QTY(682, "LegIOIQty"),
	NO_LEG_STIPULATIONS(683, "NoLegStipulations"),
	LEG_OFFER_PX(684, "LegOfferPx"),
	LEG_ORDER_QTY(685, "LegOrderQty"),
	LEG_PRICE_TYPE(686, "LegPriceType"),
	LEG_QTY(687, "LegQty"),
	LEG_STIPULATION_TYPE(688, "LegStipulationType"),
	LEG_STIPULATION_VALUE(689, "LegStipulationValue"),
	LEG_SWAP_TYPE(690, "LegSwapType"),

	POOL(691, "Pool"),
	QUOTE_PRICE_TYPE(692, "QuotePriceType"),
	QUOTE_RESP_ID(693, "QuoteRespID"),
	QUOTE_RESP_TYPE(694, "QuoteRespType"),
	QUOTE_QUALIFIER(695, "QuoteQualifier"),
	YIELD_REDEMPTION_DATE(696, "YieldRedemptionDate"),
	YIELD_REDEMPTION_PRICE(697, "YieldRedemptionPrice"),
	YIELD_REDEMPTION_PRICE_TYPE(698, "YieldRedemptionPriceType"),
	BENCHMARK_SECURITY_ID(699, "BenchmarkSecurityID"),
	REVERSAL_INDICATOR(700, "ReversalIndicator"),

	
    // 701-800

	YIELD_CALC_DATE(701, "YieldCalcDate"),
	NO_POSITIONS(702, "NOPOSITIONS"),
	POS_TYPE(703, "PosType"),
	LONG_QTY(704, "LONGQTY"),
	SHORT_QTY(705, "ShortQty"),
	POS_QTY_STATUS(706, "PosQtyStatus"),
	POS_AMT_TYPE(707, "PosAmtType"),
	POS_AMT(708, "PosAmt"),
	POS_TRANS_TYPE(709, "PosTransType"),
	POS_REQ_ID(710, "PosReqID"),

	NO_UNDERLYINGS(711, "NoUnderlyings"),
	POS_MAINT_ACTION(712, "PosMaintAction"),
	ORIG_POS_REQ_REF_ID(713, "OrigPosReqRefID"),
	POS_MAINT_RPT_REF_ID(714, "PosMaintRptRefID"),
	CLEARING_BUSINESS_DATE(715, "ClearingBusinessDate"),
	SETTL_SESS_ID(716, "SettlSessID"),
	SETTL_SESS_SUB_ID(717, "SettlSessSubID"),
	ADJUSTMENT_TYPE(718, "AdjustmentType"),
	CONTRARY_INSTRUCTION_INDICATOR(719, "ContraryInstructionIndicator"),
	PRIOR_SPREAD_INDICATOR(720, "PriorSpreadIndicator"),

	POS_MAINT_RPT_ID(721, "PosMaintRptID"),
	POS_MAINT_STATUS(722, "PosMaintStatus"),
	POS_MAINT_RESULT(723, "PosMaintResult"),
	POS_REQ_TYPE(724, "PosReqType"),
	RESPONSE_TRANSPORT_TYPE(725, "ResponseTransportType"),
	RESPONSE_DESTINATION(726, "ResponseDestination"),
	TOTAL_NUM_POS_REPORTS(727, "TotalNumPosReports"),
	POS_REQ_RESULT(728, "PosReqResult"),
	POS_REQ_STATUS(729, "PosReqStatus"),
	SETTL_PRICE(730, "SettlPrice"),

	SETTL_PRICE_TYPE(731, "SettlPriceType"),
	UNDERLYING_SETTL_PRICE(732, "UnderlyingSettlPrice"),
	UNDERLYING_SETTL_PRICE_TYPE(733, "UnderlyingSettlPriceType"),
	PRIOR_SETTL_PRICE(734, "PriorSettlPrice"),
	NO_QUOTE_QUALIFIERS(735, "NoQuoteQualifiers"),
	ALLOC_SETTL_CURRENCY(736, "AllocSettlCurrency"),
	ALLOC_SETTL_CURR_AMT(737, "AllocSettlCurrAmt"),
	INTEREST_AT_MATURITY(738, "InterestAtMaturity"),
	LEG_DATED_DATE(739, "LegDatedDate"),
	LEG_POOL(740, "LegPool"),

	ALLOC_INTEREST_AT_MATURITY(741, "AllocInterestAtMaturity"),
	ALLOC_ACCRUED_INTEREST_AMT(742, "AllocAccruedInterestAmt"),
	DELIVERY_DATE(743, "DeliveryDate"),
	ASSIGNMENT_METHOD(744, "AssignmentMethod"),
	ASSIGNMENT_UNIT(745, "ASSIGNMENTUNIT"),
	OPEN_INTEREST(746, "OpenInterest"),
	EXERCISE_METHOD(747, "ExerciseMethod"),
	TOT_NUM_TRADE_REPORTS(748, "TotNumTradeReports"),
	TRADE_REQUEST_RESULT(749, "TradeRequestResult"),
	TRADE_REQUEST_STATUS(750, "TradeRequestStatus"),

	TRADE_REPORT_REJECT_REASON(751, "TradeReportRejectReason"),
	SIDE_MULTI_LEG_REPORTING_TYPE(752, "SideMultiLegReportingType"),
	NO_POS_AMT(753, "NoPosAmt"),
	AUTO_ACCEPT_INDICATOR(754, "AutoAcceptIndicator"),
	ALLOC_REPORT_ID(755, "AllocReportID"),
	NO_NESTED_2_PARTY_IDS(756, "NoNested2PartyIDs"),
	NESTED_2_PARTY_ID(757, "Nested2PartyID"),
	NESTED_2_PARTY_ID_SOURCE(758, "Nested2PartyIDSource"),
	NESTED_2_PARTY_ROLE(759, "Nested2PartyRole"),
	NESTED_2_PARTY_SUB_ID(760, "Nested2PartySubID"),

	BENCHMARK_SECURITY_ID_SOURCE(761, "BenchmarkSecurityIDSource"),
	SECURITY_SUB_TYPE(762, "SecuritySubType"),
	UNDERLYING_SECURITY_SUB_TYPE(763, "UnderlyingSecuritySubType"),
	LEG_SECURITY_SUB_TYPE(764, "LegSecuritySubType"),
	ALLOWABLE_ONE_SIDEDNESS_PCT(765, "AllowableOneSidednessPct"),
	ALLOWABLE_ONE_SIDEDNESS_VALUE(766, "AllowableOneSidednessValue"),
	ALLOWABLE_ONE_SIDEDNESS_CURR(767, "AllowableOneSidednessCurr"),
	NO_TRD_REG_TIMESTAMPS(768, "NoTrdRegTimestamps"),
	TRD_REG_TIMESTAMP(769, "TrdRegTimestamp"),
	TRD_REG_TIMESTAMP_TYPE(770, "TrdRegTimestampType"),

	TRD_REG_TIMESTAMP_ORIGIN(771, "TrdRegTimestampOrigin"),
	CONFIRM_REF_ID(772, "ConfirmRefID"),
	CONFIRM_TYPE(773, "ConfirmType"),
	CONFIRM_REJ_REASON(774, "ConfirmRejReason"),
	BOOKING_TYPE(775, "BookingType"),
	INDIVIDUAL_ALLOC_REJ_CODE(776, "IndividualAllocRejCode"),
	SETTL_INST_MSG_ID(777, "SettlInstMsgID"),
	NO_SETTL_INST(778, "NoSettlInst"),
	LAST_UPDATE_TIME(779, "LastUpdateTime"),
	ALLOC_SETTL_INST_TYPE(780, "AllocSettlInstType"),

	NO_SETTL_PARTY_IDS(781, "NoSettlPartyIDs"),
	SETTL_PARTY_ID(782, "SettlPartyID"),
	SETTL_PARTY_ID_SOURCE(783, "SettlPartyIDSource"),
	SETTL_PARTY_ROLE(784, "SettlPartyRole"),
	SETTL_PARTY_SUB_ID(785, "SettlPartySubID"),
	SETTL_PARTY_SUB_ID_TYPE(786, "SettlPartySubIDType"),
	DLVY_INST_TYPE(787, "DlvyInstType"),
	TERMINATION_TYPE(788, "TerminationType"),
	NEXT_EXPECTED_MSG_SEQ_NUM(789, "NextExpectedMsgSeqNum"),
	ORD_STATUS_REQ_ID(790, "OrdStatusReqID"),

	SETTL_INST_REQ_ID(791, "SettlInstReqID"),
	SETTL_INST_REQ_REJ_CODE(792, "SettlInstReqRejCode"),
	SECONDARY_ALLOC_ID(793, "SecondaryAllocID"),
	ALLOC_REPORT_TYPE(794, "AllocReportType"),
	ALLOC_REPORT_REF_ID(795, "AllocReportRefID"),
	ALLOC_CANC_REPLACE_REASON(796, "AllocCancReplaceReason"),
	COPY_MSG_INDICATOR(797, "CopyMsgIndicator"),
	ALLOC_ACCOUNT_TYPE(798, "AllocAccountType"),
	ORDER_AVG_PX(799, "OrderAvgPx"),
	ORDER_BOOKING_QTY(800, "OrderBookingQty"),


    // 801-900

	NO_SETTL_PARTY_SUB_IDS(801, "NoSettlPartySubIDs"),
	NO_PARTY_SUB_IDS(802, "NoPartySubIDs"),
	PARTY_SUB_ID_TYPE(803, "PartySubIDType"),
	NO_NESTED_PARTY_SUB_IDS(804, "NoNestedPartySubIDs"),
	NESTED_PARTY_SUB_ID_TYPE(805, "NestedPartySubIDType"),
	NO_NESTED_2_PARTY_SUB_IDS(806, "NoNested2PartySubIDs"),
	NESTED_2_PARTY_SUB_ID_TYPE(807, "Nested2PartySubIDType"),
	ALLOC_INTERMED_REQ_TYPE(808, "AllocIntermedReqType"),
	NOT_DEFINED_809(809, "(Not Defined)"),
	UNDERLYING_PX(810, "UnderlyingPx"),

	PRICE_DELTA(811, "PriceDelta"),
	APPL_QUEUE_MAX(812, "ApplQueueMax"),
	APPL_QUEUE_DEPTH(813, "ApplQueueDepth"),
	APPL_QUEUE_RESOLUTION(814, "ApplQueueResolution"),
	APPL_QUEUE_ACTION(815, "ApplQueueAction"),
	NO_ALT_MD_SOURCE(816, "NoAltMDSource"),
	ALT_MD_SOURCE_ID(817, "AltMDSourceID"),
	SECONDARY_TRADE_REPORT_ID(818, "SecondaryTradeReportID"),
	AVG_PX_INDICATOR(819, "AvgPxIndicator"),
	TRADE_LINK_ID(820, "TradeLinkID"),

	ORDER_INPUT_DEVICE(821, "OrderInputDevice"),
	UNDERLYING_TRADING_SESSION_ID(822, "UnderlyingTradingSessionID"),
	UNDERLYING_TRADING_SESSION_SUB_ID(823, "UnderlyingTradingSessionSubID"),
	TRADE_LEG_REF_ID(824, "TradeLegRefID"),
	EXCHANGE_RULE(825, "ExchangeRule"),
	TRADE_ALLOC_INDICATOR(826, "TradeAllocIndicator"),
	EXPIRATION_CYCLE(827, "ExpirationCycle"),
	TRD_TYPE(828, "TrdType"),
	TRD_SUB_TYPE(829, "TrdSubType"),
	TRANSFER_REASON(830, "TransferReason"),

	ASGN_REQ_ID(831, "AsgnReqID"),
	TOT_NUM_ASSIGNMENT_REPORTS(832, "TotNumAssignmentReports"),
	ASGN_RPT_ID(833, "AsgnRptID"),
	THRESHOLD_AMOUNT(834, "ThresholdAmount"),
	PEG_MOVE_TYPE(835, "PegMoveType"),
	PEG_OFFSET_TYPE(836, "PegOffsetType"),
	PEG_LIMIT_TYPE(837, "PegLimitType"),
	PEG_ROUND_DIRECTION(838, "PegRoundDirection"),
	PEGGED_PRICE(839, "PeggedPrice"),
	PEG_SCOPE(840, "PegScope"),

	DISCRETION_MOVE_TYPE(841, "DiscretionMoveType"),
	DISCRETION_OFFSET_TYPE(842, "DiscretionOffsetType"),
	DISCRETION_LIMIT_TYPE(843, "DiscretionLimitType"),
	DISCRETION_ROUND_DIRECTION(844, "DiscretionRoundDirection"),
	DISCRETION_PRICE(845, "DiscretionPrice"),
	DISCRETION_SCOPE(846, "DiscretionScope"),
	TARGET_STRATEGY(847, "TargetStrategy"),
	TARGET_STRATEGY_PARAMETERS(848, "TargetStrategyParameters"),
	PARTICIPATION_RATE(849, "ParticipationRate"),
	TARGET_STRATEGY_PERFORMANCE(850, "TargetStrategyPerformance"),

	LAST_LIQUIDITY_IND(851, "LastLiquidityInd"),
	PUBLISH_TRD_INDICATOR(852, "PublishTrdIndicator"),
	SHORT_SALE_REASON(853, "ShortSaleReason"),
	QTY_TYPE(854, "QtyType"),
	SECONDARY_TRD_TYPE(855, "SecondaryTrdType"),
	TRADE_REPORT_TYPE(856, "TradeReportType"),
	ALLOC_NO_ORDERS_TYPE(857, "AllocNoOrdersType"),
	SHARED_COMMISSION(858, "SharedCommission"),
	CONFIRM_REQ_ID(859, "ConfirmReqID"),
	AVG_PAR_PX(860, "AvgParPx"),

	REPORTED_PX(861, "ReportedPx"),
	NO_CAPACITIES(862, "NoCapacities"),
	ORDER_CAPACITY_QTY(863, "OrderCapacityQty"),
	NO_EVENTS(864, "NoEvents"),
	EVENT_TYPE(865, "EventType"),
	EVENT_DATE(866, "EventDate"),
	EVENT_PX(867, "EventPx"),
	EVENT_TEXT(868, "EventText"),
	PCT_AT_RISK(869, "PctAtRisk"),
	NO_INSTR_ATTRIB(870, "NoInstrAttrib"),

	INSTR_ATTRIB_TYPE(871, "InstrAttribType"),
	INSTR_ATTRIB_VALUE(872, "InstrAttribValue"),
	DATED_DATE(873, "DatedDate"),
	INTEREST_ACCRUAL_DATE(874, "InterestAccrualDate"),
	CP_PROGRAM(875, "CPProgram"),
	CP_REG_TYPE(876, "CPRegType"),
	UNDERLYING_CP_PROGRAM(877, "UnderlyingCPProgram"),
	UNDERLYING_CP_REGTYPE(878, "UnderlyingCPRegType"),
	UNDERLYING_QTY(879, "UnderlyingQty"),
	TRD_MATCH_ID(880, "TrdMatchID"),

	SECONDARY_TRADE_REPORT_REF_ID(881, "SecondaryTradeReportRefID"),
	UNDERLYING_DIRTY_PRICE(882, "UnderlyingDirtyPrice"),
	UNDERLYING_END_PRICE(883, "UnderlyingEndPrice"),
	UNDERLYING_START_VALUE(884, "UnderlyingStartValue"),
	UNDERLYING_CURRENT_VALUE(885, "UnderlyingCurrentValue"),
	UNDERLYING_END_VALUE(886, "UnderlyingEndValue"),
	NO_UNDERLYING_STIPS(887, "NoUnderlyingStips"),
	UNDERLYING_STIP_TYPE(888, "UnderlyingStipType"),
	UNDERLYING_STIP_VALUE(889, "UnderlyingStipValue"),
	MATURITY_NET_MONEY(890, "MaturityNetMoney"),

	MISC_FEE_BASIS(891, "MiscFeeBasis"),
	TOT_NO_ALLOCS(892, "TotNoAllocs"),
	LAST_FRAGMENT(893, "LastFragment"),
	COLL_REQ_ID(894, "CollReqID"),
	COLL_ASGN_REASON(895, "CollAsgnReason"),
	COLL_INQUIRY_QUALIFIER(896, "CollInquiryQualifier"),
	NO_TRADES(897, "NoTrades"),
	MARGIN_RATIO(898, "MarginRatio"),
	MARGIN_EXCESS(899, "MarginExcess"),
	TOTAL_NET_VALUE(900, "TotalNetValue"),


    // 901-1000

	CASH_OUTSTANDING(901, "CashOutstanding"),
	COLL_ASGN_ID(902, "CollAsgnID"),
	COLL_ASGN_TRANS_TYPE(903, "CollAsgnTransType"),
	COLL_RESP_ID(904, "CollRespID"),
	COLL_ASGN_RESP_TYPE(905, "CollAsgnRespType"),
	COLL_ASGN_REJECT_REASON(906, "CollAsgnRejectReason"),
	COLL_ASGN_REF_ID(907, "CollAsgnRefID"),
	COLL_RPT_ID(908, "CollRptID"),
	COLL_INQUIRY_ID(909, "CollInquiryID"),
	COLL_STATUS(910, "CollStatus"),

	TOT_NUM_REPORTS(911, "TotNumReports"),
	LAST_RPT_REQUESTED(912, "LastRptRequested"),
	AGREEMENT_DESC(913, "AgreementDesc"),
	AGREEMENT_ID(914, "AgreementID"),
	AGREEMENT_DATE(915, "AgreementDate"),
	START_DATE(916, "StartDate"),
	END_DATE(917, "EndDate"),
	AGREEMENT_CURRENCY(918, "AgreementCurrency"),
	DELIVERY_TYPE(919, "DeliveryType"),
	END_ACCRUED_INTEREST_AMT(920, "EndAccruedInterestAmt"),

	START_CASH(921, "StartCash"),
	END_CASH(922, "EndCash"),
	USER_REQUEST_ID(923, "UserRequestID"),
	USER_REQUEST_TYPE(924, "UserRequestType"),
	NEW_PASSWORD(925, "NewPassword"),
	USER_STATUS(926, "UserStatus"),
	USER_STATUS_TEXT(927, "UserStatusText"),
	STATUS_VALUE(928, "StatusValue"),
	STATUS_TEXT(929, "StatusText"),
	REF_COMP_ID(930, "RefCompID"),

	REF_SUB_ID(931, "RefSubID"),
	NETWORK_RESPONSE_ID(932, "NetworkResponseID"),
	NETWORK_REQUEST_ID(933, "NetworkRequestID"),
	LAST_NETWORK_RESPONSE_ID(934, "LastNetworkResponseID"),
	NETWORK_REQUEST_TYPE(935, "NetworkRequestType"),
	NO_COMP_IDS(936, "NoCompIDs"),
	NETWORK_STATUS_RESPONSE_TYPE(937, "NetworkStatusResponseType"),
	NO_COLL_INQUIRY_QUALIFIER(938, "NoCollInquiryQualifier"),
	TRD_RPT_STATUS(939, "TrdRptStatus"),
	AFFIRM_STATUS(940, "AffirmStatus"),

	UNDERLYING_STRIKE_CURRENCY(941, "UnderlyingStrikeCurrency"),
	LEG_STRIKE_CURRENCY(942, "LegStrikeCurrency"),
	TIME_BRACKET(943, "TimeBracket"),
	COLL_ACTION(944, "CollAction"),
	COLL_INQUIRY_STATUS(945, "CollInquiryStatus"),
	COLL_INQUIRY_RESULT(946, "CollInquiryResult"),
	STRIKE_CURRENCY(947, "StrikeCurrency"),
	NO_NESTED_3_PARTY_IDS(948, "NoNested3PartyIDs"),
	NESTED_3_PARTY_ID(949, "Nested3PartyID"),
	NESTED_3_PARTY_ID_SOURCE(950, "Nested3PartyIDSource"),

	NESTED_3_PARTY_ROLE(951, "Nested3PartyRole"),
	NO_NESTED_3_PARTY_SUB_IDS(952, "NoNested3PartySubIDs"),
	NESTED_3_PARTY_SUB_ID(953, "Nested3PartySubID"),
	NESTED_3_PARTY_SUB_ID_TYPE(954, "Nested3PartySubIDType"),
	LEG_CONTRACT_SETTL_MONTH(955, "LegContractSettlMonth"),
	LEG_INTEREST_ACCRUAL_DATE(956, "LegInterestAccrualDate");


    // 1001-1100



    ///////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////

    private final int fixTagNumber;
    private final String fixTagDescription;

    FIXTag(final int fixTagNumber, final String fixTagDescription) {
        this.fixTagNumber = fixTagNumber;
        this.fixTagDescription = fixTagDescription;
    }
    public int getFIXTagNumber() {
        return fixTagNumber;
    }
    public String getFIXTagDescription() {
        return fixTagDescription;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(this.name())
            .append(":[")
            .append(getFIXTagNumber())
            .append("]")
            .append(":[")
            .append(getFIXTagDescription())
            .append("]");

        return sb.toString();
    }

}
