/*
 * Copyright (c) 2022.  HW Tech Services, LLC
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

package com.hwtsllc.fixengine2022.datatypes;

import com.hwtsllc.fixengine2022.interfaces.EnumAccessors;
import com.hwtsllc.fixengine2022.interfaces.LogStringVerbose;

/**
 * FIXType enum defines all the Financial Exchange Protocol's (FIX) fields.  
 * It consists of 3 fields.
 *
 *         ENUMName     Enum Name has the FIXn prefix *n* is the tag number defined by FIX Prootocol document.
 *                      There may be a secondary prefix denoting the data type.
 *                      ET = EnumType field
 *                      ST = StringType field
 *                      NIGT = NumInGroupType field, saved as int
 *                      LT = LengthType field, saved as int
 *                      QT = QtyType field, saved as int
 *                      SNT = SeqNumType field, saved as int
 *                      others to follow
 * String  id           this is the identifier of the field as defined by the FIX protocol document, no duplicates.
 *                      Even though *id* is really an *int*, this app treats it as a String. so save it as a String
 * String  name         short NAME of the field as defined by the FIX protocol document, no duplicates
 * String  description  a short blurb which describes what information the field contains
 */
public enum FIXType implements EnumAccessors, LogStringVerbose {

    // 1-100

    /*
     * Start of FIX2.7 as defined by the FIX Protocol Specification 2.7
     *  Tags: 1-103
     */
    FIX1_ST_ACCOUNT(1, "ACCOUNT", "Account"),
    FIX2_ST_ADV_ID(2, "ADV_ID", "AdvId"),
    FIX3_ST_ADV_REF_ID(3, "ADV_REF_ID", "AdvRefId"),
    FIX4_ET_ADV_SIDE(4, "ADV_SIDE", "AdvSide"),
    FIX5_ET_ADV_TRANS_TYPE(5, "ADV_TRANS_TYPE", "Enum5AdvTransType"),
    FIX6_AVG_PX(6, "AVG_PX", "AvgPx"),
    FIX7_BEGIN_SEQ_NO(7, "BEGIN_SEQ_NO", "BeginSeqNo"),
    FIX8_ET_BEGIN_STRING(8, "BEGIN_STRING", "BeginString"),
    FIX9_BODY_LENGTH(9, "BODY_LENGTH", "BodyLength"),
    FIX10_CHECK_SUM(10, "CHECK_SUM", "CheckSum"),

    FIX11_ST_CL_ORD_ID(11, "CL_ORD_ID", "ClOrdID"),
    FIX12_COMMISSION(12, "COMMISSION", "Commission"),
    FIX13_ET_COMM_TYPE(13, "COMM_TYPE", "CommType"),
    FIX14_CUM_QTY(14, "CUM_QTY", "CumQty"),
    FIX15_CURRENCY(15, "CURRENCY", "Currency"),
    FIX16_END_SEQ_NO(16, "END_SEQ_NO", "EndSeqNo"),
    FIX17_ST_EXEC_ID(17, "EXEC_ID", "ExecID"),
    FIX18_ET_EXEC_INST(18, "EXEC_INST", "ExecInst"),
    FIX19_ST_EXEC_REF_ID(19, "EXEC_REF_ID", "ExecRefID"),
    FIX20_ET_EXEC_TRANS_TYPE(20, "EXEC_TRANS_TYPE", "ExecTransType (replaced)"),

    FIX21_ET_HANDL_INST(21, "HANDL_INST", "HandlInst"),
    FIX22_ET_SECURITY_ID_SOURCE(22, "SECURITY_ID_SOURCE", "SecurityIDSource"),
    FIX23_ST_IOI_ID(23, "IOI_ID", "IOIid"),
    FIX24_IOI_OTH_SVC(24, "IOI_OTH_SVC", "IOIOthSvc (no longer used)"),
    FIX25_ET_IOI_QLTY_IND(25, "IOI_QLTY_IND", "IOIQltyInd"),
    FIX26_ST_IOI_REF_ID(26, "IOI_REF_ID", "IOIRefID"),
    FIX27_IOI_SHARES(27, "IOI_SHARES", "IOIShares"),
    FIX28_ET_IOI_TRANS_TYPE(28, "IOI_TRANS_TYPE", "IOITransType"),
    FIX29_ET_LAST_CAPACITY(29, "LAST_CAPACITY", "LastCapacity"),
    FIX30_LAST_MKT(30, "LAST_MKT", "LastMkt"),

    FIX31_LAST_PX(31, "LAST_PX", "LastPx"),
    FIX32_LAST_QTY(32, "LAST_QTY", "LastQty"),
    FIX33_NO_LINES_OF_TEXT(33, "NO_LINES_OF_TEXT", "NoLinesOfText"),
    FIX34_MSG_SEQ_NUM(34, "MSG_SEQ_NUM", "MsgSeqNum"),
    FIX35_ET_MSG_TYPE(35, "MSG_TYPE", "MsgType"),
    FIX36_NEW_SEQ_NO(36, "NEW_SEQ_NO", "NewSeqNo"),
    FIX37_ST_ORDER_ID(37, "ORDER_ID", "OrderID"),
    FIX38_ORDER_QTY(38, "ORDER_QTY", "OrderQty"),
    FIX39_ET_ORD_STATUS(39, "ORD_STATUS", "OrdStatus"),
    FIX40_ET_ORD_TYPE(40, "ORD_TYPE", "OrdType"),

    FIX41_ST_ORIG_CL_ORD_ID(41, "ORIG_CL_ORD_ID", "OrigClOrdID"),
    FIX42_ORIG_TIME(42, "ORIG_TIME", "OrigTime"),
    FIX43_ET_POSS_DUP_FLAG(43, "POSS_DUP_FLAG", "PossDupFlag"),
    FIX44_PRICE(44, "PRICE", "Price"),
    FIX45_REF_SEQ_NUM(45, "REF_SEQ_NUM", "RefSeqNum"),
    FIX46_ST_RELATD_SYM(46, "RELATD_SYM", "RelatdSym (No longer used)"),
    FIX47_ET_RULE_80_A(47, "RULE_80_A", "Rule80A (no longer used)"),
    FIX48_ST_SECURITY_ID(48, "SECURITY_ID", "SecurityID"),
    FIX49_ST_SENDER_COMP_ID(49, "SENDER_COMP_ID", "SenderCompID"),
    FIX50_ST_SENDER_SUB_ID(50, "SENDER_SUB_ID", "SenderSubID"),

    FIX51_SENDING_DATE(51, "SENDING_DATE", "SendingDate (no longer used)"),
    FIX52_SENDING_TIME(52, "SENDING_TIME", "SendingTime"),
    FIX53_QUANTITY(53, "QUANTITY", "Quantity (formerly Shares)"),
    FIX54_ET_SIDE(54, "SIDE", "Side"),
    FIX55_ST_SYMBOL(55, "SYMBOL", "Symbol"),
    FIX56_ST_TARGET_COMP_ID(56, "TARGET_COMP_ID", "TargetCompID"),
    FIX57_ST_TARGET_SUB_ID(57, "TARGET_SUB_ID", "TargetSubID"),
    FIX58_ST_TEXT(58, "TEXT", "Text"),
    FIX59_ET_TIME_IN_FORCE(59, "TIME_IN_FORCE", "TimeInForce"),
    FIX60_TRANSACT_TIME(60, "TRANSACT_TIME", "TransactTime"),

    FIX61_ET_URGENCY(61, "URGENCY", "Urgency"),
    FIX62_VALID_UNTIL_TIME(62, "VALID_UNTIL_TIME", "ValidUntilTime"),
    FIX63_SETTLMNT_TYP(63, "SETTLMNT_TYP", "SettlmntTyp"),
    FIX64_SETTL_DATE(64, "SETTL_DATE", "SettlDate"),
    FIX65_ST_SYMBOL_SFX(65, "SYMBOL_SFX", "SymbolSfx"),
    FIX66_ST_LIST_ID(66, "LIST_ID", "ListID"),
    FIX67_LIST_SEQ_NO(67, "LIST_SEQ_NO", "ListSeqNo"),
    FIX68_TOT_NO_ORDERS(68, "TOT_NO_ORDERS", "TotNoOrders (formerly named: ListNoOrds)"),
    FIX69_LIST_EXEC_INST(69, "LIST_EXEC_INST", "ListExecInst"),
    FIX70_ST_ALLOC_ID(70, "ALLOC_ID", "AllocID"),

    FIX71_ET_ALLOC_TRANS_TYPE(71, "ALLOC_TRANS_TYPE", "AllocTransType"),
    FIX72_ST_REF_ALLOC_ID(72, "REF_ALLOC_ID", "RefAllocID"),
    FIX73_NO_ORDERS(73, "NO_ORDERS", "NoOrders"),
    FIX74_AVG_PX_PRECISION(74, "AVG_PX_PRECISION", "AvgPxPrecision"),
    FIX75_TRADE_DATE(75, "TRADE_DATE", "TradeDate"),
    FIX76_EXEC_BROKER(76, "EXEC_BROKER", "ExecBroker (replaced)"),
    FIX77_ET_POSITION_EFFECT(77, "POSITION_EFFECT", "PositionEffect"),
    FIX78_NO_ALLOCS(78, "NO_ALLOCS", "NoAllocs"),
    FIX79_ST_ALLOC_ACCOUNT(79, "ALLOC_ACCOUNT", "AllocAccount"),
    FIX80_ALLOC_SHARES(80, "ALLOC_SHARES", "AllocShares"),

    FIX81_ET_PROCESS_CODE(81, "PROCESS_CODE", "ProcessCode"),
    FIX82_NO_RPTS(82, "NO_RPTS", "NoRpts"),
    FIX83_RPT_SEQ(83, "RPT_SEQ", "RptSeq"),
    FIX84_CXL_QTY(84, "CXL_QTY", "CxlQty"),
    FIX85_NO_DLVY_INST(85, "NO_DLVY_INST", "NoDlvyInst (no longer used)"),
    FIX86_DLVY_INST(86, "DLVY_INST", "DlvyInst (no longer used)"),
    FIX87_ET_ALLOC_STATUS(87, "ALLOC_STATUS", "AllocStatus"),
    FIX88_ET_ALLOC_REJ_CODE(88, "ALLOC_REJ_CODE", "AllocRejCode"),
    FIX89_SIGNATURE(89, "SIGNATURE", "Signature"),
    FIX90_SECURE_DATA_LEN(90, "SECURE_DATA_LEN", "SecureDataLen"),

    FIX91_SECURE_DATA(91, "SECURE_DATA", "SecureData"),
    FIX92_BROKER_OF_CREDIT(92, "BROKER_OF_CREDIT", "BrokerOfCredit (replaced)"),
    FIX93_SIGNATURE_LENGTH(93, "SIGNATURE_LENGTH", "SignatureLength"),
    FIX94_ET_EMAIL_TYPE(94, "EMAIL_TYPE", "EmailType"),
    FIX95_RAW_DATA_LENGTH(95, "RAW_DATA_LENGTH", "RawDataLength"),
    FIX96_RAW_DATA(96, "RAW_DATA", "RawData"),
    FIX97_ET_POSS_RESEND(97, "POSS_RESEND", "PossResend"),
    FIX98_ET_ENCRYPT_METHOD(98, "ENCRYPT_METHOD", "EncryptMethod"),
    FIX99_STOP_PX(99, "STOP_PX", "StopPx"),
    FIX100_EX_DESTINATION(100, "EX_DESTINATION", "ExDestination"),


    // 101-200

    FIX102_ET_CXL_REJ_REASON(102, "CXL_REJ_REASON", "CxlRejReason"),
    FIX103_ET_ORD_REJ_REASON(103, "ORD_REJ_REASON", "OrdRejReason"),
    /*
     *
     * End of FIX2.7
     *
     */


    /*
     * Start of FIX3.0 as defined by the FIX Protocol Specification 3.0
     *  Tags: 104-113
     */
    FIX104_ET_IOI_QUALIFIER(104, "IOI_QUALIFIER", "IOIQualifier"),
    FIX105_WAVE_NO(105, "WAVE_NO", "WaveNo"),
    FIX106_ISSUER(106, "ISSUER", "Issuer"),
    FIX107_SECURITY_DESC(107, "SECURITY_DESC", "SecurityDesc"),
    FIX108_HEART_BT_INT(108, "HEART_BT_INT", "HeartBtInt"),
    FIX109_CLIENT_ID(109, "CLIENT_ID", "ClientID (replaced)"),
    FIX110_MIN_QTY(110, "MIN_QTY", "MinQty"),

    FIX111_MAX_FLOOR(111, "MAX_FLOOR", "MaxFloor"),
    FIX112_TEST_REQ_ID(112, "TEST_REQ_ID", "TestReqID"),
    FIX113_ET_REPORT_TO_EXCH(113, "REPORT_TO_EXCH", "ReportToExch"),
    /*
     *
     * End of FIX3.0
     *
     */


    /*
     * Start of FIX4.0 as defined by the FIX Protocol Specification 4.0
     *  Tags: 114-140
     */
    FIX114_ET_LOCATE_REQD(114, "LOCATE_REQD", "LocateReqd"),
    FIX115_ON_BEHALF_OF_COMP_ID(115, "ON_BEHALF_OF_COMP_ID", "OnBehalfOfCompID"),
    FIX116_ON_BEHALF_OF_SUB_ID(116, "ON_BEHALF_OF_SUB_ID", "OnBehalfOfSubID"),
    FIX117_QUOTE_ID(117, "QUOTE_ID", "QuoteID"),
    FIX118_NET_MONEY(118, "NET_MONEY", "NetMoney"),
    FIX119_SETTL_CURR_AMT(119, "SETTL_CURR_AMT", "SettlCurrAmt"),
    FIX120_SETTL_CURRENCY(120, "SETTL_CURRENCY", "SettlCurrency"),

    FIX121_ET_FOREX_REQ(121, "FOREX_REQ", "ForexReq"),
    FIX122_ORIG_SENDING_TIME(122, "ORIG_SENDING_TIME", "OrigSendingTime"),
    FIX123_ET_GAP_FILL_FLAG(123, "GAP_FILL_FLAG", "GapFillFlag"),
    FIX124_NO_EXECS(124, "NO_EXECS", "NoExecs"),
    FIX125_CXL_TYPE(125, "CXL_TYPE", "CxlType (no longer used)"),
    FIX126_EXPIRE_TIME(126, "EXPIRE_TIME", "ExpireTime"),
    FIX127_ET_DK_REASON(127, "DK_REASON", "DKReason"),
    FIX128_DELIVER_TO_COMP_ID(128, "DELIVER_TO_COMP_ID", "DeliverToCompID"),
    FIX129_DELIVER_TO_SUB_ID(129, "DELIVER_TO_SUB_ID", "DeliverToSubID"),
    FIX130_ET_IOI_NATURAL_FLAG(130, "IOI_NATURAL_FLAG", "IOINaturalFlag"),

    FIX131_QUOTE_REQ_ID(131, "QUOTE_REQ_ID", "QuoteReqID"),
    FIX132_BID_PX(132, "BID_PX", "BidPx"),
    FIX133_OFFER_PX(133, "OFFER_PX", "OfferPx"),
    FIX134_BID_SIZE(134, "BID_SIZE", "BidSize"),
    FIX135_OFFER_SIZE(135, "OFFER_SIZE", "OfferSize"),
    FIX136_NO_MISC_FEES(136, "NO_MISC_FEES", "NoMiscFees"),
    FIX137_MISC_FEE_AMT(137, "MISC_FEE_AMT", "MiscFeeAmt"),
    FIX138_MISC_FEE_CURR(138, "MISC_FEE_CURR", "MiscFeeCurr"),
    FIX139_ET_MISC_FEE_TYPE(139, "MISC_FEE_TYPE", "MiscFeeType"),
    FIX140_PREV_CLOSE_PX(140, "PREV_CLOSE_PX", "PrevClosePx"),
    /*
     *
     * End of FIX4.0
     *
     */


    /*
     * Start of FIX4.2 as defined by the FIX Protocol Specification 4.2
     *  Tags: 141-446
     */
    FIX141_RESET_SEQ_NUM_FLAG(141, "RESET_SEQ_NUM_FLAG", "ResetSeqNumFlag"),
    FIX142_SENDER_LOCATION_ID(142, "SENDER_LOCATION_ID", "SenderLocationID"),
    FIX143_TARGET_LOCATION_ID(143, "TARGET_LOCATION_ID", "TargetLocationID"),
    FIX144_ON_BEHALF_OF_LOCATION_ID(144, "ON_BEHALF_OF_LOCATION_ID", "OnBehalfOfLocationID"),
    FIX145_DELIVER_TO_LOCATION_ID(145, "DELIVER_TO_LOCATION_ID", "DeliverToLocationID"),
    FIX146_NO_RELATED_SYM(146, "NO_RELATED_SYM", "NoRelatedSym"),
    FIX147_SUBJECT(147, "SUBJECT", "Subject"),
    FIX148_HEADLINE(148, "HEADLINE", "Headline"),
    FIX149_URL_LINK(149, "URL_LINK", "URLLink"),
    FIX150_EXEC_TYPE(150, "EXEC_TYPE", "ExecType"),

    FIX151_LEAVES_QTY(151, "LEAVES_QTY", "LeavesQty"),
    FIX152_CASH_ORDER_QTY(152, "CASH_ORDER_QTY", "CashOrderQty"),
    FIX153_ALLOC_AVG_PX(153, "ALLOC_AVG_PX", "AllocAvgPx"),
    FIX154_ALLOC_NET_MONEY(154, "ALLOC_NET_MONEY", "AllocNetMoney"),
    FIX155_SETTL_CURR_FX_RATE(155, "SETTL_CURR_FX_RATE", "SettlCurrFxRate"),
    FIX156_SETTL_CURR_FX_RATE_CALC(156, "SETTL_CURR_FX_RATE_CALC", "SettlCurrFxRateCalc"),
    FIX157_NUM_DAYS_INTEREST(157, "NUM_DAYS_INTEREST", "NumDaysInterest"),
    FIX158_ACCRUED_INTEREST_RATE(158, "ACCRUED_INTEREST_RATE", "AccruedInterestRate"),
    FIX159_ACCRUED_INTEREST_AMT(159, "ACCRUED_INTEREST_AMT", "AccruedInterestAmt"),
    FIX160_SETTL_INST_MODE(160, "SETTL_INST_MODE", "SettlInstMode"),

    FIX161_ALLOC_TEXT(161, "ALLOC_TEXT", "AllocText"),
    FIX162_SETTL_INST_ID(162, "SETTL_INST_ID", "SettlInstID"),
    FIX163_SETTL_INST_TRANS_TYPE(163, "SETTL_INST_TRANS_TYPE", "SettlInstTransType"),
    FIX164_EMAIL_THREAD_ID(164, "EMAIL_THREAD_ID", "EmailThreadID"),
    FIX165_SETTL_INST_SOURCE(165, "SETTL_INST_SOURCE", "SettlInstSource"),
    FIX166_SETTL_LOCATION(166, "SETTL_LOCATION", "SettlLocation (replaced)"),
    FIX167_SECURITY_TYPE(167, "SECURITY_TYPE", "SecurityType"),
    FIX168_EFFECTIVE_TIME(168, "EFFECTIVE_TIME", "EffectiveTime"),
    FIX169_STAND_INST_DB_TYPE(169, "STAND_INST_DB_TYPE", "StandInstDbType"),
    FIX170_STAND_INST_DB_NAME(170, "STAND_INST_DB_NAME", "StandInstDbName"),

    FIX171_STAND_INST_DB_ID(171, "STAND_INST_DB_ID", "StandInstDbID"),
    FIX172_SETTL_DELIVERY_TYPE(172, "SETTL_DELIVERY_TYPE", "SettlDeliveryType"),
    FIX173_SETTL_DEPOSITORY_CODE(173, "SETTL_DEPOSITORY_CODE", "SettlDepositoryCode (replaced)"),
    FIX174_SETTL_BRKR_CODE(174, "SETTL_BRKR_CODE", "SettlBrkrCode (replaced)"),
    FIX175_SETTL_INST_CODE(175, "SETTL_INST_CODE", "SettlInstCode (replaced)"),
    FIX176_SECURITY_SETTL_AGENT_NAME(176, "SECURITY_SETTL_AGENT_NAME", "SecuritySettlAgentName (replaced)"),
    FIX177_SECURITY_SETTL_AGENT_CODE(177, "SECURITY_SETTL_AGENT_CODE", "SecuritySettlAgentCode (replaced)"),
    FIX178_SECURITY_SETTL_AGENT_ACCT_NUM(178, "SECURITY_SETTL_AGENT_ACCT_NUM", "SecuritySettlAgentAcctNum (replaced)"),
    FIX179_SECURITY_SETTL_AGENT_ACCT_NAME(179, "SECURITY_SETTL_AGENT_ACCT_NAME", "SecuritySettlAgentAcctName (replaced)"),
    FIX180_SECURITY_SETTL_AGENT_CONTACT_NAME(180, "SECURITY_SETTL_AGENT_CONTACT_NAME", "SecuritySettlAgentContactName (replaced)"),

    FIX181_SECURITY_SETTL_AGENT_CONTACT_PHONE(181, "SECURITY_SETTL_AGENT_CONTACT_PHONE", "SecuritySettlAgentContactPhone (replaced)"),
    FIX182_CASH_SETTL_AGENT_NAME(182, "CASH_SETTL_AGENT_NAME", "CashSettlAgentName (replaced)"),
    FIX183_CASH_SETTL_AGENT_CODE(183, "CASH_SETTL_AGENT_CODE", "CashSettlAgentCode (replaced)"),
    FIX184_CASH_SETTL_AGENT_ACCT_NUM(184, "CASH_SETTL_AGENT_ACCT_NUM", "CashSettlAgentAcctNum (replaced)"),
    FIX185_CASH_SETTL_AGENT_ACCT_NAME(185, "CASH_SETTL_AGENT_ACCT_NAME", "CashSettlAgentAcctName (replaced)"),
    FIX186_CASH_SETTL_AGENT_CONTACT_NAME(186, "CASH_SETTL_AGENT_CONTACT_NAME", "CashSettlAgentContactName (replaced)"),
    FIX187_CASH_SETTL_AGENT_CONTACT_PHONE(187, "CASH_SETTL_AGENT_CONTACT_PHONE", "CashSettlAgentContactPhone (replaced)"),
    FIX188_BID_SPOT_RATE(188, "BID_SPOT_RATE", "BidSpotRate"),
    FIX189_BID_FORWARD_POINTS(189, "BID_FORWARD_POINTS", "BidForwardPoints"),
    FIX190_OFFER_SPOT_RATE(190, "OFFER_SPOT_RATE", "OfferSpotRate"),

    FIX191_OFFER_FORWARD_POINTS(191, "OFFER_FORWARD_POINTS", "OfferForwardPoints"),
    FIX192_ORDER_QTY_2(192, "ORDER_QTY_2", "OrderQty2"),
    FIX193_FUT_SETT_DATE_2(193, "FUT_SETT_DATE_2", "FutSettDate2"),
    FIX194_LAST_SPOT_RATE(194, "LAST_SPOT_RATE", "LastSpotRate"),
    FIX195_LAST_FORWARD_POINTS(195, "LAST_FORWARD_POINTS", "LastForwardPoints"),
    FIX196_ALLOC_LINK_ID(196, "ALLOC_LINK_ID", "AllocLinkID"),
    FIX197_ALLOC_LINK_TYPE(197, "ALLOC_LINK_TYPE", "AllocLinkType"),
    FIX198_SECONDARY_ORDER_ID(198, "SECONDARY_ORDER_ID", "SecondaryOrderID"),
    FIX199_NO_IOI_QUALIFIERS(199, "NO_IOI_QUALIFIERS", "NoIOIQualifiers"),
    FIX200_MATURITY_MONTH_YEAR(200, "MATURITY_MONTH_YEAR", "MaturityMonthYear"),


    // 201-300

    FIX201_PUT_OR_CALL(201, "PUT_OR_CALL", "PutOrCall (replaced)"),
    FIX202_STRIKE_PRICE(202, "STRIKE_PRICE", "StrikePrice"),
    FIX203_COVERED_OR_UNCOVERED(203, "COVERED_OR_UNCOVERED", "CoveredOrUncovered"),
    FIX204_CUSTOMER_OR_FIRM(204, "CUSTOMER_OR_FIRM", "CustomerOrFirm (replaced)"),
    FIX205_MATURITY_DAY(205, "MATURITY_DAY", "MaturityDay (replaced)"),
    FIX206_OPT_ATTRIBUTE(206, "OPT_ATTRIBUTE", "OptAttribute"),
    FIX207_SECURITY_EXCHANGE(207, "SECURITY_EXCHANGE", "SecurityExchange"),
    FIX208_NOTIFY_BROKER_OF_CREDIT(208, "NOTIFY_BROKER_OF_CREDIT", "NotifyBrokerOfCredit"),
    FIX209_ALLOC_HANDL_INST(209, "ALLOC_HANDL_INST", "AllocHandlInst"),
    FIX210_MAX_SHOW(210, "MAX_SHOW", "MaxShow"),

    FIX211_PEG_DIFFERENCE(211, "PEG_DIFFERENCE", "PegDifference"),
    FIX212_XML_DATA_LEN(212, "XML_DATA_LEN", "XmlDataLen"),
    FIX213_XML_DATA(213, "XML_DATA", "XmlData"),
    FIX214_SETTL_INST_REF_ID(214, "SETTL_INST_REF_ID", "SettlInstRefID"),
    FIX215_NO_ROUTING_IDS(215, "NO_ROUTING_IDS", "NoRoutingIDs"),
    FIX216_ROUTING_TYPE(216, "ROUTING_TYPE", "RoutingType"),
    FIX217_ROUTING_ID(217, "ROUTING_ID", "RoutingID"),
    FIX218_SPREAD_TO_BENCHMARK(218, "SPREAD_TO_BENCHMARK", "SpreadToBenchmark"),
    FIX219_BENCHMARK(219, "BENCHMARK", "Benchmark (no longer used)"),
    FIX220_BENCHMARK_CURVE_CURRENCY(220, "BENCHMARK_CURVE_CURRENCY", "BenchmarkCurveCurrency"),

    FIX221_BENCHMARK_CURVE_NAME(221, "BENCHMARK_CURVE_NAME", "BenchmarkCurveName"),
    FIX222_BENCHMARK_CURVE_POINT(222, "BENCHMARK_CURVE_POINT", "BenchmarkCurvePoint"),
    FIX223_COUPON_RATE(223, "COUPON_RATE", "CouponRate"),
    FIX224_COUPON_PAYMENT_DATE(224, "COUPON_PAYMENT_DATE", "CouponPaymentDate"),
    FIX225_ISSUE_DATE(225, "ISSUE_DATE", "IssueDate"),
    FIX226_REPURCHASE_TERM(226, "REPURCHASE_TERM", "RepurchaseTerm (Deprecated)"),
    FIX227_REPURCHASE_RATE(227, "REPURCHASE_RATE", "RepurchaseRate (Deprecated)"),
    FIX228_FACTOR(228, "FACTOR", "Factor"),
    FIX229_TRADE_ORIGINATION_DATE(229, "TRADE_ORIGINATION_DATE", "TradeOriginationDate"),
    FIX230_EX_DATE(230, "EX_DATE", "ExDate"),

    FIX231_CONTRACT_MULTIPLIER(231, "CONTRACT_MULTIPLIER", "ContractMultiplier"),
    FIX232_NO_STIPULATIONS(232, "NO_STIPULATIONS", "NoStipulations"),
    FIX233_STIPULATION_TYPE(233, "STIPULATION_TYPE", "StipulationType"),
    FIX234_STIPULATION_VALUE(234, "STIPULATION_VALUE", "StipulationValue"),
    FIX235_YIELD_TYPE(235, "YIELD_TYPE", "YieldType"),
    FIX236_YIELD(236, "YIELD", "Yield"),
    FIX237_TOTAL_TAKEDOWN(237, "TOTAL_TAKEDOWN", "TotalTakedown"),
    FIX238_CONCESSION(238, "CONCESSION", "Concession"),
    FIX239_REPO_COLLATERAL_SECURITY_TYPE(239, "REPO_COLLATERAL_SECURITY_TYPE", "RepoCollateralSecurityType (Deprecated)"),
    FIX240_REDEMPTION_DATE(240, "REDEMPTION_DATE", "RedemptionDate (Deprecated)"),

    FIX241_UNDERLYING_COUPON_PAYMENT_DATE(241, "UNDERLYING_COUPON_PAYMENT_DATE", "UnderlyingCouponPaymentDate"),
    FIX242_UNDERLYING_ISSUE_DATE(242, "UNDERLYING_ISSUE_DATE", "UnderlyingIssueDate"),
    FIX243_UNDERLYING_REPO_COLLATERAL_SECURITY_TYPE(243, "UNDERLYING_REPO_COLLATERAL_SECURITY_TYPE", "UnderlyingRepoCollateralSecurityType (Deprecated"),
    FIX244_UNDERLYING_REPURCHASE_TERM(244, "UNDERLYING_REPURCHASE_TERM", "UnderlyingRepurchaseTerm (Deprecated)"),
    FIX245_UNDERLYING_REPURCHASE_RATE(245, "UNDERLYING_REPURCHASE_RATE", "UnderlyingRepurchaseRate (Deprecated)"),
    FIX246_UNDERLYING_FACTOR(246, "UNDERLYING_FACTOR", "UnderlyingFactor"),
    FIX247_UNDERLYING_REDEMPTION_DATE(247, "UNDERLYING_REDEMPTION_DATE", "UnderlyingRedemptionDate (Deprecated)"),
    FIX248_LEG_COUPON_PAYMENT_DATE(248, "LEG_COUPON_PAYMENT_DATE", "LegCouponPaymentDate"),
    FIX249_LEG_ISSUE_DATE(249, "LEG_ISSUE_DATE", "LegIssueDate"),
    FIX250_LEG_REPO_COLLATERAL_SECURITY_TYPE(250, "LEG_REPO_COLLATERAL_SECURITY_TYPE", "LegRepoCollateralSecurityType (Deprecated)"),

    FIX251_LEG_REPURCHASE_TERM(251, "LEG_REPURCHASE_TERM", "LegRepurchaseTerm (Deprecated)"),
    FIX252_LEG_REPURCHASE_RATE(252, "LEG_REPURCHASE_RATE", "LegRepurchaseRate (Deprecated)"),
    FIX253_LEG_FACTOR(253, "LEG_FACTOR", "LegFactor"),
    FIX254_LEG_REDEMPTION_DATE(254, "LEG_REDEMPTION_DATE", "LegRedemptionDate (Deprecated)"),
    FIX255_CREDIT_RATING(255, "CREDIT_RATING", "CreditRating"),
    FIX256_UNDERLYING_CREDIT_RATING(256, "UNDERLYING_CREDIT_RATING", "UnderlyingCreditRating"),
    FIX257_LEG_CREDIT_RATING(257, "LEG_CREDIT_RATING", "LegCreditRating"),
    FIX258_TRADED_FLAT_SWITCH(258, "TRADED_FLAT_SWITCH", "TradedFlatSwitch"),
    FIX259_BASIS_FEATURE_DATE(259, "BASIS_FEATURE_DATE", "BasisFeatureDate"),
    FIX260_BASIS_FEATURE_PRICE(260, "BASIS_FEATURE_PRICE", "BasisFeaturePrice"),

    FIX262_MD_REQ_ID(262, "MD_REQ_ID", "MDReqID"),
    FIX263_SUBSCRIPTION_REQUEST_TYPE(263, "SUBSCRIPTION_REQUEST_TYPE", "SubscriptionRequestType"),
    FIX264_MARKET_DEPTH(264, "MARKET_DEPTH", "MarketDepth"),
    FIX265_MD_UPDATE_TYPE(265, "MD_UPDATE_TYPE", "MDUpdateType"),
    FIX266_AGGREGATED_BOOK(266, "AGGREGATED_BOOK", "AggregatedBook"),
    FIX267_NO_MD_ENTRY_TYPES(267, "NO_MD_ENTRY_TYPES", "NoMDEntryTypes"),
    FIX268_NO_MD_ENTRIES(268, "NO_MD_ENTRIES", "NoMDEntries"),
    FIX269_MD_ENTRY_TYPE(269, "MD_ENTRY_TYPE", "MDEntryType"),
    FIX270_MD_ENTRY_PX(270, "MD_ENTRY_PX", "MDEntryPx"),

    FIX271_MD_ENTRY_SIZE(271, "MD_ENTRY_SIZE", "MDEntrySize"),
    FIX272_MD_ENTRY_DATE(272, "MD_ENTRY_DATE", "MDEntryDate"),
    FIX273_MD_ENTRY_TIME(273, "MD_ENTRY_TIME", "MDEntryTime"),
    FIX274_TICK_DIRECTION(274, "TICK_DIRECTION", "TickDirection"),
    FIX275_MD_MKT(275, "MD_MKT", "MDMkt"),
    FIX276_QUOTE_CONDITION(276, "QUOTE_CONDITION", "QuoteCondition"),
    FIX277_TRADE_CONDITION(277, "TRADE_CONDITION", "TradeCondition"),
    FIX278_MD_ENTRY_ID(278, "MD_ENTRY_ID", "MDEntryID"),
    FIX279_MD_UPDATE_ACTION(279, "MD_UPDATE_ACTION", "MDUpdateAction"),
    FIX280_MD_ENTRY_REF_ID(280, "MD_ENTRY_REF_ID", "MDEntryRefID"),

    FIX281_MD_REQ_REJ_REASON(281, "MD_REQ_REJ_REASON", "MDReqRejReason"),
    FIX282_MD_ENTRY_ORIGINATOR(282, "MD_ENTRY_ORIGINATOR", "MDEntryOriginator"),
    FIX283_LOCATION_ID(283, "LOCATION_ID", "LocationID"),
    FIX284_DESK_ID(284, "DESK_ID", "DeskID"),
    FIX285_DELETE_REASON(285, "DELETE_REASON", "DeleteReason"),
    FIX286_OPEN_CLOSE_SETTLE_FLAG(286, "OPEN_CLOSE_SETTLE_FLAG", "OpenCloseSettleFlag"),
    FIX287_SELLER_DAYS(287, "SELLER_DAYS", "SellerDays"),
    FIX288_MD_ENTRY_BUYER(288, "MD_ENTRY_BUYER", "MDEntryBuyer"),
    FIX289_MD_ENTRY_SELLER(289, "MD_ENTRY_SELLER", "MDEntrySeller"),
    FIX290_MD_ENTRY_POSITION_NO(290, "MD_ENTRY_POSITION_NO", "MDEntryPositionNo"),

    FIX291_FINANCIAL_STATUS(291, "FINANCIAL_STATUS", "FinancialStatus"),
    FIX292_CORPORATE_ACTION(292, "CORPORATE_ACTION", "CorporateAction"),
    FIX293_DEF_BID_SIZE(293, "DEF_BID_SIZE", "DefBidSize"),
    FIX294_DEF_OFFER_SIZE(294, "DEF_OFFER_SIZE", "DefOfferSize"),
    FIX295_NO_QUOTE_ENTRIES(295, "NO_QUOTE_ENTRIES", "NoQuoteEntries"),
    FIX296_NO_QUOTE_SETS(296, "NO_QUOTE_SETS", "NoQuoteSets"),
    FIX297_QUOTE_ACK_STATUS(297, "QUOTE_ACK_STATUS", "QuoteAckStatus"),
    FIX298_QUOTE_CANCEL_TYPE(298, "QUOTE_CANCEL_TYPE", "QuoteCancelType"),
    FIX299_QUOTE_ENTRY_ID(299, "QUOTE_ENTRY_ID", "QuoteEntryID"),
    FIX300_QUOTE_REJECT_REASON(300, "QUOTE_REJECT_REASON", "QuoteRejectReason"),


    // 301-400

    FIX301_QUOTE_RESPONSE_LEVEL(301, "QUOTE_RESPONSE_LEVEL", "QuoteResponseLevel"),
    FIX302_QUOTE_SET_ID(302, "QUOTE_SET_ID", "QuoteSetID"),
    FIX303_QUOTE_REQUEST_TYPE(303, "QUOTE_REQUEST_TYPE", "QuoteRequestType"),
    FIX304_TOT_QUOTE_ENTRIES(304, "TOT_QUOTE_ENTRIES", "TotQuoteEntries"),
    FIX305_UNDERLYING_ID_SOURCE(305, "UNDERLYING_ID_SOURCE", "UnderlyingIDSource"),
    FIX306_UNDERLYING_ISSUER(306, "UNDERLYING_ISSUER", "UnderlyingIssuer"),
    FIX307_UNDERLYING_SECURITY_DESC(307, "UNDERLYING_SECURITY_DESC", "UnderlyingSecurityDesc"),
    FIX308_UNDERLYING_SECURITY_EXCHANGE(308, "UNDERLYING_SECURITY_EXCHANGE", "UnderlyingSecurityExchange"),
    FIX309_UNDERLYING_SECURITY_ID(309, "UNDERLYING_SECURITY_ID", "UnderlyingSecurityID"),
    FIX310_UNDERLYING_SECURITY_TYPE(310, "UNDERLYING_SECURITY_TYPE", "UnderlyingSecurityType"),

    FIX311_UNDERLYING_SYMBOL(311, "UNDERLYING_SYMBOL", "UnderlyingSymbol"),
    FIX312_UNDERLYING_SYMBOL_SFX(312, "UNDERLYING_SYMBOL_SFX", "UnderlyingSymbolSfx"),
    FIX313_UNDERLYING_MATURITY_MONTH_YEAR(313, "UNDERLYING_MATURITY_MONTH_YEAR", "UnderlyingMaturityMonthYear"),
    FIX314_UNDERLYING_MATURITY_DAY(314, "UNDERLYING_MATURITY_DAY", "UnderlyingMaturityDay (replaced)"),
    FIX315_UNDERLYING_PUT_OR_CALL(315, "UNDERLYING_PUT_OR_CALL", "UnderlyingPutOrCall (replaced)"),
    FIX316_UNDERLYING_STRIKE_PRICE(316, "UNDERLYING_STRIKE_PRICE", "UnderlyingStrikePrice"),
    FIX317_UNDERLYING_OPT_ATTRIBUTE(317, "UNDERLYING_OPT_ATTRIBUTE", "UnderlyingOptAttribute"),
    FIX318_UNDERLYING_CURRENCY(318, "UNDERLYING_CURRENCY", "UnderlyingCurrency"),
    FIX319_RATIO_QTY(319, "RATIO_QTY", "RatioQty (unused)"),
    FIX320_SECURITY_REQ_ID(320, "SECURITY_REQ_ID", "SecurityReqID"),

    FIX321_SECURITY_REQUEST_TYPE(321, "SECURITY_REQUEST_TYPE", "SecurityRequestType"),
    FIX322_SECURITY_RESPONSE_ID(322, "SECURITY_RESPONSE_ID", "SecurityResponseID"),
    FIX323_SECURITY_RESPONSE_TYPE(323, "SECURITY_RESPONSE_TYPE", "SecurityResponseType"),
    FIX324_SECURITY_STATUS_REQ_ID(324, "SECURITY_STATUS_REQ_ID", "SecurityStatusReqID"),
    FIX325_UNSOLICITED_INDICATOR(325, "UNSOLICITED_INDICATOR", "UnsolicitedIndicator"),
    FIX326_SECURITY_TRADING_STATUS(326, "SECURITY_TRADING_STATUS", "SecurityTradingStatus"),
    FIX327_HALT_REASON(327, "HALT_REASON", "HaltReason"),
    FIX328_IN_VIEW_OF_COMMON(328, "IN_VIEW_OF_COMMON", "InViewOfCommon"),
    FIX329_DUE_TO_RELATED(329, "DUE_TO_RELATED", "DueToRelated"),
    FIX330_BUY_VOLUME(330, "BUY_VOLUME", "BuyVolume"),

    FIX331_SELL_VOLUME(331, "SELL_VOLUME", "SellVolume"),
    FIX332_HIGH_PX(332, "HIGH_PX", "HighPx"),
    FIX333_LOW_PX(333, "LOW_PX", "LowPx"),
    FIX334_ADJUSTMENT(334, "ADJUSTMENT", "Adjustment"),
    FIX335_TRAD_SES_REQ_ID(335, "TRAD_SES_REQ_ID", "TradSesReqID"),
    FIX336_TRADING_SESSION_ID(336, "TRADING_SESSION_ID", "TradingSessionID"),
    FIX337_CONTRA_TRADER(337, "CONTRA_TRADER", "ContraTrader"),
    FIX338_TRAD_SES_METHOD(338, "TRAD_SES_METHOD", "TradSesMethod"),
    FIX339_TRAD_SES_MODE(339, "TRAD_SES_MODE", "TradSesMode"),
    FIX340_TRAD_SES_STATUS(340, "TRAD_SES_STATUS", "TradSesStatus"),

    FIX341_TRAD_SES_START_TIME(341, "TRAD_SES_START_TIME", "TradSesStartTime"),
    FIX342_TRAD_SES_OPEN_TIME(342, "TRAD_SES_OPEN_TIME", "TradSesOpenTime"),
    FIX343_TRAD_SES_PRE_CLOSE_TIME(343, "TRAD_SES_PRE_CLOSE_TIME", "TradSesPreCloseTime"),
    FIX344_TRAD_SES_CLOSE_TIME(344, "TRAD_SES_CLOSE_TIME", "TradSesCloseTime"),
    FIX345_TRAD_SES_END_TIME(345, "TRAD_SES_END_TIME", "TradSesEndTime"),
    FIX346_NUMBER_OF_ORDERS(346, "NUMBER_OF_ORDERS", "NumberOfOrders"),
    FIX347_MESSAGE_ENCODING(347, "MESSAGE_ENCODING", "MessageEncoding"),
    FIX348_ENCODED_ISSUER_LEN(348, "ENCODED_ISSUER_LEN", "EncodedIssuerLen"),
    FIX349_ENCODED_ISSUER(349, "ENCODED_ISSUER", "EncodedIssuer"),
    FIX350_ENCODED_SECURITY_DESC_LEN(350, "ENCODED_SECURITY_DESC_LEN", "EncodedSecurityDescLen"),

    FIX351_ENCODED_SECURITY_DESC(351, "ENCODED_SECURITY_DESC", "EncodedSecurityDesc"),
    FIX352_ENCODED_LIST_EXEC_INST_LEN(352, "ENCODED_LIST_EXEC_INST_LEN", "EncodedListExecInstLen"),
    FIX353_ENCODED_LIST_EXEC_INST(353, "ENCODED_LIST_EXEC_INST", "EncodedListExecInst"),
    FIX354_ENCODED_TEXT_LEN(354, "ENCODED_TEXT_LEN", "EncodedTextLen"),
    FIX355_ENCODED_TEXT(355, "ENCODED_TEXT", "EncodedText"),
    FIX356_ENCODED_SUBJECT_LEN(356, "ENCODED_SUBJECT_LEN", "EncodedSubjectLen"),
    FIX357_ENCODED_SUBJECT(357, "ENCODED_SUBJECT", "EncodedSubject"),
    FIX358_ENCODED_HEADLINE_LEN(358, "ENCODED_HEADLINE_LEN", "EncodedHeadlineLen"),
    FIX359_ENCODED_HEADLINE(359, "ENCODED_HEADLINE", "EncodedHeadline"),
    FIX360_ENCODED_ALLOC_TEXT_LEN(360, "ENCODED_ALLOC_TEXT_LEN", "EncodedAllocTextLen"),

    FIX361_ENCODED_ALLOC_TEXT(361, "ENCODED_ALLOC_TEXT", "EncodedAllocText"),
    FIX362_ENCODED_UNDERLYING_ISSUER_LEN(362, "ENCODED_UNDERLYING_ISSUER_LEN", "EncodedUnderlyingIssuerLen"),
    FIX363_ENCODED_UNDERLYING_ISSUER(363, "ENCODED_UNDERLYING_ISSUER", "EncodedUnderlyingIssuer"),
    FIX364_ENCODED_UNDERLYING_SECURITY_DESC_LEN(364, "ENCODED_UNDERLYING_SECURITY_DESC_LEN", "EncodedUnderlyingSecurityDescLen"),
    FIX365_ENCODED_UNDERLYING_SECURITY_DESC(365, "ENCODED_UNDERLYING_SECURITY_DESC", "EncodedUnderlyingSecurityDesc"),
    FIX366_ALLOC_PRICE(366, "ALLOC_PRICE", "AllocPrice"),
    FIX367_QUOTE_SET_VALID_UNTIL_TIME(367, "QUOTE_SET_VALID_UNTIL_TIME", "QuoteSetValidUntilTime"),
    FIX368_QUOTE_ENTRY_REJECT_REASON(368, "QUOTE_ENTRY_REJECT_REASON", "QuoteEntryRejectReason"),
    FIX369_LAST_MSG_SEQ_NUM_PROCESSED(369, "LAST_MSG_SEQ_NUM_PROCESSED", "LastMsgSeqNumProcessed"),
    FIX370_ON_BEHALF_OF_SENDING_TIME(370, "ON_BEHALF_OF_SENDING_TIME", "OnBehalfOfSendingTime"),

    FIX371_REF_TAG_ID(371, "REF_TAG_ID", "RefTagID"),
    FIX372_REF_MSG_TYPE(372, "REF_MSG_TYPE", "RefMsgType"),
    FIX373_SESSION_REJECT_REASON(373, "SESSION_REJECT_REASON", "SessionRejectReason"),
    FIX374_BID_REQUEST_TRANS_TYPE(374, "BID_REQUEST_TRANS_TYPE", "BidRequestTransType"),
    FIX375_CONTRA_BROKER(375, "CONTRA_BROKER", "ContraBroker"),
    FIX376_COMPLIANCE_ID(376, "COMPLIANCE_ID", "ComplianceID"),
    FIX377_SOLICITED_FLAG(377, "SOLICITED_FLAG", "SolicitedFlag"),
    FIX378_EXEC_RESTATEMENT_REASON(378, "EXEC_RESTATEMENT_REASON", "ExecRestatementReason"),
    FIX379_BUSINESS_REJECT_REF_ID(379, "BUSINESS_REJECT_REF_ID", "BusinessRejectRefID"),
    FIX380_BUSINESS_REJECT_REASON(380, "BUSINESS_REJECT_REASON", "BusinessRejectReason"),

    FIX381_GROSS_TRADE_AMT(381, "GROSS_TRADE_AMT", "GrossTradeAmt"),
    FIX382_NO_CONTRA_BROKERS(382, "NO_CONTRA_BROKERS", "NoContraBrokers"),
    FIX383_MAX_MESSAGE_SIZE(383, "MAX_MESSAGE_SIZE", "MaxMessageSize"),
    FIX384_NO_MSG_TYPES(384, "NO_MSG_TYPES", "NoMsgTypes"),
    FIX385_MSG_DIRECTION(385, "MSG_DIRECTION", "MsgDirection"),
    FIX386_NO_TRADING_SESSIONS(386, "NO_TRADING_SESSIONS", "NoTradingSessions"),
    FIX387_TOTAL_VOLUME_TRADED(387, "TOTAL_VOLUME_TRADED", "TotalVolumeTraded"),
    FIX388_DISCRETION_INST(388, "DISCRETION_INST", "DiscretionInst"),
    FIX389_DISCRETION_OFFSET(389, "DISCRETION_OFFSET", "DiscretionOffset"),
    FIX390_BID_ID(390, "BID_ID", "BidID"),

    FIX391_CLIENT_BID_ID(391, "CLIENT_BID_ID", "ClientBidID"),
    FIX392_LIST_NAME(392, "LIST_NAME", "ListName"),
    FIX393_TOTAL_NUM_SECURITIES(393, "TOTAL_NUM_SECURITIES", "TotalNumSecurities"),
    FIX394_BID_TYPE(394, "BID_TYPE", "BidType"),
    FIX395_NUM_TICKETS(395, "NUM_TICKETS", "NumTickets"),
    FIX396_SIDE_VALUE1(396, "SIDE_VALUE1", "SideValue1"),
    FIX397_SIDE_VALUE2(397, "SIDE_VALUE2", "SideValue2"),
    FIX398_NO_BID_DESCRIPTORS(398, "NO_BID_DESCRIPTORS", "NoBidDescriptors"),
    FIX399_BID_DESCRIPTOR_TYPE(399, "BID_DESCRIPTOR_TYPE", "BidDescriptorType"),
    FIX400_BID_DESCRIPTOR(400, "BID_DESCRIPTOR", "BidDescriptor"),


    // 401-500

    FIX401_SIDE_VALUE_IND(401, "SIDE_VALUE_IND", "SideValueInd"),
    FIX402_LIQUIDITY_PCT_LOW(402, "LIQUIDITY_PCT_LOW", "LiquidityPctLow"),
    FIX403_LIQUIDITY_PCT_HIGH(403, "LIQUIDITY_PCT_HIGH", "LiquidityPctHigh"),
    FIX404_LIQUIDITY_VALUE(404, "LIQUIDITY_VALUE", "LiquidityValue"),
    FIX405_EFP_TRACKING_ERROR(405, "EFP_TRACKING_ERROR", "EFPTrackingError"),
    FIX406_FAIR_VALUE(406, "FAIR_VALUE", "FairValue"),
    FIX407_OUTSIDE_INDEX_PCT(407, "OUTSIDE_INDEX_PCT", "OutsideIndexPct"),
    FIX408_VALUE_OF_FUTURES(408, "VALUE_OF_FUTURES", "ValueOfFutures"),
    FIX409_LIQUIDITY_IND_TYPE(409, "LIQUIDITY_IND_TYPE", "LiquidityIndType"),
    FIX410_WT_AVERAGE_LIQUIDITY(410, "WT_AVERAGE_LIQUIDITY", "WtAverageLiquidity"),

    FIX411_EXCHANGE_FOR_PHYSICAL(411, "EXCHANGE_FOR_PHYSICAL", "ExchangeForPhysical"),
    FIX412_OUT_MAIN_CNTRY_U_INDEX(412, "OUT_MAIN_CNTRY_U_INDEX", "OutMainCntryUIndex"),
    FIX413_CROSS_PERCENT(413, "CROSS_PERCENT", "CrossPercent"),
    FIX414_PROG_RPT_REQS(414, "PROG_RPT_REQS", "ProgRptReqs"),
    FIX415_PROG_PERIOD_INTERVAL(415, "PROG_PERIOD_INTERVAL", "ProgPeriodInterval"),
    FIX416_INC_TAX_IND(416, "INC_TAX_IND", "IncTaxInd"),
    FIX417_NUM_BIDDERS(417, "NUM_BIDDERS", "NumBidders"),
    FIX418_TRADE_TYPE(418, "TRADE_TYPE", "TradeType"),
    FIX419_BASIS_PX_TYPE(419, "BASIS_PX_TYPE", "BasisPxType"),
    FIX420_NO_BID_COMPONENTS(420, "NO_BID_COMPONENTS", "NoBidComponents"),

    FIX421_COUNTRY(421, "COUNTRY", "Country"),
    FIX422_TOT_NO_STRIKES(422, "TOT_NO_STRIKES", "TotNoStrikes"),
    FIX423_PRICE_TYPE(423, "PRICE_TYPE", "PriceType"),
    FIX424_DAY_ORDER_QTY(424, "DAY_ORDER_QTY", "DayOrderQty"),
    FIX425_DAY_CUM_QTY(425, "DAY_CUM_QTY", "DayCumQty"),
    FIX426_DAY_AVG_PX(426, "DAY_AVG_PX", "DayAvgPx"),
    FIX427_GT_BOOKING_INST(427, "GT_BOOKING_INST", "GTBookingInst"),
    FIX428_NO_STRIKES(428, "NO_STRIKES", "NoStrikes"),
    FIX429_LIST_STATUS_TYPE(429, "LIST_STATUS_TYPE", "ListStatusType"),
    FIX430_NET_GROSS_IND(430, "NET_GROSS_IND", "NetGrossInd"),

    FIX431_LIST_ORDER_STATUS(431, "LIST_ORDER_STATUS", "ListOrderStatus"),
    FIX432_EXPIRE_DATE(432, "EXPIRE_DATE", "ExpireDate"),
    FIX433_LIST_EXEC_INST_TYPE(433, "LIST_EXEC_INST_TYPE", "ListExecInstType"),
    FIX434_CXL_REJ_RESPONSE_TO(434, "CXL_REJ_RESPONSE_TO", "CxlRejResponseTo"),
    FIX435_UNDERLYING_COUPON_RATE(435, "UNDERLYING_COUPON_RATE", "UnderlyingCouponRate"),
    FIX436_UNDERLYING_CONTRACT_MULTIPLIER(436, "UNDERLYING_CONTRACT_MULTIPLIER", "UnderlyingContractMultiplier"),
    FIX437_CONTRA_TRADE_QTY(437, "CONTRA_TRADE_QTY", "ContraTradeQty"),
    FIX438_CONTRA_TRADE_TIME(438, "CONTRA_TRADE_TIME", "ContraTradeTime"),
    FIX439_CLEARING_FIRM(439, "CLEARING_FIRM", "ClearingFirm"),
    FIX440_CLEARING_ACCOUNT(440, "CLEARING_ACCOUNT", "ClearingAccount"),

    FIX441_LIQUIDITY_NUM_SECURITIES(441, "LIQUIDITY_NUM_SECURITIES", "LiquidityNumSecurities"),
    FIX442_MULTI_LEG_REPORTING_TYPE(442, "MULTI_LEG_REPORTING_TYPE", "MultiLegReportingType"),
    FIX443_STRIKE_TIME(443, "STRIKE_TIME", "StrikeTime"),
    FIX444_LIST_STATUS_TEXT(444, "LIST_STATUS_TEXT", "ListStatusText"),
    FIX445_LIST_STATUS_ENCODED_TEXT_LEN(445, "LIST_STATUS_ENCODED_TEXT_LEN", "ListStatusEncodedTextLen"),
    FIX446_LIST_STATUS_ENCODED_TEXT(446, "LIST_STATUS_ENCODED_TEXT", "ListStatusEncodedText"),
    /*
     *
     * End of FIX4.2
     *
     */


    /*
     * Start of FIX4.3 as defined by the FIX Protocol Specification 4.3
     *  Tags: 447-659
     */
    FIX447_PARTY_ID_SOURCE(447, "PARTY_ID_SOURCE", "PartyIDSource"),
    FIX448_PARTY_ID(448, "PARTY_ID", "PartyID"),
    FIX449_TOTAL_VOLUME_TRADED_DATE(449, "TOTAL_VOLUME_TRADED_DATE", "TotalVolumeTradedDate (replaced)"),
    FIX450_TOTAL_VOLUME_TRADED_TIME(450, "TOTAL_VOLUME_TRADED_TIME", "TotalVolumeTradedTime (replaced)"),
// TODO: add FIXnnn_ prefix to FIX4.3
    NET_CHG_PREV_DAY(451, "NET_CHG_PREV_DAY", "NetChgPrevDay"),
    PARTY_ROLE(452, "PARTY_ROLE", "PartyRole"),
    NO_PARTY_IDS(453, "NO_PARTY_IDS", "NoPartyIDs"),
    NO_SECURITY_ALT_ID(454, "NO_SECURITY_ALT_ID", "NoSecurityAltID"),
    SECURITY_ALT_ID(455, "SECURITY_ALT_ID", "SecurityAltID"),
    SECURITY_ALT_ID_SOURCE(456, "SECURITY_ALT_ID_SOURCE", "SecurityAltIDSource"),
    NO_UNDERLYING_SECURITY_ALT_ID(457, "NO_UNDERLYING_SECURITY_ALT_ID", "NoUnderlyingSecurityAltID"),
    UNDERLYING_SECURITY_ALT_ID(458, "UNDERLYING_SECURITY_ALT_ID", "UnderlyingSecurityAltID"),
    UNDERLYING_SECURITY_ALT_ID_SOURCE(459, "UNDERLYING_SECURITY_ALT_ID_SOURCE", "UnderlyingSecurityAltIDSource"),
    PRODUCT(460, "PRODUCT", "Product"),

    CFI_CODE(461, "CFI_CODE", "CFICode"),
    UNDERLYING_PRODUCT(462, "UNDERLYING_PRODUCT", "UnderlyingProduct"),
    UNDERLYING_CFI_CODE(463, "UNDERLYING_CFI_CODE", "UnderlyingCFICode"),
    TEST_MESSAGE_INDICATOR(464, "TEST_MESSAGE_INDICATOR", "TestMessageIndicator"),
    QUANTITY_TYPE(465, "QUANTITY_TYPE", "QuantityType (Deprecated)"),
    BOOKING_REF_ID(466, "BOOKING_REF_ID", "BookingRefID"),
    INDIVIDUAL_ALLOC_ID(467, "INDIVIDUAL_ALLOC_ID", "IndividualAllocID"),
    ROUNDING_DIRECTION(468, "ROUNDING_DIRECTION", "RoundingDirection"),
    ROUNDING_MODULUS(469, "ROUNDING_MODULUS", "RoundingModulus"),
    COUNTRY_OF_ISSUE(470, "COUNTRY_OF_ISSUE", "CountryOfIssue"),

    STATE_OR_PROVINCE_OF_ISSUE(471, "STATE_OR_PROVINCE_OF_ISSUE", "StateOrProvinceOfIssue"),
    LOCALE_OF_ISSUE(472, "LOCALE_OF_ISSUE", "LocaleOfIssue"),
    NO_REGIST_DTLS(473, "NO_REGIST_DTLS", "NoRegistDtls"),
    MAILING_DTLS(474, "MAILING_DTLS", "MailingDtls"),
    INVESTOR_COUNTRY_OF_RESIDENCE(475, "INVESTOR_COUNTRY_OF_RESIDENCE", "InvestorCountryOfResidence"),
    PAYMENT_REF(476, "PAYMENT_REF", "PaymentRef"),
    DISTRIB_PAYMENT_METHOD(477, "", "DistribPaymentMethod"),
    CASH_DISTRIB_CURR(478, "DISTRIB_PAYMENT_METHOD", "CashDistribCurr"),
    COMM_CURRENCY(479, "COMM_CURRENCY", "CommCurrency"),
    CANCELLATION_RIGHTS(480, "CANCELLATION_RIGHTS", "CancellationRights"),

    MONEY_LAUNDERING_STATUS(481, "MONEY_LAUNDERING_STATUS", "MoneyLaunderingStatus"),
    MAILING_INST(482, "MAILING_INST", "MailingInst"),
    TRANS_BKD_TIME(483, "TRANS_BKD_TIME", "TransBkdTime"),
    EXEC_PRICE_TYPE(484, "EXEC_PRICE_TYPE", "ExecPriceType"),
    EXEC_PRICE_ADJUSTMENT(485, "EXEC_PRICE_ADJUSTMENT", "ExecPriceAdjustment"),
    DATE_OF_BIRTH(486, "DATE_OF_BIRTH", "DateOfBirth"),
    TRADE_REPORT_TRANS_TYPE(487, "TRADE_REPORT_TRANS_TYPE", "TradeReportTransType"),
    CARD_HOLDER_NAME(488, "CARD_HOLDER_NAME", "CardHolderName"),
    CARD_NUMBER(489, "CARD_NUMBER", "CardNumber"),
    CARD_EXP_DATE(490, "CARD_EXP_DATE", "CardExpDate"),

    CARD_ISS_NUM(491, "CARD_ISS_NUM", "CardIssNum"),
    PAYMENT_METHOD(492, "PAYMENT_METHOD", "PaymentMethod"),
    REGIST_ACCT_TYPE(493, "REGIST_ACCT_TYPE", "RegistAcctType"),
    DESIGNATION(494, "DESIGNATION", "Designation"),
    TAX_ADVANTAGE_TYPE(495, "TAX_ADVANTAGE_TYPE", "TaxAdvantageType"),
    REGIST_REJ_REASON_TEXT(496, "REGIST_REJ_REASON_TEXT", "RegistRejReasonText"),
    FUND_RENEW_WAIV(497, "FUND_RENEW_WAIV", "FundRenewWaiv"),
    CASH_DISTRIB_AGENT_NAME(498, "CASH_DISTRIB_AGENT_NAME", "CashDistribAgentName"),
    CASH_DISTRIB_AGENT_CODE(499, "CASH_DISTRIB_AGENT_CODE", "CashDistribAgentCode"),
    CASH_DISTRIB_AGENT_ACCT_NUMBER(500, "CASH_DISTRIB_AGENT_ACCT_NUMBER", "CashDistribAgentAcctNumber"),


    // 501-600

    CASH_DISTRIB_PAY_REF(501, "CASH_DISTRIB_PAY_REF", "CashDistribPayRef"),
    CASH_DISTRIB_AGENT_ACCT_NAME(502, "CASH_DISTRIB_AGENT_ACCT_NAME", "CashDistribAgentAcctName"),
    CARD_START_DATE(503, "CARD_START_DATE", "CardStartDate"),
    PAYMENT_DATE(504, "PAYMENT_DATE", "PaymentDate"),
    PAYMENT_REMITTER_ID(505, "PAYMENT_REMITTER_ID", "PaymentRemitterID"),
    REGIST_STATUS(506, "REGIST_STATUS", "RegistStatus"),
    REGIST_REJ_REASON_CODE(507, "REGIST_REJ_REASON_CODE", "RegistRejReasonCode"),
    REGIST_REF_ID(508, "REGIST_REF_ID", "RegistRefID"),
    REGIST_DTLS(509, "REGIST_DTLS", "RegistDtls"),
    NO_DISTRIB_INSTS(510, "NO_DISTRIB_INSTS", "NoDistribInsts"),

    REGIST_EMAIL(511, "REGIST_EMAIL", "RegistEmail"),
    DISTRIB_PERCENTAGE(512, "DISTRIB_PERCENTAGE", "DistribPercentage"),
    REGIST_ID(513, "REGIST_ID", "RegistID"),
    REGIST_TRANS_TYPE(514, "REGIST_TRANS_TYPE", "RegistTransType"),
    EXEC_VALUATION_POINT(515, "EXEC_VALUATION_POINT", "ExecValuationPoint"),
    ORDER_PERCENT(516, "ORDER_PERCENT", "OrderPercent"),
    OWNERSHIP_TYPE(517, "OWNERSHIP_TYPE", "OwnershipType"),
    NO_CONT_AMTS(518, "NO_CONT_AMTS", "NoContAmts"),
    CONT_AMT_TYPE(519, "CONT_AMT_TYPE", "ContAmtType"),
    CONT_AMT_VALUE(520, "CONT_AMT_VALUE", "ContAmtValue"),

    CONT_AMT_CURR(521, "CONT_AMT_CURR", "ContAmtCurr"),
    OWNER_TYPE(522, "OWNER_TYPE", "OwnerType"),
    PARTY_SUB_ID(523, "PARTY_SUB_ID", "PartySubID"),
    NESTED_PARTY_ID(524, "NESTED_PARTY_ID", "NestedPartyID"),
    NESTED_PARTY_ID_SOURCE(525, "NESTED_PARTY_ID_SOURCE", "NestedPartyIDSource"),
    SECONDARY_CL_ORD_ID(526, "SECONDARY_CL_ORD_ID", "SecondaryClOrdID"),
    SECONDARY_EXEC_ID(527, "SECONDARY_EXEC_ID", "SecondaryExecID"),
    ORDER_CAPACITY(528, "ORDER_CAPACITY", "OrderCapacity"),
    ORDER_RESTRICTIONS(529, "ORDER_RESTRICTIONS", "OrderRestrictions"),
    MASS_CANCEL_REQUEST_TYPE(530, "MASS_CANCEL_REQUEST_TYPE", "MassCancelRequestType"),

    MASS_CANCEL_RESPONSE(531, "MASS_CANCEL_RESPONSE", "MassCancelResponse"),
    MASS_CANCEL_REJECT_REASON(532, "MASS_CANCEL_REJECT_REASON", "MassCancelRejectReason"),
    TOTAL_AFFECTED_ORDERS(533, "TOTAL_AFFECTED_ORDERS", "TotalAffectedOrders"),
    NO_AFFECTED_ORDERS(534, "NO_AFFECTED_ORDERS", "NoAffectedOrders"),
    AFFECTED_ORDER_ID(535, "AFFECTED_ORDER_ID", "AffectedOrderID"),
    AFFECTED_SECONDARY_ORDER_ID(536, "AFFECTED_SECONDARY_ORDER_ID", "AffectedSecondaryOrderID"),
    QUOTE_TYPE(537, "QUOTE_TYPE", "QuoteType"),
    NESTED_PARTY_ROLE(538, "NESTED_PARTY_ROLE", "NestedPartyRole"),
    NO_NESTED_PARTY_IDS(539, "NO_NESTED_PARTY_IDS", "NoNestedPartyIDs"),
    TOTAL_ACCRUED_INTEREST_AMT(540, "TOTAL_ACCRUED_INTEREST_AMT", "TotalAccruedInterestAmt (Deprecated)"),

    MATURITY_DATE(541, "MATURITY_DATE", "MaturityDate"),
    UNDERLYING_MATURITY_DATE(542, "UNDERLYING_MATURITY_DATE", "UnderlyingMaturityDate"),
    INSTR_REGISTRY(543, "INSTR_REGISTRY", "InstrRegistry"),
    CASH_MARGIN(544, "CASH_MARGIN", "CashMargin"),
    NESTED_PARTY_SUB_ID(545, "NESTED_PARTY_SUB_ID", "NestedPartySubID"),
    SCOPE(546, "SCOPE", "Scope"),
    MD_IMPLICIT_DELETE(547, "MD_IMPLICIT_DELETE", "MDImplicitDelete"),
    CROSS_ID(548, "CROSS_ID", "CrossID"),
    CROSS_TYPE(549, "CROSS_TYPE", "CrossType"),
    CROSS_PRIORITIZATION(550, "CROSS_PRIORITIZATION", "CrossPrioritization"),

    ORIG_CROSS_ID(551, "ORIG_CROSS_ID", "OrigCrossID"),
    NO_SIDES(552, "NO_SIDES", "NoSides"),
    FIX553_USERNAME(553, "USERNAME", "Username"),
    FIX554_PASSWORD(554, "PASSWORD", "Password"),
    NO_LEGS(555, "NO_LEGS", "NoLegs"),
    LEG_CURRENCY(556, "LEG_CURRENCY", "LegCurrency"),
    TOT_NO_SECURITY_TYPES(557, "TOT_NO_SECURITY_TYPES", "TotNoSecurityTypes"),
    NO_SECURITY_TYPES(558, "NO_SECURITY_TYPES", "NoSecurityTypes"),
    SECURITY_LIST_REQUEST_TYPE(559, "SECURITY_LIST_REQUEST_TYPE", "SecurityListRequestType"),
    SECURITY_REQUEST_RESULT(560, "SECURITY_REQUEST_RESULT", "SecurityRequestResult"),

    ROUND_LOT(561, "ROUND_LOT", "RoundLot"),
    MIN_TRADE_VOL(562, "MIN_TRADE_VOL", "MinTradeVol"),
    MULTI_LEG_RPT_TYPE_REQ(563, "MULTI_LEG_RPT_TYPE_REQ", "MultiLegRptTypeReq"),
    LEG_POSITION_EFFECT(564, "LEG_POSITION_EFFECT", "LegPositionEffect"),
    LEG_COVERED_OR_UNCOVERED(565, "LEG_COVERED_OR_UNCOVERED", "LegCoveredOrUncovered"),
    LEG_PRICE(566, "LEG_PRICE", "LegPrice"),
    TRAD_SES_STATUS_REJ_REASON(567, "TRAD_SES_STATUS_REJ_REASON", "TradSesStatusRejReason"),
    TRADE_REQUEST_ID(568, "TRADE_REQUEST_ID", "TradeRequestID"),
    TRADE_REQUEST_TYPE(569, "TRADE_REQUEST_TYPE", "TradeRequestType"),
    PREVIOUSLY_REPORTED(570, "PREVIOUSLY_REPORTED", "PreviouslyReported"),

    TRADE_REPORT_ID(571, "TRADE_REPORT_ID", "TradeReportID"),
    TRADE_REPORT_REF_ID(572, "TRADE_REPORT_REF_ID", "TradeReportRefID"),
    MATCH_STATUS(573, "MATCH_STATUS", "MatchStatus"),
    MATCH_TYPE(574, "MATCH_TYPE", "MatchType"),
    ODD_LOT(575, "ODD_LOT", "OddLot"),
    NO_CLEARING_INSTRUCTIONS(576, "NO_CLEARING_INSTRUCTIONS", "NoClearingInstructions"),
    CLEARING_INSTRUCTION(577, "CLEARING_INSTRUCTION", "ClearingInstruction"),
    TRADE_INPUT_SOURCE(578, "TRADE_INPUT_SOURCE", "TradeInputSource"),
    TRADE_INPUT_DEVICE(579, "TRADE_INPUT_DEVICE", "TradeInputDevice"),
    NO_DATES(580, "NO_DATES", "NoDates"),

    ACCOUNT_TYPE(581, "ACCOUNT_TYPE", "AccountType"),
    CUST_ORDER_CAPACITY(582, "CUST_ORDER_CAPACITY", "CustOrderCapacity"),
    CL_ORD_LINK_ID(583, "CL_ORD_LINK_ID", "ClOrdLinkID"),
    MASS_STATUS_REQ_ID(584, "MASS_STATUS_REQ_ID", "MassStatusReqID"),
    MASS_STATUS_REQ_TYPE(585, "MASS_STATUS_REQ_TYPE", "MassStatusReqType"),
    ORIG_ORD_MOD_TIME(586, "ORIG_ORD_MOD_TIME", "OrigOrdModTime"),
    LEG_SETTL_TYPE(587, "LEG_SETTL_TYPE", "LegSettlType (formerly named LegSettlmntTyp prior to FIX 4.4)"),
    LEG_SETTL_DATE(588, "LEG_SETTL_DATE", "LegSettlDate (formerly named LegFutSettlDate prior to FIX 4.4)"),
    DAY_BOOKING_INST(589, "DAY_BOOKING_INST", "DayBookingInst"),
    BOOKING_UNIT(590, "BOOKING_UNIT", "BookingUnit"),

    PREALLOC_METHOD(591, "PREALLOC_METHOD", "PreallocMethod"),
    UNDERLYING_COUNTRY_OF_ISSUE(592, "UNDERLYING_COUNTRY_OF_ISSUE", "UnderlyingCountryOfIssue"),
    UNDERLYING_STATE_OR_PROVINCE_OF_ISSUE(593, "UNDERLYING_STATE_OR_PROVINCE_OF_ISSUE", "UnderlyingStateOrProvinceOfIssue"),
    UNDERLYING_LOCALE_OF_ISSUE(594, "UNDERLYING_LOCALE_OF_ISSUE", "UnderlyingLocaleOfIssue"),
    UNDERLYING_INSTR_REGISTRY(595, "UNDERLYING_INSTR_REGISTRY", "UnderlyingInstrRegistry"),
    LEG_COUNTRY_OF_ISSUE(596, "LEG_COUNTRY_OF_ISSUE", "LegCountryOfIssue"),
    LEG_STATE_OR_PROVINCE_OF_ISSUE(597, "LEG_STATE_OR_PROVINCE_OF_ISSUE", "LegStateOrProvinceOfIssue"),
    LEG_LOCALE_OF_ISSUE(598, "LEG_LOCALE_OF_ISSUE", "LegLocaleOfIssue"),
    LEG_INSTR_REGISTRY(599, "LEG_INSTR_REGISTRY", "LegInstrRegistry"),
    LEG_SYMBOL(600, "LEG_SYMBOL", "LegSymbol"),


    // 601-700

    LEG_SYMBOL_SFX(601, "LEG_SYMBOL_SFX", "LegSymbolSfx"),
    LEG_SECURITY_ID(602, "LEG_SECURITY_ID", "LegSecurityID"),
    LEG_SECURITY_ID_SOURCE(603, "LEG_SECURITY_ID_SOURCE", "LegSecurityIDSource"),
    NO_LEG_SECURITY_ALT_ID(604, "NO_LEG_SECURITY_ALT_ID", "NoLegSecurityAltID"),
    LEG_SECURITY_ALT_ID(605, "LEG_SECURITY_ALT_ID", "LegSecurityAltID"),
    LEG_SECURITY_ALT_ID_SOURCE(606, "LEG_SECURITY_ALT_ID_SOURCE", "LegSecurityAltIDSource"),
    LEG_PRODUCT(607, "LEG_PRODUCT", "LegProduct"),
    LEG_CFI_CODE(608, "LEG_CFI_CODE", "LegCFICode"),
    LEG_SECURITY_TYPE(609, "LEG_SECURITY_TYPE", "LegSecurityType"),
    LEG_MATURITY_MONTH_YEAR(610, "LEG_MATURITY_MONTH_YEAR", "LegMaturityMonthYear"),

    LEG_MATURITY_DATE(611, "LEG_MATURITY_DATE", "LegMaturityDate"),
    LEG_STRIKE_PRICE(612, "LEG_STRIKE_PRICE", "LegStrikePrice"),
    LEG_OPT_ATTRIBUTE(613, "LEG_OPT_ATTRIBUTE", "LegOptAttribute"),
    LEG_CONTRACT_MULTIPLIER(614, "LEG_CONTRACT_MULTIPLIER", "LegContractMultiplier"),
    LEG_COUPON_RATE(615, "LEG_COUPON_RATE", "LegCouponRate"),
    LEG_SECURITY_EXCHANGE(616, "LEG_SECURITY_EXCHANGE", "LegSecurityExchange"),
    LEG_ISSUER(617, "LEG_ISSUER", "LegIssuer"),
    ENCODED_LEG_ISSUER_LEN(618, "ENCODED_LEG_ISSUER_LEN", "EncodedLegIssuerLen"),
    ENCODED_LEG_ISSUER(619, "ENCODED_LEG_ISSUER", "EncodedLegIssuer"),
    LEG_SECURITY_DESC(620, "LEG_SECURITY_DESC", "LegSecurityDesc"),

    ENCODED_LEG_SECURITY_DESC_LEN(621, "ENCODED_LEG_SECURITY_DESC_LEN", "EncodedLegSecurityDescLen"),
    ENCODED_LEG_SECURITY_DESC(622, "ENCODED_LEG_SECURITY_DESC", "EncodedLegSecurityDesc"),
    LEG_RATIO_QTY(623, "LEG_RATIO_QTY", "LegRatioQty"),
    LEG_SIDE(624, "LEG_SIDE", "LegSide"),
    TRADING_SESSION_SUB_ID(625, "TRADING_SESSION_SUB_ID", "TradingSessionSubID"),
    ALLOC_TYPE(626, "ALLOC_TYPE", "AllocType"),
    NO_HOPS(627, "NO_HOPS", "NoHops"),
    HOP_COMP_ID(628, "HOP_COMP_ID", "HopCompID"),
    HOP_SENDING_TIME(629, "HOP_SENDING_TIME", "HopSendingTime"),
    HOP_REF_ID(630, "HOP_REF_ID", "HopRefID"),

    MID_PX(631, "MID_PX", "MidPx"),
    BID_YIELD(632, "BID_YIELD", "BidYield"),
    MID_YIELD(633, "MID_YIELD", "MidYield"),
    OFFER_YIELD(634, "OFFER_YIELD", "OfferYield"),
    CLEARING_FEE_INDICATOR(635, "CLEARING_FEE_INDICATOR", "ClearingFeeIndicator"),
    WORKING_INDICATOR(636, "WORKING_INDICATOR", "WorkingIndicator"),
    LEG_LAST_PX(637, "LEG_LAST_PX", "LegLastPx"),
    PRIORITY_INDICATOR(638, "PRIORITY_INDICATOR", "PriorityIndicator"),
    PRICE_IMPROVEMENT(639, "PRICE_IMPROVEMENT", "PriceImprovement"),
    PRICE_2(640, "PRICE_2", "Price2"),

    LAST_FORWARD_POINTS_2(641, "LAST_FORWARD_POINTS_2", "LastForwardPoints2"),
    BID_FORWARD_POINTS_2(642, "BID_FORWARD_POINTS_2", "BidForwardPoints2"),
    OFFER_FORWARD_POINTS_2(643, "OFFER_FORWARD_POINTS_2", "OfferForwardPoints2"),
    RFQ_REQ_ID(644, "RFQ_REQ_ID", "RFQReqID"),
    MKT_BID_PX(645, "MKT_BID_PX", "MktBidPx"),
    MKT_OFFER_PX(646, "MKT_OFFER_PX", "MktOfferPx"),
    MIN_BID_SIZE(647, "MIN_BID_SIZE", "MinBidSize"),
    MIN_OFFER_SIZE(648, "MIN_OFFER_SIZE", "MinOfferSize"),
    QUOTE_STATUS_REQ_ID(649, "QUOTE_STATUS_REQ_ID", "QuoteStatusReqID"),
    LEGAL_CONFIRM(650, "LEGAL_CONFIRM", "LegalConfirm"),

    UNDERLYING_LAST_PX(651, "UNDERLYING_LAST_PX", "UnderlyingLastPx"),
    UNDERLYING_LAST_QTY(652, "UNDERLYING_LAST_QTY", "UnderlyingLastQty"),
    SEC_DEF_STATUS(653, "SEC_DEF_STATUS", "SecDefStatus (replaced)"),
    LEG_REF_ID(654, "LEG_REF_ID", "LegRefID"),
    CONTRA_LEG_REF_ID(655, "CONTRA_LEG_REF_ID", "ContraLegRefID"),
    SETTL_CURR_BID_FX_RATE(656, "SETTL_CURR_BID_FX_RATE", "SettlCurrBidFxRate"),
    SETTL_CURR_OFFER_FX_RATE(657, "SETTL_CURR_OFFER_FX_RATE", "SettlCurrOfferFxRate"),
    QUOTE_REQUEST_REJECT_REASON(658, "QUOTE_REQUEST_REJECT_REASON", "QuoteRequestRejectReason"),
    SIDE_COMPLIANCE_ID(659, "SIDE_COMPLIANCE_ID", "SideComplianceID"),
    /*
     *
     * End of FIX4.3
     *
     */


    /*
     * Start of FIX4.4 as defined by the FIX Protocol Specification 4.4
     *  Tags: 660-956
     */
// TODO: add FIXnnn_ prefix to FIX4.4
    ACCT_ID_SOURCE(660, "ACCT_ID_SOURCE", "AcctIDSource"),

    ALLOC_ACCT_ID_SOURCE(661, "ALLOC_ACCT_ID_SOURCE", "AllocAcctIDSource"),
    BENCHMARK_PRICE(662, "BENCHMARK_PRICE", "BenchmarkPrice"),
    BENCHMARK_PRICE_TYPE(663, "BENCHMARK_PRICE_TYPE", "BenchmarkPriceType"),
    CONFIRM_ID(664, "CONFIRM_ID", "ConfirmID"),
    CONFIRM_STATUS(665, "CONFIRM_STATUS", "ConfirmStatus"),
    CONFIRM_TRANS_TYPE(666, "CONFIRM_TRANS_TYPE", "ConfirmTransType"),
    CONTRACT_SETTL_MONTH(667, "CONTRACT_SETTL_MONTH", "ContractSettlMonth"),
    DELIVERY_FORM(668, "DELIVERY_FORM", "DeliveryForm"),
    LAST_PAR_PX(669, "LAST_PAR_PX", "LastParPx"),
    NO_LEG_ALLOCS(670, "NO_LEG_ALLOCS", "NoLegAllocs"),

    LEG_ALLOC_ACCOUNT(671, "LEG_ALLOC_ACCOUNT", "LegAllocAccount"),
    LEG_INDIVIDUAL_ALLOC_ID(672, "LEG_INDIVIDUAL_ALLOC_ID", "LegIndividualAllocID"),
    LEG_ALLOC_QTY(673, "LEG_ALLOC_QTY", "LegAllocQty"),
    LEG_ALLOC_ACCT_ID_SOURCE(674, "LEG_ALLOC_ACCT_ID_SOURCE", "LegAllocAcctIDSource"),
    LEG_SETTL_CURRENCY(675, "LEG_SETTL_CURRENCY", "LegSettlCurrency"),
    LEG_BENCHMARK_CURVE_CURRENCY(676, "LEG_BENCHMARK_CURVE_CURRENCY", "LegBenchmarkCurveCurrency"),
    LEG_BENCHMARK_CURVE_NAME(677, "LEG_BENCHMARK_CURVE_NAME", "LegBenchmarkCurveName"),
    LEG_BENCHMARK_CURVE_POINT(678, "LEG_BENCHMARK_CURVE_POINT", "LegBenchmarkCurvePoint"),
    LEG_BENCHMARK_PRICE(679, "LEG_BENCHMARK_PRICE", "LegBenchmarkPrice"),
    LEG_BENCHMARK_PRICE_TYPE(680, "LEG_BENCHMARK_PRICE_TYPE", "LegBenchmarkPriceType"),

    LEG_BID_PX(681, "LEG_BID_PX", "LegBidPx"),
    LEG_IOI_QTY(682, "LEG_IOI_QTY", "LegIOIQty"),
    NO_LEG_STIPULATIONS(683, "NO_LEG_STIPULATIONS", "NoLegStipulations"),
    LEG_OFFER_PX(684, "LEG_OFFER_PX", "LegOfferPx"),
    LEG_ORDER_QTY(685, "LEG_ORDER_QTY", "LegOrderQty"),
    LEG_PRICE_TYPE(686, "LEG_PRICE_TYPE", "LegPriceType"),
    LEG_QTY(687, "LEG_QTY", "LegQty"),
    LEG_STIPULATION_TYPE(688, "LEG_STIPULATION_TYPE", "LegStipulationType"),
    LEG_STIPULATION_VALUE(689, "LEG_STIPULATION_VALUE", "LegStipulationValue"),
    LEG_SWAP_TYPE(690, "LEG_SWAP_TYPE", "LegSwapType"),

    POOL(691, "POOL", "Pool"),
    QUOTE_PRICE_TYPE(692, "QUOTE_PRICE_TYPE", "QuotePriceType"),
    QUOTE_RESP_ID(693, "QUOTE_RESP_ID", "QuoteRespID"),
    QUOTE_RESP_TYPE(694, "QUOTE_RESP_TYPE", "QuoteRespType"),
    QUOTE_QUALIFIER(695, "QUOTE_QUALIFIER", "QuoteQualifier"),
    YIELD_REDEMPTION_DATE(696, "YIELD_REDEMPTION_DATE", "YieldRedemptionDate"),
    YIELD_REDEMPTION_PRICE(697, "YIELD_REDEMPTION_PRICE", "YieldRedemptionPrice"),
    YIELD_REDEMPTION_PRICE_TYPE(698, "YIELD_REDEMPTION_PRICE_TYPE", "YieldRedemptionPriceType"),
    BENCHMARK_SECURITY_ID(699, "BENCHMARK_SECURITY_ID", "BenchmarkSecurityID"),
    REVERSAL_INDICATOR(700, "REVERSAL_INDICATOR", "ReversalIndicator"),


    // 701-800

    YIELD_CALC_DATE(701, "YIELD_CALC_DATE", "YieldCalcDate"),
    NO_POSITIONS(702, "NO_POSITIONS", "NoPositions"),
    POS_TYPE(703, "POS_TYPE", "PosType"),
    LONG_QTY(704, "LONG_QTY", "LongQty"),
    SHORT_QTY(705, "SHORT_QTY", "ShortQty"),
    POS_QTY_STATUS(706, "POS_QTY_STATUS", "PosQtyStatus"),
    POS_AMT_TYPE(707, "POS_AMT_TYPE", "PosAmtType"),
    POS_AMT(708, "POS_AMT", "PosAmt"),
    POS_TRANS_TYPE(709, "POS_TRANS_TYPE", "PosTransType"),
    POS_REQ_ID(710, "POS_REQ_ID", "PosReqID"),

    NO_UNDERLYINGS(711, "NO_UNDERLYINGS", "NoUnderlyings"),
    POS_MAINT_ACTION(712, "POS_MAINT_ACTION", "PosMaintAction"),
    ORIG_POS_REQ_REF_ID(713, "ORIG_POS_REQ_REF_ID", "OrigPosReqRefID"),
    POS_MAINT_RPT_REF_ID(714, "POS_MAINT_RPT_REF_ID", "PosMaintRptRefID"),
    CLEARING_BUSINESS_DATE(715, "CLEARING_BUSINESS_DATE", "ClearingBusinessDate"),
    SETTL_SESS_ID(716, "SETTL_SESS_ID", "SettlSessID"),
    SETTL_SESS_SUB_ID(717, "SETTL_SESS_SUB_ID", "SettlSessSubID"),
    ADJUSTMENT_TYPE(718, "ADJUSTMENT_TYPE", "AdjustmentType"),
    CONTRARY_INSTRUCTION_INDICATOR(719, "CONTRARY_INSTRUCTION_INDICATOR", "ContraryInstructionIndicator"),
    PRIOR_SPREAD_INDICATOR(720, "PRIOR_SPREAD_INDICATOR", "PriorSpreadIndicator"),

    POS_MAINT_RPT_ID(721, "POS_MAINT_RPT_ID", "PosMaintRptID"),
    POS_MAINT_STATUS(722, "POS_MAINT_STATUS", "PosMaintStatus"),
    POS_MAINT_RESULT(723, "POS_MAINT_RESULT", "PosMaintResult"),
    POS_REQ_TYPE(724, "POS_REQ_TYPE", "PosReqType"),
    RESPONSE_TRANSPORT_TYPE(725, "RESPONSE_TRANSPORT_TYPE", "ResponseTransportType"),
    RESPONSE_DESTINATION(726, "RESPONSE_DESTINATION", "ResponseDestination"),
    TOTAL_NUM_POS_REPORTS(727, "TOTAL_NUM_POS_REPORTS", "TotalNumPosReports"),
    POS_REQ_RESULT(728, "POS_REQ_RESULT", "PosReqResult"),
    POS_REQ_STATUS(729, "POS_REQ_STATUS", "PosReqStatus"),
    SETTL_PRICE(730, "SETTL_PRICE", "SettlPrice"),

    SETTL_PRICE_TYPE(731, "SETTL_PRICE_TYPE", "SettlPriceType"),
    UNDERLYING_SETTL_PRICE(732, "UNDERLYING_SETTL_PRICE", "UnderlyingSettlPrice"),
    UNDERLYING_SETTL_PRICE_TYPE(733, "UNDERLYING_SETTL_PRICE_TYPE", "UnderlyingSettlPriceType"),
    PRIOR_SETTL_PRICE(734, "PRIOR_SETTL_PRICE", "PriorSettlPrice"),
    NO_QUOTE_QUALIFIERS(735, "NO_QUOTE_QUALIFIERS", "NoQuoteQualifiers"),
    ALLOC_SETTL_CURRENCY(736, "ALLOC_SETTL_CURRENCY", "AllocSettlCurrency"),
    ALLOC_SETTL_CURR_AMT(737, "ALLOC_SETTL_CURR_AMT", "AllocSettlCurrAmt"),
    INTEREST_AT_MATURITY(738, "INTEREST_AT_MATURITY", "InterestAtMaturity"),
    LEG_DATED_DATE(739, "LEG_DATED_DATE", "LegDatedDate"),
    LEG_POOL(740, "LEG_POOL", "LegPool"),

    ALLOC_INTEREST_AT_MATURITY(741, "ALLOC_INTEREST_AT_MATURITY", "AllocInterestAtMaturity"),
    ALLOC_ACCRUED_INTEREST_AMT(742, "ALLOC_ACCRUED_INTEREST_AMT", "AllocAccruedInterestAmt"),
    DELIVERY_DATE(743, "DELIVERY_DATE", "DeliveryDate"),
    ASSIGNMENT_METHOD(744, "ASSIGNMENT_METHOD", "AssignmentMethod"),
    ASSIGNMENT_UNIT(745, "ASSIGNMENT_UNIT", "AssignmentUnit"),
    OPEN_INTEREST(746, "OPEN_INTEREST", "OpenInterest"),
    EXERCISE_METHOD(747, "EXERCISE_METHOD", "ExerciseMethod"),
    TOT_NUM_TRADE_REPORTS(748, "TOT_NUM_TRADE_REPORTS", "TotNumTradeReports"),
    TRADE_REQUEST_RESULT(749, "TRADE_REQUEST_RESULT", "TradeRequestResult"),
    TRADE_REQUEST_STATUS(750, "TRADE_REQUEST_STATUS", "TradeRequestStatus"),

    TRADE_REPORT_REJECT_REASON(751, "TRADE_REPORT_REJECT_REASON", "TradeReportRejectReason"),
    SIDE_MULTI_LEG_REPORTING_TYPE(752, "SIDE_MULTI_LEG_REPORTING_TYPE", "SideMultiLegReportingType"),
    NO_POS_AMT(753, "NO_POS_AMT", "NoPosAmt"),
    AUTO_ACCEPT_INDICATOR(754, "AUTO_ACCEPT_INDICATOR", "AutoAcceptIndicator"),
    ALLOC_REPORT_ID(755, "ALLOC_REPORT_ID", "AllocReportID"),
    NO_NESTED_2_PARTY_IDS(756, "NO_NESTED_2_PARTY_IDS", "NoNested2PartyIDs"),
    NESTED_2_PARTY_ID(757, "NESTED_2_PARTY_ID", "Nested2PartyID"),
    NESTED_2_PARTY_ID_SOURCE(758, "NESTED_2_PARTY_ID_SOURCE", "Nested2PartyIDSource"),
    NESTED_2_PARTY_ROLE(759, "NESTED_2_PARTY_ROLE", "Nested2PartyRole"),
    NESTED_2_PARTY_SUB_ID(760, "NESTED_2_PARTY_SUB_ID", "Nested2PartySubID"),

    BENCHMARK_SECURITY_ID_SOURCE(761, "BENCHMARK_SECURITY_ID_SOURCE", "BenchmarkSecurityIDSource"),
    SECURITY_SUB_TYPE(762, "SECURITY_SUB_TYPE", "SecuritySubType"),
    UNDERLYING_SECURITY_SUB_TYPE(763, "UNDERLYING_SECURITY_SUB_TYPE", "UnderlyingSecuritySubType"),
    LEG_SECURITY_SUB_TYPE(764, "LEG_SECURITY_SUB_TYPE", "LegSecuritySubType"),
    ALLOWABLE_ONE_SIDEDNESS_PCT(765, "ALLOWABLE_ONE_SIDEDNESS_PCT", "AllowableOneSidednessPct"),
    ALLOWABLE_ONE_SIDEDNESS_VALUE(766, "ALLOWABLE_ONE_SIDEDNESS_VALUE", "AllowableOneSidednessValue"),
    ALLOWABLE_ONE_SIDEDNESS_CURR(767, "ALLOWABLE_ONE_SIDEDNESS_CURR", "AllowableOneSidednessCurr"),
    NO_TRD_REG_TIMESTAMPS(768, "NO_TRD_REG_TIMESTAMPS", "NoTrdRegTimestamps"),
    TRD_REG_TIMESTAMP(769, "TRD_REG_TIMESTAMP", "TrdRegTimestamp"),
    TRD_REG_TIMESTAMP_TYPE(770, "TRD_REG_TIMESTAMP_TYPE", "TrdRegTimestampType"),

    TRD_REG_TIMESTAMP_ORIGIN(771, "TRD_REG_TIMESTAMP_ORIGIN", "TrdRegTimestampOrigin"),
    CONFIRM_REF_ID(772, "CONFIRM_REF_ID", "ConfirmRefID"),
    CONFIRM_TYPE(773, "CONFIRM_TYPE", "ConfirmType"),
    CONFIRM_REJ_REASON(774, "CONFIRM_REJ_REASON", "ConfirmRejReason"),
    BOOKING_TYPE(775, "BOOKING_TYPE", "BookingType"),
    INDIVIDUAL_ALLOC_REJ_CODE(776, "INDIVIDUAL_ALLOC_REJ_CODE", "IndividualAllocRejCode"),
    SETTL_INST_MSG_ID(777, "SETTL_INST_MSG_ID", "SettlInstMsgID"),
    NO_SETTL_INST(778, "NO_SETTL_INST", "NoSettlInst"),
    LAST_UPDATE_TIME(779, "LAST_UPDATE_TIME", "LastUpdateTime"),
    ALLOC_SETTL_INST_TYPE(780, "ALLOC_SETTL_INST_TYPE", "AllocSettlInstType"),

    NO_SETTL_PARTY_IDS(781, "NO_SETTL_PARTY_IDS", "NoSettlPartyIDs"),
    SETTL_PARTY_ID(782, "SETTL_PARTY_ID", "SettlPartyID"),
    SETTL_PARTY_ID_SOURCE(783, "SETTL_PARTY_ID_SOURCE", "SettlPartyIDSource"),
    SETTL_PARTY_ROLE(784, "SETTL_PARTY_ROLE", "SettlPartyRole"),
    SETTL_PARTY_SUB_ID(785, "SETTL_PARTY_SUB_ID", "SettlPartySubID"),
    SETTL_PARTY_SUB_ID_TYPE(786, "SETTL_PARTY_SUB_ID_TYPE", "SettlPartySubIDType"),
    DLVY_INST_TYPE(787, "DLVY_INST_TYPE", "DlvyInstType"),
    TERMINATION_TYPE(788, "TERMINATION_TYPE", "TerminationType"),
    NEXT_EXPECTED_MSG_SEQ_NUM(789, "NEXT_EXPECTED_MSG_SEQ_NUM", "NextExpectedMsgSeqNum"),
    ORD_STATUS_REQ_ID(790, "ORD_STATUS_REQ_ID", "OrdStatusReqID"),

    SETTL_INST_REQ_ID(791, "SETTL_INST_REQ_ID", "SettlInstReqID"),
    SETTL_INST_REQ_REJ_CODE(792, "SETTL_INST_REQ_REJ_CODE", "SettlInstReqRejCode"),
    SECONDARY_ALLOC_ID(793, "SECONDARY_ALLOC_ID", "SecondaryAllocID"),
    ALLOC_REPORT_TYPE(794, "ALLOC_REPORT_TYPE", "AllocReportType"),
    ALLOC_REPORT_REF_ID(795, "ALLOC_REPORT_REF_ID", "AllocReportRefID"),
    ALLOC_CANC_REPLACE_REASON(796, "ALLOC_CANC_REPLACE_REASON", "AllocCancReplaceReason"),
    COPY_MSG_INDICATOR(797, "COPY_MSG_INDICATOR", "CopyMsgIndicator"),
    ALLOC_ACCOUNT_TYPE(798, "ALLOC_ACCOUNT_TYPE", "AllocAccountType"),
    ORDER_AVG_PX(799, "ORDER_AVG_PX", "OrderAvgPx"),
    ORDER_BOOKING_QTY(800, "ORDER_BOOKING_QTY", "OrderBookingQty"),


    // 801-900

    NO_SETTL_PARTY_SUB_IDS(801, "NO_SETTL_PARTY_SUB_IDS", "NoSettlPartySubIDs"),
    NO_PARTY_SUB_IDS(802, "NO_PARTY_SUB_IDS", "NoPartySubIDs"),
    PARTY_SUB_ID_TYPE(803, "PARTY_SUB_ID_TYPE", "PartySubIDType"),
    NO_NESTED_PARTY_SUB_IDS(804, "NO_NESTED_PARTY_SUB_IDS", "NoNestedPartySubIDs"),
    NESTED_PARTY_SUB_ID_TYPE(805, "NESTED_PARTY_SUB_ID_TYPE", "NestedPartySubIDType"),
    NO_NESTED_2_PARTY_SUB_IDS(806, "NO_NESTED_2_PARTY_SUB_IDS", "NoNested2PartySubIDs"),
    NESTED_2_PARTY_SUB_ID_TYPE(807, "NESTED_2_PARTY_SUB_ID_TYPE", "Nested2PartySubIDType"),
    ALLOC_INTERMED_REQ_TYPE(808, "ALLOC_INTERMED_REQ_TYPE", "AllocIntermedReqType"),
    UNDERLYING_PX(810, "UNDERLYING_PX", "UnderlyingPx"),

    PRICE_DELTA(811, "PRICE_DELTA", "PriceDelta"),
    APPL_QUEUE_MAX(812, "APPL_QUEUE_MAX", "ApplQueueMax"),
    APPL_QUEUE_DEPTH(813, "APPL_QUEUE_DEPTH", "ApplQueueDepth"),
    APPL_QUEUE_RESOLUTION(814, "APPL_QUEUE_RESOLUTION", "ApplQueueResolution"),
    APPL_QUEUE_ACTION(815, "APPL_QUEUE_ACTION", "ApplQueueAction"),
    NO_ALT_MD_SOURCE(816, "NO_ALT_MD_SOURCE", "NoAltMDSource"),
    ALT_MD_SOURCE_ID(817, "ALT_MD_SOURCE_ID", "AltMDSourceID"),
    SECONDARY_TRADE_REPORT_ID(818, "SECONDARY_TRADE_REPORT_ID", "SecondaryTradeReportID"),
    AVG_PX_INDICATOR(819, "AVG_PX_INDICATOR", "AvgPxIndicator"),
    TRADE_LINK_ID(820, "TRADE_LINK_ID", "TradeLinkID"),

    ORDER_INPUT_DEVICE(821, "ORDER_INPUT_DEVICE", "OrderInputDevice"),
    UNDERLYING_TRADING_SESSION_ID(822, "UNDERLYING_TRADING_SESSION_ID", "UnderlyingTradingSessionID"),
    UNDERLYING_TRADING_SESSION_SUB_ID(823, "UNDERLYING_TRADING_SESSION_SUB_ID", "UnderlyingTradingSessionSubID"),
    TRADE_LEG_REF_ID(824, "TRADE_LEG_REF_ID", "TradeLegRefID"),
    EXCHANGE_RULE(825, "EXCHANGE_RULE", "ExchangeRule"),
    TRADE_ALLOC_INDICATOR(826, "TRADE_ALLOC_INDICATOR", "TradeAllocIndicator"),
    EXPIRATION_CYCLE(827, "EXPIRATION_CYCLE", "ExpirationCycle"),
    TRD_TYPE(828, "TRD_TYPE", "TrdType"),
    TRD_SUB_TYPE(829, "TRD_SUB_TYPE", "TrdSubType"),
    TRANSFER_REASON(830, "TRANSFER_REASON", "TransferReason"),

    ASGN_REQ_ID(831, "ASGN_REQ_ID", "AsgnReqID"),
    TOT_NUM_ASSIGNMENT_REPORTS(832, "TOT_NUM_ASSIGNMENT_REPORTS", "TotNumAssignmentReports"),
    ASGN_RPT_ID(833, "ASGN_RPT_ID", "AsgnRptID"),
    THRESHOLD_AMOUNT(834, "THRESHOLD_AMOUNT", "ThresholdAmount"),
    PEG_MOVE_TYPE(835, "PEG_MOVE_TYPE", "PegMoveType"),
    PEG_OFFSET_TYPE(836, "PEG_OFFSET_TYPE", "PegOffsetType"),
    PEG_LIMIT_TYPE(837, "PEG_LIMIT_TYPE", "PegLimitType"),
    PEG_ROUND_DIRECTION(838, "PEG_ROUND_DIRECTION", "PegRoundDirection"),
    PEGGED_PRICE(839, "PEGGED_PRICE", "PeggedPrice"),
    PEG_SCOPE(840, "PEG_SCOPE", "PegScope"),

    DISCRETION_MOVE_TYPE(841, "DISCRETION_MOVE_TYPE", "DiscretionMoveType"),
    DISCRETION_OFFSET_TYPE(842, "DISCRETION_OFFSET_TYPE", "DiscretionOffsetType"),
    DISCRETION_LIMIT_TYPE(843, "DISCRETION_LIMIT_TYPE", "DiscretionLimitType"),
    DISCRETION_ROUND_DIRECTION(844, "DISCRETION_ROUND_DIRECTION", "DiscretionRoundDirection"),
    DISCRETION_PRICE(845, "DISCRETION_PRICE", "DiscretionPrice"),
    DISCRETION_SCOPE(846, "DISCRETION_SCOPE", "DiscretionScope"),
    TARGET_STRATEGY(847, "TARGET_STRATEGY", "TargetStrategy"),
    TARGET_STRATEGY_PARAMETERS(848, "TARGET_STRATEGY_PARAMETERS", "TargetStrategyParameters"),
    PARTICIPATION_RATE(849, "PARTICIPATION_RATE", "ParticipationRate"),
    TARGET_STRATEGY_PERFORMANCE(850, "TARGET_STRATEGY_PERFORMANCE", "TargetStrategyPerformance"),

    LAST_LIQUIDITY_IND(851, "LAST_LIQUIDITY_IND", "LastLiquidityInd"),
    PUBLISH_TRD_INDICATOR(852, "PUBLISH_TRD_INDICATOR", "PublishTrdIndicator"),
    SHORT_SALE_REASON(853, "SHORT_SALE_REASON", "ShortSaleReason"),
    QTY_TYPE(854, "QTY_TYPE", "QtyType"),
    SECONDARY_TRD_TYPE(855, "SECONDARY_TRD_TYPE", "SecondaryTrdType"),
    TRADE_REPORT_TYPE(856, "TRADE_REPORT_TYPE", "TradeReportType"),
    ALLOC_NO_ORDERS_TYPE(857, "ALLOC_NO_ORDERS_TYPE", "AllocNoOrdersType"),
    SHARED_COMMISSION(858, "SHARED_COMMISSION", "SharedCommission"),
    CONFIRM_REQ_ID(859, "CONFIRM_REQ_ID", "ConfirmReqID"),
    AVG_PAR_PX(860, "AVG_PAR_PX", "AvgParPx"),

    REPORTED_PX(861, "REPORTED_PX", "ReportedPx"),
    NO_CAPACITIES(862, "NO_CAPACITIES", "NoCapacities"),
    ORDER_CAPACITY_QTY(863, "ORDER_CAPACITY_QTY", "OrderCapacityQty"),
    NO_EVENTS(864, "NO_EVENTS", "NoEvents"),
    EVENT_TYPE(865, "EVENT_TYPE", "EventType"),
    EVENT_DATE(866, "EVENT_DATE", "EventDate"),
    EVENT_PX(867, "EVENT_PX", "EventPx"),
    EVENT_TEXT(868, "EVENT_TEXT", "EventText"),
    PCT_AT_RISK(869, "PCT_AT_RISK", "PctAtRisk"),
    NO_INSTR_ATTRIB(870, "NO_INSTR_ATTRIB", "NoInstrAttrib"),

    INSTR_ATTRIB_TYPE(871, "INSTR_ATTRIB_TYPE", "InstrAttribType"),
    INSTR_ATTRIB_VALUE(872, "INSTR_ATTRIB_VALUE", "InstrAttribValue"),
    DATED_DATE(873, "DATED_DATE", "DatedDate"),
    INTEREST_ACCRUAL_DATE(874, "INTEREST_ACCRUAL_DATE", "InterestAccrualDate"),
    CP_PROGRAM(875, "CP_PROGRAM", "CPProgram"),
    CP_REG_TYPE(876, "CP_REG_TYPE", "CPRegType"),
    UNDERLYING_CP_PROGRAM(877, "UNDERLYING_CP_PROGRAM", "UnderlyingCPProgram"),
    UNDERLYING_CP_REGTYPE(878, "UNDERLYING_CP_REGTYPE", "UnderlyingCPRegType"),
    UNDERLYING_QTY(879, "UNDERLYING_QTY", "UnderlyingQty"),
    TRD_MATCH_ID(880, "TRD_MATCH_ID", "TrdMatchID"),

    SECONDARY_TRADE_REPORT_REF_ID(881, "SECONDARY_TRADE_REPORT_REF_ID", "SecondaryTradeReportRefID"),
    UNDERLYING_DIRTY_PRICE(882, "UNDERLYING_DIRTY_PRICE", "UnderlyingDirtyPrice"),
    UNDERLYING_END_PRICE(883, "UNDERLYING_END_PRICE", "UnderlyingEndPrice"),
    UNDERLYING_START_VALUE(884, "UNDERLYING_START_VALUE", "UnderlyingStartValue"),
    UNDERLYING_CURRENT_VALUE(885, "UNDERLYING_CURRENT_VALUE", "UnderlyingCurrentValue"),
    UNDERLYING_END_VALUE(886, "UNDERLYING_END_VALUE", "UnderlyingEndValue"),
    NO_UNDERLYING_STIPS(887, "NO_UNDERLYING_STIPS", "NoUnderlyingStips"),
    UNDERLYING_STIP_TYPE(888, "UNDERLYING_STIP_TYPE", "UnderlyingStipType"),
    UNDERLYING_STIP_VALUE(889, "UNDERLYING_STIP_VALUE", "UnderlyingStipValue"),
    MATURITY_NET_MONEY(890, "MATURITY_NET_MONEY", "MaturityNetMoney"),

    MISC_FEE_BASIS(891, "MISC_FEE_BASIS", "MiscFeeBasis"),
    TOT_NO_ALLOCS(892, "TOT_NO_ALLOCS", "TotNoAllocs"),
    LAST_FRAGMENT(893, "LAST_FRAGMENT", "LastFragment"),
    COLL_REQ_ID(894, "COLL_REQ_ID", "CollReqID"),
    COLL_ASGN_REASON(895, "COLL_ASGN_REASON", "CollAsgnReason"),
    COLL_INQUIRY_QUALIFIER(896, "COLL_INQUIRY_QUALIFIER", "CollInquiryQualifier"),
    NO_TRADES(897, "NO_TRADES", "NoTrades"),
    MARGIN_RATIO(898, "MARGIN_RATIO", "MarginRatio"),
    MARGIN_EXCESS(899, "MARGIN_EXCESS", "MarginExcess"),
    TOTAL_NET_VALUE(900, "TOTAL_NET_VALUE", "TotalNetValue"),


    // 901-1000

    CASH_OUTSTANDING(901, "CASH_OUTSTANDING", "CashOutstanding"),
    COLL_ASGN_ID(902, "COLL_ASGN_ID", "CollAsgnID"),
    COLL_ASGN_TRANS_TYPE(903, "COLL_ASGN_TRANS_TYPE", "CollAsgnTransType"),
    COLL_RESP_ID(904, "COLL_RESP_ID", "CollRespID"),
    COLL_ASGN_RESP_TYPE(905, "COLL_ASGN_RESP_TYPE", "CollAsgnRespType"),
    COLL_ASGN_REJECT_REASON(906, "COLL_ASGN_REJECT_REASON", "CollAsgnRejectReason"),
    COLL_ASGN_REF_ID(907, "COLL_ASGN_REF_ID", "CollAsgnRefID"),
    COLL_RPT_ID(908, "COLL_RPT_ID", "CollRptID"),
    COLL_INQUIRY_ID(909, "COLL_INQUIRY_ID", "CollInquiryID"),
    COLL_STATUS(910, "COLL_STATUS", "CollStatus"),

    TOT_NUM_REPORTS(911, "TOT_NUM_REPORTS", "TotNumReports"),
    LAST_RPT_REQUESTED(912, "LAST_RPT_REQUESTED", "LastRptRequested"),
    AGREEMENT_DESC(913, "AGREEMENT_DESC", "AgreementDesc"),
    AGREEMENT_ID(914, "AGREEMENT_ID", "AgreementID"),
    AGREEMENT_DATE(915, "AGREEMENT_DATE", "AgreementDate"),
    START_DATE(916, "START_DATE", "StartDate"),
    END_DATE(917, "END_DATE", "EndDate"),
    AGREEMENT_CURRENCY(918, "AGREEMENT_CURRENCY", "AgreementCurrency"),
    DELIVERY_TYPE(919, "DELIVERY_TYPE", "DeliveryType"),
    END_ACCRUED_INTEREST_AMT(920, "END_ACCRUED_INTEREST_AMT", "EndAccruedInterestAmt"),

    START_CASH(921, "START_CASH", "StartCash"),
    END_CASH(922, "END_CASH", "EndCash"),
    USER_REQUEST_ID(923, "USER_REQUEST_ID", "UserRequestID"),
    USER_REQUEST_TYPE(924, "USER_REQUEST_TYPE", "UserRequestType"),
    NEW_PASSWORD(925, "NEW_PASSWORD", "NewPassword"),
    USER_STATUS(926, "USER_STATUS", "UserStatus"),
    USER_STATUS_TEXT(927, "USER_STATUS_TEXT", "UserStatusText"),
    STATUS_VALUE(928, "STATUS_VALUE", "StatusValue"),
    STATUS_TEXT(929, "STATUS_TEXT", "StatusText"),
    REF_COMP_ID(930, "REF_COMP_ID", "RefCompID"),

    REF_SUB_ID(931, "REF_SUB_ID", "RefSubID"),
    NETWORK_RESPONSE_ID(932, "NETWORK_RESPONSE_ID", "NetworkResponseID"),
    NETWORK_REQUEST_ID(933, "NETWORK_REQUEST_ID", "NetworkRequestID"),
    LAST_NETWORK_RESPONSE_ID(934, "LAST_NETWORK_RESPONSE_ID", "LastNetworkResponseID"),
    NETWORK_REQUEST_TYPE(935, "NETWORK_REQUEST_TYPE", "NetworkRequestType"),
    NO_COMP_IDS(936, "NO_COMP_IDS", "NoCompIDs"),
    NETWORK_STATUS_RESPONSE_TYPE(937, "NETWORK_STATUS_RESPONSE_TYPE", "NetworkStatusResponseType"),
    NO_COLL_INQUIRY_QUALIFIER(938, "NO_COLL_INQUIRY_QUALIFIER", "NoCollInquiryQualifier"),
    TRD_RPT_STATUS(939, "TRD_RPT_STATUS", "TrdRptStatus"),
    AFFIRM_STATUS(940, "AFFIRM_STATUS", "AffirmStatus"),

    UNDERLYING_STRIKE_CURRENCY(941, "UNDERLYING_STRIKE_CURRENCY", "UnderlyingStrikeCurrency"),
    LEG_STRIKE_CURRENCY(942, "LEG_STRIKE_CURRENCY", "LegStrikeCurrency"),
    TIME_BRACKET(943, "TIME_BRACKET", "TimeBracket"),
    COLL_ACTION(944, "COLL_ACTION", "CollAction"),
    COLL_INQUIRY_STATUS(945, "COLL_INQUIRY_STATUS", "CollInquiryStatus"),
    COLL_INQUIRY_RESULT(946, "COLL_INQUIRY_RESULT", "CollInquiryResult"),
    STRIKE_CURRENCY(947, "STRIKE_CURRENCY", "StrikeCurrency"),
    NO_NESTED_3_PARTY_IDS(948, "NO_NESTED_3_PARTY_IDS", "NoNested3PartyIDs"),
    NESTED_3_PARTY_ID(949, "NESTED_3_PARTY_ID", "Nested3PartyID"),
    NESTED_3_PARTY_ID_SOURCE(950, "NESTED_3_PARTY_ID_SOURCE", "Nested3PartyIDSource"),

    NESTED_3_PARTY_ROLE(951, "NESTED_3_PARTY_ROLE", "Nested3PartyRole"),
    NO_NESTED_3_PARTY_SUB_IDS(952, "NO_NESTED_3_PARTY_SUB_IDS", "NoNested3PartySubIDs"),
    NESTED_3_PARTY_SUB_ID(953, "NESTED_3_PARTY_SUB_ID", "Nested3PartySubID"),
    NESTED_3_PARTY_SUB_ID_TYPE(954, "NESTED_3_PARTY_SUB_ID_TYPE", "Nested3PartySubIDType"),
    LEG_CONTRACT_SETTL_MONTH(955, "LEG_CONTRACT_SETTL_MONTH", "LegContractSettlMonth"),
    LEG_INTEREST_ACCRUAL_DATE(956, "LEG_INTEREST_ACCRUAL_DATE", "LegInterestAccrualDate"),
    /*
     *
     * End of FIX4.4
     *
     */


    /*
     * Start of FIX5.0 as defined by the FIX Protocol Specification 5.0
     *  Tags: 957-1139
     */
    FIX957_NO_STRATEGY_PARAMETERS(957, "NO_STRATEGY_PARAMETERS", "NoStrategyParameters"),
    FIX958_STRATEGY_PARAMETER_NAME(958, "STRATEGY_PARAMETER_NAME", "StrategyParameterName"),
    FIX959_STRATEGY_PARAMETER_TYPE(959, "STRATEGY_PARAMETER_TYPE", "StrategyParameterType"),
    FIX960_STRATEGY_PARAMETER_VALUE(960, "STRATEGY_PARAMETER_VALUE", "StrategyParameterValue"),

    FIX961_HOST_CROSS_ID(961, "HOST_CROSS_ID", "HostCrossID"),
    FIX962_SIDE_TIME_IN_FORCE(962, "SIDE_TIME_IN_FORCE", "SideTimeInForce"),
    FIX963_MD_REPORT_ID(963, "MD_REPORT_ID", "MDReportID"),
    FIX964_SECURITY_REPORT_ID(964, "SECURITY_REPORT_ID", "SecurityReportID"),
    FIX965_SECURITY_STATUS(965, "SECURITY_STATUS", "SecurityStatus"),
    FIX966_SETTLE_ON_OPEN_FLAG(966, "SETTLE_ON_OPEN_FLAG", "SettleOnOpenFlag"),
    FIX967_STRIKE_MULTIPLIER(967, "STRIKE_MULTIPLIER", "StrikeMultiplier"),
    FIX968_STRIKE_VALUE(968, "STRIKE_VALUE", "StrikeValue"),
    FIX969_MIN_PRICE_INCREMENT(969, "MIN_PRICE_INCREMENT", "MinPriceIncrement"),
    FIX970_POSITION_LIMIT(970, "POSITION_LIMIT", "PositionLimit"),

    FIX971_NT_POSITION_LIMIT(971, "NT_POSITION_LIMIT", "NTPositionLimit"),
    FIX972_UNDERLYING_ALLOCATION_PERCENT(972, "UNDERLYING_ALLOCATION_PERCENT", "UnderlyingAllocationPercent"),
    FIX973_UNDERLYING_CASH_AMOUNT(973, "UNDERLYING_CASH_AMOUNT", "UnderlyingCashAmount"),
    FIX974_UNDERLYING_CASH_TYPE(974, "UNDERLYING_CASH_TYPE", "UnderlyingCashType"),
    FIX975_UNDERLYING_SETTLEMENT_TYPE(975, "UNDERLYING_SETTLEMENT_TYPE", "UnderlyingSettlementType"),
    FIX976_QUANTITY_DATE(976, "QUANTITY_DATE", "QuantityDate"),
    FIX977_CONT_INT_RPT_ID(977, "CONT_INT_RPT_ID", "ContIntRptID"),
    FIX978_LATE_INDICATOR(978, "LATE_INDICATOR", "LateIndicator"),
    FIX979_INPUT_SOURCE(979, "INPUT_SOURCE", "InputSource"),
    FIX980_SECURITY_UPDATE_ACTION(980, "SECURITY_UPDATE_ACTION", "SecurityUpdateAction"),

    FIX981_NO_EXPIRATION(981, "NO_EXPIRATION", "NoExpiration"),
    FIX982_EXP_TYPE(982, "EXP_TYPE", "ExpType"),
    FIX983_EXP_QTY(983, "EXP_QTY", "ExpQty"),
    FIX984_NO_UNDERLYING_AMOUNTS(984, "NO_UNDERLYING_AMOUNTS", "NoUnderlyingAmounts"),
    FIX985_UNDERLYING_PAY_AMOUNT(985, "UNDERLYING_PAY_AMOUNT", "UnderlyingPayAmount"),
    FIX986_UNDERLYING_COLLECT_AMOUNT(986, "UNDERLYING_COLLECT_AMOUNT", "UnderlyingCollectAmount"),
    FIX987_UNDERLYING_SETTLEMENT_DATE(987, "UNDERLYING_SETTLEMENT_DATE", "UnderlyingSettlementDate"),
    FIX988_UNDERLYING_SETTLEMENT_STATUS(988, "UNDERLYING_SETTLEMENT_STATUS", "UnderlyingSettlementStatus"),
    FIX989_SECONDARY_INDIVIDUAL_ALLOC_ID(989, "SECONDARY_INDIVIDUAL_ALLOC_ID", "SecondaryIndividualAllocID"),
    FIX990_LEG_REPORT_ID(990, "LEG_REPORT_ID", "LegReportID"),

    FIX991_RND_PX(991, "RND_PX", "RndPx"),
    FIX992_INDIVIDUAL_ALLOC_TYPE(992, "INDIVIDUAL_ALLOC_TYPE", "IndividualAllocType"),
    FIX993_ALLOC_CUSTOMER_CAPACITY(993, "ALLOC_CUSTOMER_CAPACITY", "AllocCustomerCapacity"),
    FIX994_TIER_CODE(994, "TIER_CODE", "TierCode"),
    FIX996_UNIT_OF_MEASURE(996, "UNIT_OF_MEASURE", "UnitofMeasure"),
    FIX997_TIME_UNIT(997, "TIME_UNIT", "TimeUnit"),
    FIX998_UNDERLYING_UNIT_OF_MEASURE(998, "UNDERLYING_UNIT_OF_MEASURE", "UnderlyingUnitofMeasure"),
    FIX999_LEG_UNIT_OF_MEASURE(999, "LEG_UNIT_OF_MEASURE", "LegUnitofMeasure"),
    FIX1000_UNDERLYING_TIME_UNIT(1000, "UNDERLYING_TIME_UNIT", "UnderlyingTimeUnit"),


    // 1001-1100

    FIX1001_LEG_TIME_UNIT(1001, "LEG_TIME_UNIT", "LegTimeUnit"),
    FIX1002_ALLOC_METHOD(1002, "ALLOC_METHOD", "AllocMethod"),
    FIX1003_TRADE_ID(1003, "TRADE_ID", "TradeID"),
    FIX1005_SIDE_TRADE_REPORT_ID(1005, "SIDE_TRADE_REPORT_ID", "SideTradeReportID"),
    FIX1006_SIDE_FILL_STATION_CD(1006, "SIDE_FILL_STATION_CD", "SideFillStationCd"),
    FIX1007_SIDE_REASON_CD(1007, "SIDE_REASON_CD", "SideReasonCd"),
    FIX1008_SIDE_TRD_SUB_TYP(1008, "SIDE_TRD_SUB_TYP", "SideTrdSubTyp"),
    FIX1009_SIDE_QTY(1009, "SIDE_QTY", "SideQty"),

    FIX1011_MESSAGE_EVENT_SOURCE(1011, "MESSAGE_EVENT_SOURCE", "MessageEventSource"),
    FIX1012_SIDE_TRD_REG_TIMESTAMP(1012, "SIDE_TRD_REG_TIMESTAMP", "SideTrdRegTimestamp"),
    FIX1013_SIDE_TRD_REG_TIMESTAMP_TYPE(1013, "SIDE_TRD_REG_TIMESTAMP_TYPE", "SideTrdRegTimestampType"),
    FIX1014_SIDE_TRD_REG_TIMESTAMP_SRC(1014, "SIDE_TRD_REG_TIMESTAMP_SRC", "SideTrdRegTimestampSrc"),
    FIX1015_AS_OF_INDICATOR(1015, "AS_OF_INDICATOR", "AsOfIndicator"),
    FIX1016_NO_SIDE_TRD_REG_TS(1016, "NO_SIDE_TRD_REG_TS", "NoSideTrdRegTS"),
    FIX1017_LEG_OPTION_RATIO(1017, "LEG_OPTION_RATIO", "LegOptionRatio"),
    FIX1018_NO_INSTRUMENT_PARTIES(1018, "NO_INSTRUMENT_PARTIES", "NoInstrumentParties"),
    FIX1019_INSTRUMENT_PARTY_ID(1019, "INSTRUMENT_PARTY_ID", "InstrumentPartyID"),
    FIX1020_TRADE_VOLUME(1020, "TRADE_VOLUME", "TradeVolume"),

    FIX1021_MD_BOOK_TYPE(1021, "MD_BOOK_TYPE", "MDBookType"),
    FIX1022_MD_FEED_TYPE(1022, "MD_FEED_TYPE", "MDFeedType"),
    FIX1023_MD_PRICE_LEVEL(1023, "MD_PRICE_LEVEL", "MDPriceLevel"),
    FIX1024_MD_ORIGIN_TYPE(1024, "MD_ORIGIN_TYPE", "MDOriginType"),
    FIX1025_FIRST_PX(1025, "FIRST_PX", "FirstPx"),
    FIX1026_MD_ENTRY_SPOT_RATE(1026, "MD_ENTRY_SPOT_RATE", "MDEntrySpotRate"),
    FIX1027_MD_ENTRY_FORWARD_POINTS(1027, "MD_ENTRY_FORWARD_POINTS", "MDEntryForwardPoints"),
    FIX1028_MANUAL_ORDER_INDICATOR(1028, "MANUAL_ORDER_INDICATOR", "ManualOrderIndicator"),
    FIX1029_CUST_DIRECTED_ORDER(1029, "CUST_DIRECTED_ORDER", "CustDirectedOrder"),
    FIX1030_RECEIVED_DEPT_ID(1030, "RECEIVED_DEPT_ID", "ReceivedDeptID"),

    FIX1031_CUST_ORDER_HANDLING_INST(1031, "CUST_ORDER_HANDLING_INST", "CustOrderHandlingInst"),
    FIX1032_ORDER_HANDLING_INST_SOURCE(1032, "ORDER_HANDLING_INST_SOURCE", "OrderHandlingInstSource"),
    FIX1033_DESK_TYPE(1033, "DESK_TYPE", "DeskType"),
    FIX1034_DESK_TYPE_SOURCE(1034, "DESK_TYPE_SOURCE", "DeskTypeSource"),
    FIX1035_DESK_ORDER_HANDLING_INST(1035, "DESK_ORDER_HANDLING_INST", "DeskOrderHandlingInst"),
    FIX1036_EXEC_ACK_STATUS(1036, "EXEC_ACK_STATUS", "ExecAckStatus"),
    FIX1037_UNDERLYING_DELIVERY_AMOUNT(1037, "UNDERLYING_DELIVERY_AMOUNT", "UnderlyingDeliveryAmount"),
    FIX1038_UNDERLYING_CAP_VALUE(1038, "UNDERLYING_CAP_VALUE", "UnderlyingCapValue"),
    FIX1039_UNDERLYING_SETTL_METHOD(1039, "UNDERLYING_SETTL_METHOD", "UnderlyingSettlMethod"),
    FIX1040_SECONDARY_TRADE_ID(1040, "SECONDARY_TRADE_ID", "SecondaryTradeID"),

    FIX1041_FIRM_TRADE_ID(1041, "FIRM_TRADE_ID", "FirmTradeID"),
    FIX1042_SECONDARY_FIRM_TRADE_ID(1042, "SECONDARY_FIRM_TRADE_ID", "SecondaryFirmTradeID"),
    FIX1043_COLL_APPL_TYPE(1043, "COLL_APPL_TYPE", "CollApplType"),
    FIX1044_UNDERLYING_ADJUSTED_QUANTITY(1044, "UNDERLYING_ADJUSTED_QUANTITY", "UnderlyingAdjustedQuantity"),
    FIX1045_UNDERLYING_FX_RATE(1045, "UNDERLYING_FX_RATE", "UnderlyingFXRate"),
    FIX1046_UNDERLYING_FX_RATE_CALC(1046, "UNDERLYING_FX_RATE_CALC", "UnderlyingFXRateCalc"),
    FIX1047_ALLOC_POSITION_EFFECT(1047, "ALLOC_POSITION_EFFECT", "AllocPositionEffect"),
    FIX1048_DEALING_CAPACITY(1048, "DEALING_CAPACITY", "DealingCapacity"),
    FIX1049_INSTRMT_ASSIGNMENT_METHOD(1049, "INSTRMT_ASSIGNMENT_METHOD", "InstrmtAssignmentMethod"),
    FIX1050_INSTRUMENT_PARTY_ID_SOURCE(1050, "INSTRUMENT_PARTY_ID_SOURCE", "InstrumentPartyIDSource"),

    FIX1051_INSTRUMENT_PARTY_ROLE(1051, "INSTRUMENT_PARTY_ROLE", "InstrumentPartyRole"),
    FIX1052_NO_INSTRUMENT_PARTY_SUB_IDS(1052, "NO_INSTRUMENT_PARTY_SUB_IDS", "NoInstrumentPartySubIDs"),
    FIX1053_INSTRUMENT_PARTY_SUB_ID(1053, "INSTRUMENT_PARTY_SUB_ID", "InstrumentPartySubID"),
    FIX1054_INSTRUMENT_PARTY_SUB_ID_TYPE(1054, "INSTRUMENT_PARTY_SUB_ID_TYPE", "InstrumentPartySubIDType"),
    FIX1055_POSITION_CURRENCY(1055, "POSITION_CURRENCY", "PositionCurrency"),
    FIX1056_CALCULATED_CCY_LAST_QTY(1056, "CALCULATED_CCY_LAST_QTY", "CalculatedCcyLastQty"),
    FIX1057_AGGRESSOR_INDICATOR(1057, "AGGRESSOR_INDICATOR", "AggressorIndicator"),
    FIX1058_NO_UNDLY_INSTRUMENT_PARTIES(1058, "NO_UNDLY_INSTRUMENT_PARTIES", "NoUndlyInstrumentParties"),
    FIX1059_UNDLY_INSTRUMENT_PARTY_ID(1059, "UNDLY_INSTRUMENT_PARTY_ID", "UndlyInstrumentPartyID"),
    FIX1060_UNDLY_INSTRUMENT_PARTY_ID_SOURCE(1060, "UNDLY_INSTRUMENT_PARTY_ID_SOURCE", "UndlyInstrumentPartyIDSource"),

    FIX1061_UNDLY_INSTRUMENT_PARTY_ROLE(1061, "UNDLY_INSTRUMENT_PARTY_ROLE", "UndlyInstrumentPartyRole"),
    FIX1062_NO_UNDLY_INSTRUMENT_PARTY_SUB_IDS(1062, "NO_UNDLY_INSTRUMENT_PARTY_SUB_IDS", "NoUndlyInstrumentPartySubIDs"),
    FIX1063_UNDLY_INSTRUMENT_PARTY_SUB_ID(1063, "UNDLY_INSTRUMENT_PARTY_SUB_ID", "UndlyInstrumentPartySubID"),
    FIX1064_UNDLY_INSTRUMENT_PARTY_SUB_ID_TYPE(1064, "UNDLY_INSTRUMENT_PARTY_SUB_ID_TYPE", "UndlyInstrumentPartySubIDType"),
    FIX1065_BID_SWAP_POINTS(1065, "BID_SWAP_POINTS", "BidSwapPoints"),
    FIX1066_OFFER_SWAP_POINTS(1066, "OFFER_SWAP_POINTS", "OfferSwapPoints"),
    FIX1067_LEG_BID_FORWARD_POINTS(1067, "LEG_BID_FORWARD_POINTS", "LegBidForwardPoints"),
    FIX1068_LEG_OFFER_FORWARD_POINTS(1068, "LEG_OFFER_FORWARD_POINTS", "LegOfferForwardPoints"),
    FIX1069_SWAP_POINTS(1069, "SWAP_POINTS", "SwapPoints"),
    FIX1070_MD_QUOTE_TYPE(1070, "MD_QUOTE_TYPE", "MDQuoteType"),

    FIX1071_LAST_SWAP_POINTS(1071, "LAST_SWAP_POINTS", "LastSwapPoints"),
    FIX1072_SIDE_GROSS_TRADE_AMT(1072, "SIDE_GROSS_TRADE_AMT", "SideGrossTradeAmt"),
    FIX1073_LEG_LAST_FORWARD_POINTS(1073, "LEG_LAST_FORWARD_POINTS", "LegLastForwardPoints"),
    FIX1074_LEG_CALCULATED_CCY_LAST_QTY(1074, "LEG_CALCULATED_CCY_LAST_QTY", "LegCalculatedCcyLastQty"),
    FIX1075_LEG_GROSS_TRADE_AMT(1075, "LEG_GROSS_TRADE_AMT", "LegGrossTradeAmt"),
    FIX1079_MATURITY_TIME(1079, "MATURITY_TIME", "MaturityTime"),
    FIX1080_REF_ORDER_ID(1080, "REF_ORDER_ID", "RefOrderID"),

    FIX1081_REF_ORDER_ID_SOURCE(1081, "REF_ORDER_ID_SOURCE", "RefOrderIDSource"),
    FIX1082_SECONDARY_DISPLAY_QTY(1082, "SECONDARY_DISPLAY_QTY", "SecondaryDisplayQty"),
    FIX1083_DISPLAY_WHEN(1083, "DISPLAY_WHEN", "DisplayWhen"),
    FIX1084_DISPLAY_METHOD(1084, "DISPLAY_METHOD", "DisplayMethod"),
    FIX1085_DISPLAY_LOW_QTY(1085, "DISPLAY_LOW_QTY", "DisplayLowQty"),
    FIX1086_DISPLAY_HIGH_QTY(1086, "DISPLAY_HIGH_QTY", "DisplayHighQty"),
    FIX1087_DISPLAY_MIN_INCR(1087, "DISPLAY_MIN_INCR", "DisplayMinIncr"),
    FIX1088_REFRESH_QTY(1088, "REFRESH_QTY", "RefreshQty"),
    FIX1089_MATCH_INCREMENT(1089, "MATCH_INCREMENT", "MatchIncrement"),
    FIX1090_MAX_PRICE_LEVELS(1090, "MAX_PRICE_LEVELS", "MaxPriceLevels"),

    FIX1091_PRE_TRADE_ANONYMITY(1091, "PRE_TRADE_ANONYMITY", "PreTradeAnonymity"),
    FIX1092_PRICE_PROTECTION_SCOPE(1092, "PRICE_PROTECTION_SCOPE", "PriceProtectionScope"),
    FIX1093_LOT_TYPE(1093, "LOT_TYPE", "LotType"),
    FIX1094_PEG_PRICE_TYPE(1094, "PEG_PRICE_TYPE", "PegPriceType"),
    FIX1095_PEGGED_REF_PRICE(1095, "PEGGED_REF_PRICE", "PeggedRefPrice"),
    FIX1096_PEG_SECURITY_ID_SOURCE(1096, "PEG_SECURITY_ID_SOURCE", "PegSecurityIDSource"),
    FIX1097_PEG_SECURITY_ID(1097, "PEG_SECURITY_ID", "PegSecurityID"),
    FIX1098_PEG_SYMBOL(1098, "PEG_SYMBOL", "PegSymbol"),
    FIX1099_PEG_SECURITY_DESC(1099, "PEG_SECURITY_DESC", "PegSecurityDesc"),
    FIX1100_TRIGGER_TYPE(1100, "TRIGGER_TYPE", "TriggerType"),


    // 1101-1200

    FIX1101_TRIGGER_ACTION(1101, "TRIGGER_ACTION", "TriggerAction"),
    FIX1102_TRIGGER_PRICE(1102, "TRIGGER_PRICE", "TriggerPrice"),
    FIX1103_TRIGGER_SYMBOL(1103, "TRIGGER_SYMBOL", "TriggerSymbol"),
    FIX1104_TRIGGER_SECURITY_ID(1104, "TRIGGER_SECURITY_ID", "TriggerSecurityID"),
    FIX1105_TRIGGER_SECURITY_ID_SOURCE(1105, "TRIGGER_SECURITY_ID_SOURCE", "TriggerSecurityIDSource"),
    FIX1106_TRIGGER_SECURITY_DESC(1106, "TRIGGER_SECURITY_DESC", "TriggerSecurityDesc"),
    FIX1107_TRIGGER_PRICE_TYPE(1107, "TRIGGER_PRICE_TYPE", "TriggerPriceType"),
    FIX1108_TRIGGER_PRICE_TYPE_SCOPE(1108, "TRIGGER_PRICE_TYPE_SCOPE", "TriggerPriceTypeScope"),
    FIX1109_TRIGGER_PRICE_DIRECTION(1109, "TRIGGER_PRICE_DIRECTION", "TriggerPriceDirection"),
    FIX1110_TRIGGER_NEW_PRICE(1110, "TRIGGER_NEW_PRICE", "TriggerNewPrice"),

    FIX1111_TRIGGER_ORDER_TYPE(1111, "TRIGGER_ORDER_TYPE", "TriggerOrderType"),
    FIX1112_TRIGGER_NEW_QTY(1112, "TRIGGER_NEW_QTY", "TriggerNewQty"),
    FIX1113_TRIGGER_TRADING_SESSION_ID(1113, "TRIGGER_TRADING_SESSION_ID", "TriggerTradingSessionID"),
    FIX1114_TRIGGER_TRADING_SESSION_SUB_ID(1114, "TRIGGER_TRADING_SESSION_SUB_ID", "TriggerTradingSessionSubID"),
    FIX1115_ORDER_CATEGORY(1115, "ORDER_CATEGORY", "OrderCategory"),
    FIX1116_NO_ROOT_PARTY_IDS(1116, "NO_ROOT_PARTY_IDS", "NoRootPartyIDs"),
    FIX1117_ROOT_PARTY_ID(1117, "ROOT_PARTY_ID", "RootPartyID"),
    FIX1118_ROOT_PARTY_ID_SOURCE(1118, "ROOT_PARTY_ID_SOURCE", "RootPartyIDSource"),
    FIX1119_ROOT_PARTY_ROLE(1119, "ROOT_PARTY_ROLE", "RootPartyRole"),
    FIX1120_NO_ROOT_PARTY_SUB_IDS(1120, "NO_ROOT_PARTY_SUB_IDS", "NoRootPartySubIDs"),

    FIX1121_ROOT_PARTY_SUB_ID(1121, "ROOT_PARTY_SUB_ID", "RootPartySubID"),
    FIX1122_ROOT_PARTY_SUB_ID_TYPE(1122, "ROOT_PARTY_SUB_ID_TYPE", "RootPartySubIDType"),
    FIX1123_TRADE_HANDLING_INSTR(1123, "TRADE_HANDLING_INSTR", "TradeHandlingInstr"),
    FIX1124_ORIG_TRADE_HANDLING_INSTR(1124, "ORIG_TRADE_HANDLING_INSTR", "OrigTradeHandlingInstr"),
    FIX1125_ORIG_TRADE_DATE(1125, "ORIG_TRADE_DATE", "OrigTradeDate"),
    FIX1126_ORIG_TRADE_ID(1126, "ORIG_TRADE_ID", "OrigTradeID"),
    FIX1127_ORIG_SECONDARY_TRADE_ID(1127, "ORIG_SECONDARY_TRADE_ID", "OrigSecondaryTradeID"),
    FIX1128_APPL_VER_ID(1128, "APPL_VER_ID", "ApplVerID"),
    FIX1129_CSTM_APPL_VER_ID(1129, "CSTM_APPL_VER_ID", "CstmApplVerID"),
    FIX1130_REF_APPL_VER_ID(1130, "REF_APPL_VER_ID", "RefApplVerID"),

    FIX1131_REF_CSTM_APPL_VER_ID(1131, "REF_CSTM_APPL_VER_ID", "RefCstmApplVerID"),
    FIX1132_TZ_TRANSACT_TIME(1132, "TZ_TRANSACT_TIME", "TZTransactTime"),
    FIX1133_EX_DESTINATION_ID_SOURCE(1133, "EX_DESTINATION_ID_SOURCE", "ExDestinationIDSource"),
    FIX1134_REPORTED_PX_DIFF(1134, "REPORTED_PX_DIFF", "ReportedPxDiff"),
    FIX1135_RPT_SYS(1135, "RPT_SYS", "RptSys"),
    FIX1136_ALLOC_CLEARING_FEE_INDICATOR(1136, "ALLOC_CLEARING_FEE_INDICATOR", "AllocClearingFeeIndicator"),
    FIX1137_DEFAULT_APPL_VER_ID(1137, "DEFAULT_APPL_VER_ID", "DefaultApplVerID"),
    FIX1138_DISPLAY_QTY(1138, "DISPLAY_QTY", "DisplayQty"),
    FIX1139_EXCHANGE_SPECIAL_INSTRUCTIONS(1139, "EXCHANGE_SPECIAL_INSTRUCTIONS", "ExchangeSpecialInstructions");
    /*
     *
     * End of FIX5.0
     *
     */


    ///////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////


    private final String id;
    private final String name;
    private final String description;

    /*
     * used in @Test routine.
     */
    public final static String JUNK_ENUM_NAME = "JunkEnumName";
    public final static String JUNK_ID = "JunkID";
    public final static String JUNK_NAME = "JunkName";
    public final static String JUNK_DESCRIPTION = "JunkDescription";
    public final static String JUNK_DATA_VALUE = "JunkDataValue";

    FIXType(final int id, final String name, final String description) {
        /*
         *  Even though fixNumber is an *int*, this app treats it as a String,
         *  so convert the field at load time instead of changing the lines.
         *
         *  todo: convert all definition lines to be String instead of int.
         *
         */
        this.id = String.valueOf(id);
        this.name = name;
        this.description = description;
    }

    /**
     * standard wrapper to retrieve the specific enum name
     */
    @Override

    public String getEnumName() {
        return this.name();
    }
    /**
     * standard wrapper to retrieve the specific ID code for this enum. eg: the first field
     */
    @Override
    public String getID() {
        return id;
    }
    /**
     * standard wrapper to retrieve the specific fix name for this enum. eg: the second field
     */
    @Override
    public String getName() {
        return name;
    }
    /**
     * standard wrapper to retrieve the specific fix description for this enum. eg: the third field
     */
    @Override
    public String getDescription() {
        return description;
    }
    @Override
    public String toLogStringVerbose() {
        return this.getClass().getSimpleName()
                .concat("\n\tFIXTypeName[")
                .concat(getEnumName())
                .concat("]")
                .concat("\n\tFIXNumber[")
                .concat(getID())
                .concat("]")
                .concat("\n\tFIXName[")
                .concat(getName())
                .concat("]")
                .concat("\n\tFIXDescription[")
                .concat(getDescription())
                .concat("]");
    }
    @Override
    public String toString() {
        return getEnumName()
                .concat("=[")
                .concat(getID())
                .concat(",")
                .concat(getName())
                .concat(",")
                .concat(getDescription())
                .concat("]");
    }

    /**
     *
     * @param args Not used.
     */
    public static void main(String[] args) {
        /*
         * dump all the enum values
         */
        for (FIXType oneFIX : FIXType.values()) {
            System.out.println(oneFIX);
        }
    }
}
